// Code generated by "stringer -output=enum_strings.go -type=RunningState,ExpansionUnitState"; DO NOT EDIT.

package portforwardingautosetup

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PF_AUTO_SETUP_NONE-0]
	_ = x[PF_AUTO_SETUP_RUNNING-1]
	_ = x[PF_AUTO_SETUP_CANCELED-2]
	_ = x[PF_AUTO_SETUP_FINISHED_WITH_ERROR-3]
	_ = x[PF_AUTO_SETUP_FINISHED_SUCCESSFULLY-4]
}

const _RunningState_name = "PF_AUTO_SETUP_NONEPF_AUTO_SETUP_RUNNINGPF_AUTO_SETUP_CANCELEDPF_AUTO_SETUP_FINISHED_WITH_ERRORPF_AUTO_SETUP_FINISHED_SUCCESSFULLY"

var _RunningState_index = [...]uint8{0, 18, 39, 61, 94, 129}

func (i RunningState) String() string {
	if i < 0 || i >= RunningState(len(_RunningState_index)-1) {
		return "RunningState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RunningState_name[_RunningState_index[i]:_RunningState_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PF_AUTO_SETUP_UNIT_ALREADY_EXISTS-0]
	_ = x[PF_AUTO_SETUP_UNIT_PENDING-1]
	_ = x[PF_AUTO_SETUP_UNIT_ADDED-2]
	_ = x[PF_AUTO_SETUP_UNIT_ERROR-3]
}

const _ExpansionUnitState_name = "PF_AUTO_SETUP_UNIT_ALREADY_EXISTSPF_AUTO_SETUP_UNIT_PENDINGPF_AUTO_SETUP_UNIT_ADDEDPF_AUTO_SETUP_UNIT_ERROR"

var _ExpansionUnitState_index = [...]uint8{0, 33, 59, 83, 107}

func (i ExpansionUnitState) String() string {
	if i < 0 || i >= ExpansionUnitState(len(_ExpansionUnitState_index)-1) {
		return "ExpansionUnitState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExpansionUnitState_name[_ExpansionUnitState_index[i]:_ExpansionUnitState_index[i+1]]
}
