// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package smtp was generated by IDLC from Smtp.idl.
// It is part of module devsettings.
// The remaining comment is for module devsettings.
//
// Device Settings
package smtp

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40010/idl"
)

const ERR_INVALID_PARAMS int32 = 1 // Invalid parameters

// SMTP settings interface
type Smtp interface {
	idl.Object

	// Retrieve the SMTP server configuration.
	//
	//	@return SMTP server configuration
	GetConfiguration(ctx context.Context) (Configuration, error)

	// Set the SMTP server configuration.
	//
	//	@param cfg  New SMTP server settings
	//
	//	@return 0 if OK
	//	@return 1 if any parameters are invalid
	SetConfiguration(ctx context.Context, cfg Configuration) (int32, error)

	// Test an SMTP server configuration. The active server configuration
	// is not changed.
	//
	//	@param cfg         SMTP server settings to test
	//	@param recipients  Recipient email addresses
	//
	// @result Result of configuration test
	TestConfiguration(ctx context.Context, cfg Configuration, recipients []string) (TestResult, error)
}

// SMTP server configuration
type Configuration struct {
	Host                   string // SMTP server host name or IP address
	Port                   int32  // SMTP server port
	UseTls                 bool   // Enforce TLS usage
	AllowOffTimeRangeCerts bool   // allow expired and not yet valid TLS certificates
	CaCertChain            string // TLS CA certificate chain
	Sender                 string // Sender email address
	UseAuth                bool   // SMTP server requires authentication
	Username               string // Authentication user name
	Password               string // Password; write-only, empty to leave unchanged
	RetryCount             int32  // Number of attempts at sending the email
	RetryInterval          int32  // Sending retry interval in minutes
}

// Result of SMTP configuration test
type TestResult struct {
	Status  int32  // Status code; 0 if OK
	Message string // Status message
}
