// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Code generated by "stringer -output=enum_strings.go -type=DetectionType,DeviceTypeId"; DO NOT EDIT.

package port

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AUTO-0]
	_ = x[PINNED-1]
	_ = x[DISABLED-2]
}

const _DetectionType_name = "AUTOPINNEDDISABLED"

var _DetectionType_index = [...]uint8{0, 4, 10, 18}

func (i DetectionType) String() string {
	if i < 0 || i >= DetectionType(len(_DetectionType_index)-1) {
		return "DetectionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DetectionType_name[_DetectionType_index[i]:_DetectionType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UNSPECIFIED-0]
	_ = x[OTHER-1]
	_ = x[SENSOR_HUB-2]
	_ = x[BEEPER-3]
	_ = x[ASSET_STRIP-4]
	_ = x[POWER_CIM-5]
	_ = x[GATEWAY_SENSOR-6]
}

const _DeviceTypeId_name = "UNSPECIFIEDOTHERSENSOR_HUBBEEPERASSET_STRIPPOWER_CIMGATEWAY_SENSOR"

var _DeviceTypeId_index = [...]uint8{0, 11, 16, 26, 32, 43, 52, 66}

func (i DeviceTypeId) String() string {
	if i < 0 || i >= DeviceTypeId(len(_DeviceTypeId_index)-1) {
		return "DeviceTypeId(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DeviceTypeId_name[_DeviceTypeId_index[i]:_DeviceTypeId_index[i+1]]
}
