// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package port was generated by IDLC from Port.idl.
// It is part of module portsmodel.
// The remaining comment is for module portsmodel.
//
// Ports
package port

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40413/idl"
	"github.com/arminguenther/xeruspower-go/v40413/idl/event"
	"github.com/arminguenther/xeruspower-go/v40413/peripheral/poselement"
	"github.com/arminguenther/xeruspower-go/v40413/portsmodel/portfuse"
)

// Error codes
const (
	NO_ERROR          int32 = 0 // operation successful, no error
	ERR_INVALID_PARAM int32 = 1 // invalid parameter for an operation
	ERR_DEVICE_BUSY   int32 = 2 // operation fails because connected device is busy
)

// Port interface
type Port interface {
	idl.Object

	// Get the current properties of the port
	//
	//	@return Properties of the Port
	GetProperties(ctx context.Context) (Properties, error)

	// NOT USED RIGHT NOW!
	//
	// Set the port name
	//
	//	@param  name                 new port name
	SetName(ctx context.Context, name string) error

	// Set the detection mode for the port
	//
	//	@param  mode                 new detection mode
	//	@return NO_ERROR             on success
	//	@return ERR_INVALID_PARAM    invalid parameter
	//	@return ERR_DEVICE_BUSY      device busy (e.g. Asset Strip Firmware Update)
	SetDetectionMode(ctx context.Context, mode DetectionMode) (int32, error)

	// Get all detectable devices of this port
	//
	//	@return List of all registered detectable Devices as strings
	GetDetectableDevices(ctx context.Context) ([]string, error)

	// Get the connected device of the port
	//
	//	@return Device connected to Port
	GetDevice(ctx context.Context) (idl.Object, error)

	// Get device type specific configuration interface.
	//
	//	@param deviceType    Device type to get configuration interface for
	//
	//	@return              Device configuration interface
	GetDeviceConfig(ctx context.Context, deviceType string) (idl.Object, error)

	// Get the fuse for this port
	//
	//	@return A fuse instance, if available
	GetFuse(ctx context.Context) (portfuse.PortFuse, error)
}

// Port detection type
type DetectionType int

const (
	AUTO     DetectionType = iota // auto-detection of connected devices
	PINNED                        // port is pinned to a specific device type
	DISABLED                      // port is disabled and will not detect any device connected
)

// devices types that may be connected to port
type DeviceTypeId int

const (
	UNSPECIFIED    DeviceTypeId = iota // not specified, means "not detected" in Properties.detectedDeviceTypeId
	OTHER                              // other types, not listed below
	SENSOR_HUB                         // sensor hub
	BEEPER                             // external beeper
	ASSET_STRIP                        // asset strip
	POWER_CIM                          // power cim
	GATEWAY_SENSOR                     // modbus RTU gateway sensor
)

type DeviceTypeWithId struct {
	Id   DeviceTypeId // device type ID
	Type string       // device type string
}

// Port detection mode
type DetectionMode struct {
	Type             DetectionType // detection type: auto or pinned
	PinnedDeviceType string        // contains specific device type in pinned mode, not used for auto
}

// Port properties
type Properties struct {
	Name                  string                  // user-defined name - NOT USED RIGHT NOW!
	Label                 string                  // label on device
	Mode                  DetectionMode           // detection mode
	DetectedDeviceType    string                  // detected device type or empty if nothing connected
	DetectedDeviceName    string                  // detected device name or empty if nothing connected
	PinnedDeviceTypeId    DeviceTypeId            // contains specific device type ID in pinned mode, or UNSPECIFIED if not pinned
	DetectedDeviceTypeId  DeviceTypeId            // detected device type ID or UNSPECIFIED if nothing connected
	DetectableDeviceTypes []DeviceTypeWithId      // all detectable devices of this port as ID-string pairs
	TopoId                string                  // short id depending on position, e.g. 'REMOTE-HUB-1' or 'USB-2-1-4'
	SerialId              string                  // serial number of device, e.g. for USB Dongle, maybe empty
	PortType              poselement.PortType     // machine-readable port type information
	Position              []poselement.PosElement // full machine-readable position information
}

// Event: The port properties have changed
type PropertiesChangedEvent interface {
	event.Event
	OldProperties() Properties // Properties before change
	NewProperties() Properties // Properties after change
	isPropertiesChangedEvent()
}

// Event: The device connected to the port has changed
type DeviceChangedEvent interface {
	event.Event
	OldDevice() idl.Object // Connected device before change
	NewDevice() idl.Object // Connected device after change
	isDeviceChangedEvent()
}
