// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package port was generated by IDLC from Port.idl.
// It is part of module portsmodel.
// The remaining comment is for module portsmodel.
//
// Ports
package port

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40032/idl"
	"github.com/arminguenther/xeruspower-go/v40032/idl/event"
	"github.com/arminguenther/xeruspower-go/v40032/portsmodel/portfuse"
)

// Error codes
const (
	NO_ERROR          int32 = 0 // operation successful, no error
	ERR_INVALID_PARAM int32 = 1 // invalid parameter for an operation
	ERR_DEVICE_BUSY   int32 = 2 // operation fails because connected device is busy
)

// Port interface
type Port interface {
	idl.Object

	// Get the current properties of the port
	//
	//	@return Properties of the Port
	GetProperties(ctx context.Context) (Properties, error)

	// NOT USED RIGHT NOW!
	//
	// Set the port name
	//
	//	@param  name                 new port name
	SetName(ctx context.Context, name string) error

	// Set the detection mode for the port
	//
	//	@param  mode                 new detection mode
	//	@return NO_ERROR             on success
	//	@return ERR_INVALID_PARAM    invalid parameter
	//	@return ERR_DEVICE_BUSY      device busy (e.g. Asset Strip Firmware Update)
	SetDetectionMode(ctx context.Context, mode DetectionMode) (int32, error)

	// Get all detectable devices of this port
	//
	//	@return List of all registered detectable Devices
	GetDetectableDevices(ctx context.Context) ([]string, error)

	// Get the connected device of the port
	//
	//	@return Device connected to Port
	GetDevice(ctx context.Context) (idl.Object, error)

	// Get device type specific configuration interface.
	//
	//	@param deviceType    Device type to get configuration interface for
	//
	//	@return              Device configuration interface
	GetDeviceConfig(ctx context.Context, deviceType string) (idl.Object, error)

	// Get the fuse for this port
	//
	//	@return A fuse instance, if available
	GetFuse(ctx context.Context) (portfuse.PortFuse, error)
}

// Port detection type
type DetectionType int

const (
	AUTO     DetectionType = iota // auto detection of connected devices
	PINNED                        // port is pinned to a specific device type
	DISABLED                      // port is disabled and will not detect any device connected
)

// Port detection mode
type DetectionMode struct {
	Type             DetectionType // detection type: auto or pinned
	PinnedDeviceType string        // contains specific device type in pinned mode, not used for auto
}

// Port properties
type Properties struct {
	Name               string        // user defineable name - NOT USED RIGHT NOW!
	Label              string        // label on device
	Mode               DetectionMode // detection mode
	DetectedDeviceType string        // detected device type or empty if nothing connected
	DetectedDeviceName string        // detected device name or empty if nothing connected
}

// Event: The port properties have changed
type PropertiesChangedEvent interface {
	event.Event
	OldProperties() Properties // Properties before change
	NewProperties() Properties // Properties after change
	isPropertiesChangedEvent()
}

// Event: The device connected to the port has changed
type DeviceChangedEvent interface {
	event.Event
	OldDevice() idl.Object // Connected device before change
	NewDevice() idl.Object // Connected device after change
	isDeviceChangedEvent()
}
