// Code generated by "stringer -output=enum_strings.go -type=RangeDirection"; DO NOT EDIT.

package log

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FORWARD-0]
	_ = x[BACKWARD-1]
}

const _RangeDirection_name = "FORWARDBACKWARD"

var _RangeDirection_index = [...]uint8{0, 7, 15}

func (i RangeDirection) String() string {
	if i < 0 || i >= RangeDirection(len(_RangeDirection_index)-1) {
		return "RangeDirection(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RangeDirection_name[_RangeDirection_index[i]:_RangeDirection_index[i+1]]
}
