// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package cascademanager was generated by IDLC from CascadeManager.idl.
// It is part of module cascading.
// The remaining comment is for module cascading.
//
// Raritan JSON-RPC
package cascademanager

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40211/event/userevent"
	"github.com/arminguenther/xeruspower-go/v40211/idl"
	"github.com/arminguenther/xeruspower-go/v40211/idl/event"
)

const (
	NO_ERROR                        int32 = 0  // Operation successful, no error
	ERR_INVALID_PARAM               int32 = 1  // A parameter was invalid
	ERR_UNSUPPORTED_ON_PRIMARY_UNIT int32 = 2  // Operation not allowed for a primary unit
	ERR_UNSUPPORTED_ON_LINK_UNIT    int32 = 3  // Operation not allowed for a link unit
	ERR_LINK_ID_IN_USE              int32 = 4  // The specified link ID is already used
	ERR_HOST_IN_USE                 int32 = 5  // The specified host is already in use
	ERR_LINK_UNIT_UNREACHABLE       int32 = 6  // Could not connect to the link device
	ERR_LINK_UNIT_ACCESS_DENIED     int32 = 7  // Login to link device failed
	ERR_LINK_UNIT_REFUSED           int32 = 8  // Remote device refused to become a link unit
	ERR_UNIT_BUSY                   int32 = 9  // The unit could not respond because it was busy
	ERR_NOT_SUPPORTED               int32 = 10 // Operation not supported on this device
	ERR_PASSWORD_CHANGE_REQUIRED    int32 = 11 // The unit requires a password change
	ERR_PASSWORD_POLICY             int32 = 12 // The given password did not meet the requirements
	ERR_LINK_UNIT_COMM_FAILED       int32 = 13 // Communication with the link unit failed
	ERR_LINK_UNIT_NOT_SUPPORTED     int32 = 14 // Link unit does not support cascading
	ERR_FIRMWARE_VERSION_MISMATCH   int32 = 15 // The firmware versions between primary and link unit do not match
)

// JSON-RPC Cascade Manager
type CascadeManager interface {
	idl.Object

	// Retrieve settings for the primary unit.
	//
	//	@return Primary unit settings
	GetPrimaryUnitSettings(ctx context.Context) (PrimaryUnitSettings, error)

	// Set settings for the primary unit.
	//
	//	@param primaryUnitSettings  Primary unit settings
	//
	//	@return NO_ERROR            The operation was successful
	//	@return ERR_INVALID_PARAM   At least one of the parameters had an invalid value
	SetPrimaryUnitSettings(ctx context.Context, primaryUnitSettings PrimaryUnitSettings) (int32, error)

	// Retrieve the full cascading status for this unit.
	//
	//	@return Full cascading status
	GetStatus(ctx context.Context) (Status, error)

	// Retrieve the current Link Port status
	//
	//	@return Current Link Port status
	GetLinkPortStatus(ctx context.Context) (LinkPortStatus, error)

	// Put a new link unit under this primary unit's control.
	//
	// The login credentials must have administrator privileges on the link
	// unit. They are only used to establish a trust relationship between
	// primary and link unit and not stored.
	//
	// This method can also be used to re-authenticate a link unit that
	// denies access. In that case the linkId and host parameter must
	// exactly match the existing values.
	//
	//	@param linkId       The ID for the new link unit
	//	@param host         The link unit's host name or IP address
	//	@param login        The administrator login for the link unit
	//	@param password     The administrator password for the link unit
	//	@param newPassword  The new default administrator password for the unit.
	//	                    This is needed for adding a link unit that still has default
	//	                    settings and requires a password change. Otherwise it can be
	//	                    left empty. login must be the default admin.
	//
	//	@return NO_ERROR                       The operation was successful
	//	@return ERR_INVALID_PARAM              One of the parameters had an invalid value
	//	@return ERR_UNSUPPORTED_ON_LINK_UNIT   This unit is currently a link unit and can't have link units of its own
	//	@return ERR_LINK_ID_IN_USE             The specified link ID is already in use
	//	@return ERR_HOST_IN_USE                The specified host is already in use
	//	@return ERR_LINK_UNIT_UNREACHABLE      Connection to the link unit failed
	//	@return ERR_LINK_UNIT_ACCESS_DENIED    The credentials for the link unit were invalid
	//	@return ERR_LINK_UNIT_REFUSED          The remote unit refused to become our link unit because it's a primary unit itself
	//	@return ERR_UNIT_BUSY                  This unit is currently busy with handling another request
	//	@return ERR_NOT_SUPPORTED              This device does not support PDU linking
	//	@return ERR_PASSWORD_CHANGE_REQUIRED   The specified link unit requires a password change
	//	@return ERR_PASSWORD_POLICY            The new password did not meet the requirements
	//	@return ERR_LINK_UNIT_COMM_FAILED      Communication with the link unit failed
	//	@return ERR_LINK_UNIT_NOT_SUPPORTED    Link unit does not support cascading
	//	@return ERR_FIRMWARE_VERSION_MISMATCH  The firmware version of the link unit does not match that of the primary unit
	AddLinkUnit(ctx context.Context, linkId int32, host string, login string, password string, newPassword string) (int32, error)

	// Put a new link unit under this primary unit's control.
	//
	// The login credentials must have administrator privileges on the link
	// unit. They are only used to establish a trust relationship between
	// primary and link unit and not stored.
	//
	// This method can also be used to re-authenticate a link unit that
	// denies access. In that case the linkId and host parameter must
	// exactly match the existing values.
	//
	//	@param linkId       The ID for the new link unit
	//	@param host         The link unit's host name or IP address
	//	@param login        The administrator login for the link unit
	//	@param password     The administrator password for the link unit
	//	@param newPassword  The new default administrator password for the unit.
	//	                    This is needed for adding a link unit that still has default
	//	                    settings and requires a password change. Otherwise it can be
	//	                    left empty. login must be the default admin.
	//	@param disableStrongPasswordReq  if true, this disables the strong password
	//	                                 requirements on the link unit if newPassword is set
	//
	//	@return see addLinkUnit
	AddLinkUnit2(ctx context.Context, linkId int32, host string, login string, password string, newPassword string, disableStrongPasswordReq bool) (int32, error)

	// Release a link unit from this primary unit's control.
	//
	//	@param linkId   The ID of the link unit
	//
	//	@return NO_ERROR           The operation was successful
	//	@return ERR_INVALID_PARAM  The specified link ID is invalid
	ReleaseLinkUnit(ctx context.Context, linkId int32) (int32, error)

	// Request to make this unit a link unit and put it under the remote
	// primary unit's control.
	//
	// This method is usually called by the primary unit when adding a new
	// link unit. The link will only be established once finalizeLink() is
	// successfully called.
	//
	//	@param token  Authorization token for future requests
	//
	//	@return NO_ERROR                         The operation was successful
	//	@return ERR_UNSUPPORTED_ON_PRIMARY_UNIT  This unit is a primary unit and can't become a link unit
	//	@return ERR_NOT_SUPPORTED                This device does not support PDU linking
	RequestLink(ctx context.Context, token string) (int32, error)

	// Finalize the link with this link unit.
	//
	//	@param token  same authorization token as used for requestLink()
	//
	// This method should only be called by the primary unit in order to
	// acknowledge the establishment of the link to the link unit and
	// finalize the link build-up. The linking will only take effect once
	// the link unit received this acknowledgement.
	//
	// If this method fails, you will get the ACCESS_DENIED status for this
	// link unit and you will have to re-authenticate it.
	FinalizeLink(ctx context.Context, token string) error

	// Release this link unit from the remote primary unit's control.
	//
	// This method is usually called by the primary unit when releasing a
	// link unit. This unit will become a standalone unit.
	Unlink(ctx context.Context) error

	// Check which cascading roles this unit supports.
	//
	//	@return vector with Roles that are supported by this unit
	GetSupportedRoles(ctx context.Context) ([]Role, error)

	// Check which type of link units this unit supports.
	//
	//	@return vector with supported link unit types
	GetSupportedLinkUnitTypes(ctx context.Context) ([]LinkUnitType, error)

	// Can be called on a network cascade primary unit to add expansion
	// units of the network cascade as link units.
	//
	//	@param linkId                The ID for the new link unit
	//	@param nodeIndex             The expansion unit's index in the network cascade (1 - 15)
	//	@param login                 The administrator login for the link unit
	//	@param password              The administrator password for the link unit
	//	@param positionDependent     If true, host names that depend on the nodex index will be used.
	//	                             If false, unique link-local IPv6 addresses will be used for linking.
	//
	//	@return see addLinkUnit
	AddCascadeLinkUnit(ctx context.Context, linkId int32, nodeIndex int32, login string, password string, positionDependent bool) (int32, error)

	// Add a neighbor that was discovered on the link port as link unit. If
	// a new password needs to be set, it will be generated.
	//
	//	@return NO_ERROR                       The operation was successful
	//	@return ERR_INVALID_PARAM              No neighbor currently discovered or no link id left
	//	@return ERR_UNSUPPORTED_ON_LINK_UNIT   This unit is currently a link unit and can't have link units of its own
	//	@return ERR_HOST_IN_USE                The link port neighbor was already added
	//	@return ERR_LINK_UNIT_UNREACHABLE      Connection to the link unit failed
	//	@return ERR_LINK_UNIT_ACCESS_DENIED    The credentials for the link unit were invalid
	//	@return ERR_LINK_UNIT_REFUSED          The remote unit refused to become our link unit because it's a primary unit itself
	//	@return ERR_UNIT_BUSY                  This unit is currently busy with handling another request
	//	@return ERR_NOT_SUPPORTED              This device does not support PDU linking via link port
	//	@return ERR_LINK_UNIT_COMM_FAILED      Communication with the link unit failed
	//	@return ERR_LINK_UNIT_NOT_SUPPORTED    Link unit does not support cascading
	//	@return ERR_FIRMWARE_VERSION_MISMATCH  The firmware version of the link unit does not match that of the primary unit
	AddLinkPortLinkUnit(ctx context.Context) (int32, error)

	// Add a serial link unit (ScalePoint Base).
	//
	// As a special case, link ID 1 is used to pair the primary unit on the
	// "internal" RS485 bus. It will not be added to the list of link units.
	//
	//	@param linkId       The ID for the new link unit
	//	@param installKey   The install key from the Base unit's label
	//
	//	@return NO_ERROR                       The operation was successful
	//	@return ERR_INVALID_PARAM              One of the parameters had an invalid value
	//	@return ERR_UNSUPPORTED_ON_LINK_UNIT   This unit is currently a link unit and can't have link units of its own
	//	@return ERR_LINK_ID_IN_USE             The specified link ID is already in use
	//	@return ERR_LINK_UNIT_UNREACHABLE      Connection to the link unit failed
	//	@return ERR_UNIT_BUSY                  This unit is currently busy with handling another request
	//	@return ERR_NOT_SUPPORTED              This device does not support PDU linking
	//	@return ERR_LINK_UNIT_COMM_FAILED      Communication with the link unit failed
	AddSecureSerialLinkUnit(ctx context.Context, linkId int32, installKey string) (int32, error)
}

// Settings for primary unit
type PrimaryUnitSettings struct {
	CaCertChain            string // CA certificate chain that signs the link unit TLS certs
	AllowOffTimeRangeCerts bool   // allow expired and not yet valid TLS certs
}

// JSON-RPC Cascade Role
type Role int

const (
	STANDALONE   Role = iota // Standalone unit, not in cascade
	PRIMARY_UNIT             // Primary unit controlling other devices
	LINK_UNIT                // Link unit under primary unit control
)

type LinkUnitType int

const (
	NETWORK       LinkUnitType = iota // High-level linking via JSON-RPC API
	SECURE_SERIAL                     // Linking via encrypted serial bus (ScalePoint)
)

// Link Unit Communication Status
type LinkUnitStatus int

const (
	UNKNOWN           LinkUnitStatus = iota // The status of the link unit is unknown
	OK                                      // The link unit operates normally
	UNREACHABLE                             // The link unit is unreachable
	ACCESS_DENIED                           // The link unit denies access
	FIRMWARE_UPDATE                         // This link unit is performing a firmware update
	FIRMWARE_MISMATCH                       // This link unit's firmware version does not match that of the primary unit
	PENDING                                 // The link unit becomes active after the next reboot
)

// Link Unit Status
type LinkUnit struct {
	Type      LinkUnitType   // Link unit type
	Host      string         // Link unit host name, IP address or bus address
	Status    LinkUnitStatus // Communication status
	FwVersion string         // Firmware version of the link unit
}

// Full Cascading Status
type Status struct {
	Role        Role               // This unit's role in the JSON-RPC cascade
	PrimaryUnit string             // The primary unit IP address (if role is link unit)
	LinkUnits   map[int32]LinkUnit // The list of link units (if role is primary unit)
}

// Status of the Link Port
type LinkPortStatus struct {
	IsSupported                 bool   // true, if Link Port is supported on this device
	IsLinkDetected              bool   // true, if a link on the Link Port was detected
	IsLinkingConfirmationNeeded bool   // true, if confirmation for linking via Link Port is needed
	ConnectedNeighborAddr       string // link-local IPv6 address of the currently connected neighbor, or empty
}

// Event: This unit's role in the cascade has changed
type RoleChangedEvent interface {
	event.Event
	OldRole() Role       // Previous role before the change
	NewRole() Role       // New role after the change
	PrimaryUnit() string // Primary unit IP address (if new role is link unit)
	isRoleChangedEvent()
}

// Event: A new link unit has been added
type LinkUnitAddedEvent interface {
	userevent.UserEvent
	LinkId() int32      // Link ID
	Type() LinkUnitType // Link unit type
	Host() string       // Host name, IP address or bus address
	isLinkUnitAddedEvent()
}

// Event: A link unit has been released
type LinkUnitReleasedEvent interface {
	userevent.UserEvent
	LinkId() int32      // Link ID
	Type() LinkUnitType // Link unit type
	Host() string       // Host name, IP address or bus address
	isLinkUnitReleasedEvent()
}

// Event: A link unit's communication status has changed
type LinkUnitStatusChangedEvent interface {
	event.Event
	LinkId() int32             // Link ID
	Type() LinkUnitType        // Link unit type
	Host() string              // Host name, IP address or bus address
	OldStatus() LinkUnitStatus // Previous communication status
	NewStatus() LinkUnitStatus // New communication status
	isLinkUnitStatusChangedEvent()
}

// Link Port Status changed
type LinkPortStatusChangedEvent interface {
	event.Event
	OldStatus() LinkPortStatus // Old Link Port status
	NewStatus() LinkPortStatus // New Link Port status
	isLinkPortStatusChangedEvent()
}
