// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Code generated by "stringer -output=enum_strings.go -type=Role,LinkUnitType,LinkUnitStatus"; DO NOT EDIT.

package cascademanager

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[STANDALONE-0]
	_ = x[PRIMARY_UNIT-1]
	_ = x[LINK_UNIT-2]
}

const _Role_name = "STANDALONEPRIMARY_UNITLINK_UNIT"

var _Role_index = [...]uint8{0, 10, 22, 31}

func (i Role) String() string {
	if i < 0 || i >= Role(len(_Role_index)-1) {
		return "Role(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Role_name[_Role_index[i]:_Role_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NETWORK-0]
	_ = x[SECURE_SERIAL-1]
}

const _LinkUnitType_name = "NETWORKSECURE_SERIAL"

var _LinkUnitType_index = [...]uint8{0, 7, 20}

func (i LinkUnitType) String() string {
	if i < 0 || i >= LinkUnitType(len(_LinkUnitType_index)-1) {
		return "LinkUnitType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LinkUnitType_name[_LinkUnitType_index[i]:_LinkUnitType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UNKNOWN-0]
	_ = x[OK-1]
	_ = x[UNREACHABLE-2]
	_ = x[ACCESS_DENIED-3]
	_ = x[FIRMWARE_UPDATE-4]
	_ = x[FIRMWARE_MISMATCH-5]
	_ = x[PENDING-6]
}

const _LinkUnitStatus_name = "UNKNOWNOKUNREACHABLEACCESS_DENIEDFIRMWARE_UPDATEFIRMWARE_MISMATCHPENDING"

var _LinkUnitStatus_index = [...]uint8{0, 7, 9, 20, 33, 48, 65, 72}

func (i LinkUnitStatus) String() string {
	if i < 0 || i >= LinkUnitStatus(len(_LinkUnitStatus_index)-1) {
		return "LinkUnitStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LinkUnitStatus_name[_LinkUnitStatus_index[i]:_LinkUnitStatus_index[i+1]]
}
