// Code generated by "stringer -output=enum_strings.go -type=Parity"; DO NOT EDIT.

package modbus

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NONE-0]
	_ = x[EVEN-1]
	_ = x[ODD-2]
}

const _Parity_name = "NONEEVENODD"

var _Parity_index = [...]uint8{0, 4, 8, 11}

func (i Parity) String() string {
	if i < 0 || i >= Parity(len(_Parity_index)-1) {
		return "Parity(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Parity_name[_Parity_index[i]:_Parity_index[i+1]]
}
