// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package eventservice was generated by IDLC from EventService.idl.
// It is part of module event.
// The remaining comment is for module event.
//
// Event interface
package eventservice

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40040/idl"
	"github.com/arminguenther/xeruspower-go/v40040/idl/event"
)

// Consumer interface is for event consumers that want to be
// called back in case new events have occured. Subscription
// with this interface happens in Channel interface.
// Note that this interface cannot be used over transports that
// do not support callbacks.
//
// Not available via JSON-RPC.
type Consumer interface {
	idl.Object

	// This method is called by EventService to notify Consumer
	// about new events. Consumer is not supposed to block this
	// function but return immidiately. Policy of how often and
	// with how many events this method is called is up to the
	// EventService Implementation.
	PushEvents(ctx context.Context, events []event.Event) error
}

// Event Channel
type Channel interface {
	idl.Object

	// Subscribe for events of a given type.
	//
	//	@param evttype typecode of valueobject of demanded event
	DemandEventType(ctx context.Context, type_ idl.TypeCode) error

	// Cancel the subscription for events of a given type.
	//
	//	@param evttype typecode of valueobject of demanded event
	CancelEventType(ctx context.Context, type_ idl.TypeCode) error

	// Subscribe for multiple event types at once.
	//
	//	@param evttypes  List of event typecodes
	DemandEventTypes(ctx context.Context, types []idl.TypeCode) error

	// Cancel subscription for events that are of any of given types.
	//
	//	@param evttypes  List of event typecodes
	CancelEventTypes(ctx context.Context, types []idl.TypeCode) error

	// Subscribe for events that are of given type and emitted by a
	// specific object instance.
	//
	//	@param evttype  Event typecode
	//	@param src      Event source instance
	DemandEvent(ctx context.Context, type_ idl.TypeCode, src idl.Object) error

	// Cancel the subscription for events that are of given type and
	// emitted by a specific object instance.
	//
	//	@param evttype  Event typecode
	//	@param src      Event source instance
	CancelEvent(ctx context.Context, type_ idl.TypeCode, src idl.Object) error

	// Subscribe for multiple specific events at once.
	//
	//	@param events  List of typecodes to subscribe for
	DemandEvents(ctx context.Context, events []ChannelEventSelect) error

	// Cancel the subscription for multiple specific events.
	//
	//	@param events  List of typecodes to unsubscribe from
	CancelEvents(ctx context.Context, events []ChannelEventSelect) error

	// Subsribe for push notifications from EventService.
	//
	// Not available via JSON-RPC.
	//
	//	@param consumer interface on which subscriber is called back.
	Subscribe(ctx context.Context, consumer Consumer) error

	// Unsubscribe from  push notifications from EventService.
	//
	// Not available via JSON-RPC.
	//
	//	@param consumer interface which was used for the subscription.
	//	@return 0 if OK
	//	        1 if consumer is unknown to channel
	Unsubscribe(ctx context.Context, consumer Consumer) (int32, error)

	// Poll for new events blockingly.
	//
	// This method will block in case the queue is empty. It will return
	// as soon as at least one event is available, or after a maximum
	// wait time of 30 seconds.
	//
	// The method will not return more than an implementation-defined
	// maximum number of events. The boolean return value indicates
	// whether there are more events in the queue.
	//
	//	@param events List of new events
	//	@return true if there are more events in the queue
	//	        false if the queue is empty
	PollEvents(ctx context.Context) (ret bool, events []event.Event, err error)

	// Poll for new events non-blockingly.
	//
	// The method will not return more than an implementation-defined
	// maximum number of events. The boolean return value indicates
	// whether there are more events in the queue.
	//
	//	@param events List of new events
	//	@return true if there are more events in the queue
	//	        false if the queue is empty
	PollEventsNb(ctx context.Context) (ret bool, events []event.Event, err error)
}

// Structure to select an Event *
type ChannelEventSelect struct {
	Type idl.TypeCode
	Src  idl.Object
}

const INVALID_CHANNEL int32 = 1

// Event Service
type Service interface {
	idl.Object

	// Create a new event channel.
	//
	//	@return New event channel reference
	//	        or nil if all channels have been used
	CreateChannel(ctx context.Context) (Channel, error)

	// Destroy an event channel.
	//
	//	@param channel  Event channel reference
	//	@return 0 if OK
	//	@return INVALID_CHANNEL if channel is not implemented by this Service
	DestroyChannel(ctx context.Context, channel Channel) (int32, error)

	// Push an Event into the service and to all existing
	// receiver channels
	PushEvent(ctx context.Context, event event.Event) error

	// Push a vector of Events into the service and to all existing
	// receiver channels
	PushEvents(ctx context.Context, events []event.Event) error
}
