// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package security was generated by IDLC from Security.idl.
// It is part of module security.
// The remaining comment is for module security.
//
// Security Configuration
package security

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40300/event/userevent"
	"github.com/arminguenther/xeruspower-go/v40300/idl"
)

// IP packet filter policy
type IpfwPolicy int

const (
	ACCEPT IpfwPolicy = iota // Accept the packet
	DROP                     // Silently discard the packet
	REJECT                   // Discard packet, send error response
)

// IP packet filter rule
type IpfwRule struct {
	IpMask string     // Remote IP and network mask
	Policy IpfwPolicy // Filter policy
}

// IP packet filter configuration
type IpFw struct {
	Enabled          bool       // true to enable packet filtering
	DefaultPolicyIn  IpfwPolicy // The default policy for inbound traffic in case no rule matches
	DefaultPolicyOut IpfwPolicy // The default policy for outbound traffic in case no rule matches
	RuleSetIn        []IpfwRule // Ordered list of inbound firewall rules
	RuleSetOut       []IpfwRule // Ordered list of outbound firewall rules
}

// Role-based access policy
type RoleAccessPolicy int

const (
	ALLOW RoleAccessPolicy = iota // Access granted
	DENY                          // Access denied
)

// Role-based access rule
type RoleAccessRule struct {
	StartIp string           // Start of IP range
	EndIp   string           // End of IP range
	RoleId  int32            // Role id
	Policy  RoleAccessPolicy // Access policy
}

// Role-based access control settings
type RoleAccessControl struct {
	Enabled       bool             // true to enable role-based access control
	DefaultPolicy RoleAccessPolicy // Default policy
	Rules         []RoleAccessRule // List of access rules
}

// User blocking settings
type BlockSettings struct {
	MaxFailedLogins    int32 // The number of failed logins before blocking a user
	BlockTimeout       int32 // Time (in minutes) the account will be blocked
	FailedLoginTimeout int32 // Time (in minutes) before resetting the failure counter
}

// Password settings
type PasswordSettings struct {
	EnableAging     bool  // true to enable password aging
	AgingInterval   int32 // Aging interval in days
	EnableStrongReq bool  // true to enable strong password requirements
	MinPwLength     int32 // Minimum password length
	MaxPwLength     int32 // Maximum password length
	EnforceLower    bool  // Passwords must contain at least one lower case character
	EnforceUpper    bool  // Passwords must contain at least one upper case character
	EnforceNumeric  bool  // Passwords must contain at least one numeric character
	EnforceSpecial  bool  // Passwords must contain at least one special character
	PwHistoryDepth  int32 // Number of entries in password history
}

// SSH authentication settings
type SSHSettings struct {
	AllowPasswordAuth  bool // Allow password authentication
	AllowPublicKeyAuth bool // Allow public key authentication
}

// Type of SSH host key
type SSHHostKeyType int

const (
	SSH_HOST_KEY_TYPE_RSA SSHHostKeyType = iota
	SSH_HOST_KEY_TYPE_ECDSA
	SSH_HOST_KEY_TYPE_ED25519
)

// Type of SSH key fingerprint
type SSHKeyFingerprintType int

const (
	SSH_KEY_FPRINT_TYPE_MD5_HEX SSHKeyFingerprintType = iota
	SSH_KEY_FPRINT_TYPE_SHA256_BASE64
	SSH_KEY_FPRINT_TYPE_UNKNOWN
)

// Fingerprints of SSH host key
type SSHKeyFingerprint struct {
	Fingerprint string                // Fingerprint of SSH key
	Type        SSHKeyFingerprintType // Type of fingerprint
}

// SSH host keys
type SSHHostKey struct {
	Key          string              // Public key
	Type         SSHHostKeyType      // Type of public key
	Fingerprints []SSHKeyFingerprint // Fingerprints of public key
}

// Restricted Service Agreement settings
type RestrictedServiceAgreement struct {
	Enabled bool   // Enforce Restricted Service Agreement
	Banner  string // Restricted Service Agreement Banner
}

// Information about an installed Secure Element
//
// The name TpmInfo is kept for backward compatibility.
type TpmInfo struct {
	Detected bool
}

// FIPS settings
type FipsSettings struct {
	Enabled bool // FIPS mode enabled state
}

// This Event is emitted after any of the password-settings
// has been changed
type PasswordSettingsChanged interface {
	userevent.UserEvent
	OldSettings() PasswordSettings
	NewSettings() PasswordSettings
	isPasswordSettingsChanged()
}

// Front panel privileges have been changed
type FrontPanelPrivilegesChanged interface {
	userevent.UserEvent
	OldPrivileges() []string // old front panel privileges
	NewPrivileges() []string // new front panel privileges
	isFrontPanelPrivilegesChanged()
}

const ERR_INVALID_VALUE int32 = 1 // Invalid arguments

// Security configuration interface
type Security interface {
	idl.Object

	// Retrieve the current state of the HTTP-to-HTTPS redirection.
	//
	//	@return true if the HTTP-to-HTTPS redirection is enabled
	GetHttpRedirSettings(ctx context.Context) (bool, error)

	// Enable or disable HTTP-to-HTTPS redirection.
	//
	//	@param http2httpsRedir  true to enable the redirection
	SetHttpRedirSettings(ctx context.Context, http2httpsRedir bool) error

	// Check whether HTTP Strict Transport Security (HSTS) is enabled
	//
	//	@return true when HSTS is enabled
	IsHstsEnabled(ctx context.Context) (bool, error)

	// Enable or disable HTTP Strict Transport Security (HSTS).
	//
	//	@param enable true to enable HSTS
	SetHstsEnabled(ctx context.Context, enable bool) error

	// Retrieve the IPv4 packet filter configuration.
	//
	//	@return IPv4 packet filter configuration
	GetIpFwSettings(ctx context.Context) (IpFw, error)

	// Set the IPv4 packet filter configuration.
	//
	//	@param ipFw  New packet filter settings
	//
	//	@return 0 on success
	//	@return ERR_INVALID_VALUE if any argument was invalid
	SetIpFwSettings(ctx context.Context, ipFw IpFw) (int32, error)

	// Retrieve the IPv6 packet filter configuration.
	//
	//	@return IPv6 packet filter configuration
	GetIpV6FwSettings(ctx context.Context) (IpFw, error)

	// Set the IPv6 packet filter configuration.
	//
	//	@param ipV6Fw  New packet filter settings
	//
	//	@return 0 on success
	//	@return ERR_INVALID_VALUE if any argument was invalid
	SetIpV6FwSettings(ctx context.Context, ipV6Fw IpFw) (int32, error)

	// Retrieve the role-base access control settings for IPv4.
	//
	//	@return Role-based access control settings
	GetRoleAccessControlSettings(ctx context.Context) (RoleAccessControl, error)

	// Change the role-based access control settings.
	//
	//	@param settings  New settings
	//
	//	@return 0 on success
	//	@return ERR_INVALID_VALUE if any argument was invalid
	SetRoleAccessControlSettings(ctx context.Context, settings RoleAccessControl) (int32, error)

	// Retrieve the role-base access control settings for IPv6.
	//
	//	@return Role-based access control settings
	GetRoleAccessControlSettingsV6(ctx context.Context) (RoleAccessControl, error)

	// Change the role-based access control settings for IPv6.
	//
	//	@param settings  New settings
	//
	//	@return 0 on success
	//	@return ERR_INVALID_VALUE if any argument was invalid
	SetRoleAccessControlSettingsV6(ctx context.Context, settings RoleAccessControl) (int32, error)

	// Retrieve the current user blocking settings
	//
	//	@return User blocking settings
	GetBlockSettings(ctx context.Context) (BlockSettings, error)

	// Change the user blocking settings.
	//
	//	@param settings  New settings
	//
	//	@return 0 on success
	//	@return ERR_INVALID_VALUE if any argument was invalid
	SetBlockSettings(ctx context.Context, settings BlockSettings) (int32, error)

	// Retrieve the password settings.
	//
	//	@return Password settings
	GetPwSettings(ctx context.Context) (PasswordSettings, error)

	// Change the password settings.
	//
	//	@param pwSettings  New settings
	//
	//	@return 0 on success
	//	@return ERR_INVALID_VALUE if any argument was invalid
	SetPwSettings(ctx context.Context, pwSettings PasswordSettings) (int32, error)

	// Retrieve the current idle timeout.
	//
	//	@return Idle timeout in minutes
	GetIdleTimeoutSettings(ctx context.Context) (int32, error)

	// Change the session idle timeout.
	//
	//	@param idleTimeout  New idle timeout in minutes
	//
	//	@return 0 on success
	//	@return ERR_INVALID_VALUE if any argument was invalid
	SetIdleTimeoutSettings(ctx context.Context, idleTimeout int32) (int32, error)

	// Retrieve the current single-login limitation setting.
	//
	//	@return true if single-login limitation is enabled
	GetSingleLoginLimitation(ctx context.Context) (bool, error)

	// Enable or disable single login limitation.
	//
	//	@param singleLogin  true to enable single login limitation
	SetSingleLoginLimitation(ctx context.Context, singleLogin bool) error

	// Retrieve the current SSH settings
	//
	//	@return SSH settings
	GetSSHSettings(ctx context.Context) (SSHSettings, error)

	// Change the SSH settings
	//
	//	@param settings  New settings
	SetSSHSettings(ctx context.Context, settings SSHSettings) error

	// Retrieve the host SSH keys
	//
	//	@return SSH host keys
	GetSSHHostKeys(ctx context.Context) ([]SSHHostKey, error)

	// Retrieve the current Restricted Service Agreement settings
	//
	//	@return Restricted Service Agreement settings
	GetRestrictedServiceAgreement(ctx context.Context) (RestrictedServiceAgreement, error)

	// Change the Restricted Service Agreement settings
	//
	//	@param settings  New settings
	//
	//	@return 0 on success
	//	@return ERR_INVALID_VALUE if any argument was invalid
	SetRestrictedServiceAgreement(ctx context.Context, settings RestrictedServiceAgreement) (int32, error)

	// Retrieve a list of supported privileges for the front panel
	//
	//	@return List of privilege names
	GetSupportedFrontPanelPrivileges(ctx context.Context) ([]string, error)

	// Retrieve the list of active front panel privileges
	//
	//	@return List of privilege names
	GetFrontPanelPrivileges(ctx context.Context) ([]string, error)

	// Set the privileges for the front panel
	//
	//	@return 0 on success
	//	@return ERR_INVALID_VALUE if any argument was invalid
	SetFrontPanelPrivileges(ctx context.Context, privileges []string) (int32, error)

	// Set the default admin account password and optionally disable strong password requirements.
	//
	// The purpose of this method is to set the default admin account password when the device is
	// unprovisioned, i.e. has not been configured yet or has been reset to factory defaults. The
	// difference to the regular setAccountPassword() method in the User.idl is that this method
	// allows to disable the strong password requirements at the same time. It allows choosing a
	// weaker password in case strong password requirements are not needed for the specific purpose.
	//
	//	@param password                  The new password
	//	@param disableStrongPasswordReq  true to disable strong password requirements
	//	                                 false to keep the current strong password requirement setting
	//
	//	@return  0 OK
	//	@return  1 The new password has to differ from old password.
	//	@return  2 The password must not be empty.
	//	@return  3 The password is too short.
	//	@return  4 The password is too long.
	//	@return  5 The password must not contain control characters.
	//	@return  6 The password has to contain at least one lower case character.
	//	@return  7 The password has to contain at least one upper case character.
	//	@return  8 The password has to contain at least one numeric character.
	//	@return  9 The password has to contain at least one printable special character.
	//	@return 10 The password already is in history.
	//	@return 11 SNMPv3 USM is activated for the user and the password shall be used as auth passphrase.
	//	           For this case, the password is too short (must be at least 8 characters).
	SetDefaultAdminAccountPassword(ctx context.Context, password string, disableStrongPasswordReq bool) (int32, error)

	// Set the password hash for the admin user. Naturally, this circumvents
	// checks for password complexity requirements and the password history,
	// since we only receive the salted hash of a password.
	//
	// This method is only allowed on link units when called by the primary unit.
	//
	//	@return  0 OK
	//	@return  2 The password hash must not be empty.
	SetAdminAccountPasswordHash(ctx context.Context, passwordHash string) (int32, error)

	// Check whether secure boot is active.
	//
	// ATTENTION: There are some uncertainties involved here. It is possible that it reports secure boot
	//
	//	          active while it isn't. Theoretically also the opposite is possible. For that reason
	//	          the result of this function may not be used to reduce any security checks!
	//
	//	@return true if secure boot is active
	IsSecureBootActive(ctx context.Context) (bool, error)

	// Return information about an installed Secure Element.
	//
	// The name getTpmInfo is kept for backward compatibility.
	//
	//	@return Secure Element information
	GetTpmInfo(ctx context.Context) (TpmInfo, error)

	// Get active FIPS settings.
	//
	//	@return Active FIPS settings
	GetActiveFipsSettings(ctx context.Context) (FipsSettings, error)

	// Get persistent FIPS settings.
	//
	// Those settings are applied on next boot and may differ from currently active settings.
	//
	//	@return Persistent FIPS settings
	GetPersistentFipsSettings(ctx context.Context) (FipsSettings, error)

	// Set persistent FIPS settings.
	//
	// Those settings are applied on next boot and may differ from currently active settings.
	//
	//	@param settings  new persistent FIPS settings
	SetPersistentFipsSettings(ctx context.Context, settings FipsSettings) error
}
