// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package assetstriplogger was generated by IDLC from AssetStripLogger.idl.
// It is part of module assetmgrmodel.
// The remaining comment is for module assetmgrmodel.
//
// Asset Management Model
package assetstriplogger

import (
	"context"
	"time"

	"github.com/arminguenther/xeruspower-go/v40410/assetmgrmodel/assetstrip"
	"github.com/arminguenther/xeruspower-go/v40410/idl"
)

// Error codes
const (
	NO_ERROR          int32 = 0 // Operation successful, no error
	ERR_INVALID_PARAM int32 = 1 // Invalid parameter
)

// Asset Strip Logger interface
type AssetStripLogger interface {
	idl.Object

	// Retrieve the log information.
	//
	//	@return Log information
	GetInfo(ctx context.Context) (Info, error)

	// Retrieve records from the log ring buffer.
	//
	// This method is used to read one or more records from the log ring
	// buffer. It is allowed to read unused entries. The record index
	// will wrap to 0 when reading beyond the end of the log.
	//
	//	@param records  Result: The requested log entries
	//	@param id       Index of the first log index to read (0..capacity)
	//	@param count    Number of records to read (1..capacity)
	//
	//	@return NO_ERROR on success
	//	@return ERR_INVALID_PARAM if any parameter is out of range
	GetRecords(ctx context.Context, id int32, count int32) (ret int32, records []Record, err error)
}

// Log information structure
type Info struct {
	Capacity        int32 // Maximum number of entries in the record ring buffer
	OldestRecord    int32 // Pointer to the oldest log entry; -1 if the log is empty
	NewestRecord    int32 // Pointer to the newest log entry; -1 if the log is empty
	TotalEventCount int32 // Total number of events logged
}

// Log record type
type RecordType int

const (
	EMPTY                     RecordType = iota // The log record is empty
	ASSET_TAG_CONNECTED                         // An asset tag has been connected
	ASSET_TAG_DISCONNECTED                      // An asset tag has been disconnected
	ASSET_STRIP_STATE_CHANGED                   // The state of the asset strip changed
)

// Log record structure
type Record struct {
	Timestamp        time.Time        // Time of log entry creation (UNIX timestamp, UTC)
	Type             RecordType       // Entry type
	AssetStripNumber int32            // Asset strip number (0-based), -1 if unknown
	RackUnitNumber   int32            // Rack unit number (0-based), -1 if unknown
	RackUnitPosition int32            // Rack unit position, -1 if unknown
	SlotNumber       int32            // Blade extension slot number, -1 if unknown, 0 is main strip, >0 is blade
	TagId            string           // The ID of the asset management tag, empty if unknown
	ParentBladeId    string           // ID of the parent blade extension tag in case slotNumber>0, empty otherwise
	State            assetstrip.State // Asset strip state
}
