// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Code generated by "stringer -output=enum_strings.go -type=RecordType"; DO NOT EDIT.

package assetstriplogger

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EMPTY-0]
	_ = x[ASSET_TAG_CONNECTED-1]
	_ = x[ASSET_TAG_DISCONNECTED-2]
	_ = x[ASSET_STRIP_STATE_CHANGED-3]
}

const _RecordType_name = "EMPTYASSET_TAG_CONNECTEDASSET_TAG_DISCONNECTEDASSET_STRIP_STATE_CHANGED"

var _RecordType_index = [...]uint8{0, 5, 24, 46, 71}

func (i RecordType) String() string {
	if i < 0 || i >= RecordType(len(_RecordType_index)-1) {
		return "RecordType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RecordType_name[_RecordType_index[i]:_RecordType_index[i+1]]
}
