// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Code generated by "stringer -output=enum_strings.go -type=SnmpV3PrivProto,TemperatureEnum,PressureEnum,SnmpV3SecLevel,LengthEnum,SnmpV3AuthProto"; DO NOT EDIT.

package user

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DES-0]
	_ = x[AES128-1]
	_ = x[AES192-2]
	_ = x[AES256-3]
	_ = x[AES192_3DES-4]
	_ = x[AES256_3DES-5]
}

const _SnmpV3PrivProto_name = "DESAES128AES192AES256AES192_3DESAES256_3DES"

var _SnmpV3PrivProto_index = [...]uint8{0, 3, 9, 15, 21, 32, 43}

func (i SnmpV3PrivProto) String() string {
	if i < 0 || i >= SnmpV3PrivProto(len(_SnmpV3PrivProto_index)-1) {
		return "SnmpV3PrivProto(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SnmpV3PrivProto_name[_SnmpV3PrivProto_index[i]:_SnmpV3PrivProto_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DEG_C-0]
	_ = x[DEG_F-1]
}

const _TemperatureEnum_name = "DEG_CDEG_F"

var _TemperatureEnum_index = [...]uint8{0, 5, 10}

func (i TemperatureEnum) String() string {
	if i < 0 || i >= TemperatureEnum(len(_TemperatureEnum_index)-1) {
		return "TemperatureEnum(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TemperatureEnum_name[_TemperatureEnum_index[i]:_TemperatureEnum_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PASCAL-0]
	_ = x[PSI-1]
}

const _PressureEnum_name = "PASCALPSI"

var _PressureEnum_index = [...]uint8{0, 6, 9}

func (i PressureEnum) String() string {
	if i < 0 || i >= PressureEnum(len(_PressureEnum_index)-1) {
		return "PressureEnum(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PressureEnum_name[_PressureEnum_index[i]:_PressureEnum_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NO_AUTH_NO_PRIV-0]
	_ = x[AUTH_NO_PRIV-1]
	_ = x[AUTH_PRIV-2]
}

const _SnmpV3SecLevel_name = "NO_AUTH_NO_PRIVAUTH_NO_PRIVAUTH_PRIV"

var _SnmpV3SecLevel_index = [...]uint8{0, 15, 27, 36}

func (i SnmpV3SecLevel) String() string {
	if i < 0 || i >= SnmpV3SecLevel(len(_SnmpV3SecLevel_index)-1) {
		return "SnmpV3SecLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SnmpV3SecLevel_name[_SnmpV3SecLevel_index[i]:_SnmpV3SecLevel_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[METER-0]
	_ = x[FEET-1]
}

const _LengthEnum_name = "METERFEET"

var _LengthEnum_index = [...]uint8{0, 5, 9}

func (i LengthEnum) String() string {
	if i < 0 || i >= LengthEnum(len(_LengthEnum_index)-1) {
		return "LengthEnum(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LengthEnum_name[_LengthEnum_index[i]:_LengthEnum_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MD5-0]
	_ = x[SHA1-1]
	_ = x[SHA224-2]
	_ = x[SHA256-3]
	_ = x[SHA384-4]
	_ = x[SHA512-5]
}

const _SnmpV3AuthProto_name = "MD5SHA1SHA224SHA256SHA384SHA512"

var _SnmpV3AuthProto_index = [...]uint8{0, 3, 7, 13, 19, 25, 31}

func (i SnmpV3AuthProto) String() string {
	if i < 0 || i >= SnmpV3AuthProto(len(_SnmpV3AuthProto_index)-1) {
		return "SnmpV3AuthProto(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SnmpV3AuthProto_name[_SnmpV3AuthProto_index[i]:_SnmpV3AuthProto_index[i+1]]
}
