// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package numericsensor was generated by IDLC from NumericSensor.idl.
// It is part of module sensors.
// The remaining comment is for module sensors.
//
// Sensors Model
package numericsensor

import (
	"context"
	"time"

	"github.com/arminguenther/xeruspower-go/v40211/event/userevent"
	"github.com/arminguenther/xeruspower-go/v40211/idl/event"
	"github.com/arminguenther/xeruspower-go/v40211/sensors/sensor"
)

const (
	THRESHOLD_OUT_OF_RANGE  int32 = 1 // The threshold exceedes the sensor range
	THRESHOLD_INVALID       int32 = 2 // The threshold constraints are not met
	THRESHOLD_NOT_SUPPORTED int32 = 3 // The sensor does not support setting this threshold
)

// A sensor with numeric readings
type NumericSensor interface {
	sensor.Sensor

	// Retrieve the sensor metadata.
	//
	//	@return Sensor metadata
	GetMetaData(ctx context.Context) (MetaData, error)

	// Retrieve the sensor default thresholds.
	//
	//	@return Set of default thresholds
	GetDefaultThresholds(ctx context.Context) (Thresholds, error)

	// Retrieve the thresholds.
	//
	// Note: In case of peripheral devices these thresholds may be overridden
	// by the device slot configuration.
	//
	//	@return Set of configured thresholds
	GetThresholds(ctx context.Context) (Thresholds, error)

	// Change the thresholds.
	//
	// Note: In case of peripheral devices these thresholds may be overridden
	// by the device slot configuration.
	//
	//	@param thresh  New set of thresholds
	//
	//	@return 0                        if OK
	//	@return THRESHOLD_OUT_OF_RANGE   if any threshold is out of range
	//	@return THRESHOLD_INVALID        if thresholds don't meet the requirements
	//	@return THRESHOLD_NOT_SUPPORTED  if threshold is not supported
	SetThresholds(ctx context.Context, thresh Thresholds) (int32, error)

	// Get the sensor reading.
	//
	//	@return Sensor reading, not rounded
	GetReading(ctx context.Context) (Reading, error)

	// Get the min / max of sensor value.
	//
	//	@return Sensor min / max values
	GetMinMax(ctx context.Context) (MinMax, error)

	// Reset min / max of sensor value.
	ResetMinMax(ctx context.Context) error
}

// Range of possible sensor readings
type Range struct {
	Lower float64 // Minimum reading
	Upper float64 // Maximum reading
}

// Threshold capabilities
type ThresholdCapabilities struct {
	HasUpperCritical bool // Sensor has upper critical threshold
	HasUpperWarning  bool // Sensor has upper warning threshold
	HasLowerWarning  bool // Sensor has lower warning threshold
	HasLowerCritical bool // Sensor has lower critical threshold
}

// Numeric sensor metadata
type MetaData struct {
	Type sensor.TypeSpec // Sensor type, reading type and unit
	// Number of significant decimal digits.
	//
	// Indicates how many digits should be displayed
	// to the right of the decimal point. I.e. double
	// values must be rounded with this precision.
	Decdigits int32
	// Sensor accuracy in percent.
	//
	// How close in percent measurement is to actual value.
	// This value has an implicit precision of 2, i.e. the double
	// value must be rounded for 2 decimal digits before use.
	// For example a reading of 10.0 and an accuracy of 0.2
	// means the actual reading value is 10.0 +/- 0.2%.
	//
	// A value of 0 means unused.
	Accuracy float32
	// Sensor resolution.
	//
	// Minimum difference between any two measured values.
	// Must be rounded with decimal digits.
	Resolution float32
	// Sensor tolerance.
	//
	// Tolerance is given in +/- counts of the reading value.
	// It indicates a constant magnitude possible error in the
	// quantization of an analog input to the sensor.
	// Rounded with decimal digits + 1.
	//
	// A value of 0 means unused.
	Tolerance float32
	// Sensor noise threshold.
	//
	// Threshold under which sensor measurements will be ignored.
	// Sensor measurements below that value will be reported at
	// the lower bound of the sensor range.
	NoiseThreshold float32
	// Range of possible sensor readings.
	//
	// Range values are rounded with with decimal digits.
	Range         Range
	ThresholdCaps ThresholdCapabilities // Threshold capabilities
}

// Numeric sensor thresholds
type Thresholds struct {
	UpperCriticalActive   bool    // true if the upper critical threshold is enabled
	UpperCritical         float64 // Upper critical threshold
	UpperWarningActive    bool    // true if the upper warning threshold is enabled
	UpperWarning          float64 // Upper warning threshold
	LowerWarningActive    bool    // true if the lower warning threshold is enabled
	LowerWarning          float64 // Lower warning threshold
	LowerCriticalActive   bool    // true if the lower critical threshold is enabled
	LowerCritical         float64 // Lower critical threshold
	AssertionTimeout      int32   // Assertion timeout in samples
	DeassertionHysteresis float32 // Deassertion hysteresis
}

// Numeric sensor reading
type Reading struct {
	Timestamp time.Time // UNIX timestamp (UTC) of last sample
	Available bool      // true if the sensor is available
	// Numeric sensor status
	//
	// Numeric sensor status
	//
	//	The status is determined on the basis of rounded values. The
	//	rounding is done according to MetaData::decdigits. This ensures
	//	that status and value will match when displayed simultaneously,
	//	if the value is also displayed rounded.
	Status struct /*Status*/ {
		AboveUpperCritical bool // Reading is above upper critical threshold
		AboveUpperWarning  bool // Reading is above upper warning threshold
		BelowLowerWarning  bool // Reading is below lower warning threshold
		BelowLowerCritical bool // Reading is below lower critical threshold
	}
	Valid bool    // true if the sensor reading is valid
	Value float64 // Numeric sensor reading, not rounded
}

// Numeric sensor minimum / maximum values
type MinMax struct {
	MinReading          float64   // the minimum value since observedSince, not rounded
	MinReadingTimestamp time.Time // UNIX timestamp (UTC) when the minimum value has occurred
	MaxReading          float64   // the maximum value since observedSince, not rounded
	MaxReadingTimestamp time.Time // UNIX timestamp (UTC) when the maximum value has occurred
	Valid               bool      // true if min and max are valid
	ObservedSince       time.Time // UNIX timestamp (UTC) of last reset of min / max
}

// Event: Numeric sensor reading has changed
//
//	The event is sent when the Reading::value has changed enough to affect
//	a digit to be displayed according to MetaData::decdigits, or if one of
//	Reading::available, Reading::status or Reading::valid has changed.
type ReadingChangedEvent interface {
	event.Event
	NewReading() Reading // New numeric sensor reading
	isReadingChangedEvent()
}

// Event: Sensor state has changed
type StateChangedEvent interface {
	event.Event
	OldReading() Reading // Reading before state change
	NewReading() Reading // Reading after state change
	isStateChangedEvent()
}

// Event: Sensor metadata has changed
type MetaDataChangedEvent interface {
	event.Event
	OldMetaData() MetaData // Metadata before change
	NewMetaData() MetaData // Metadata after change
	isMetaDataChangedEvent()
}

// Event: Sensor default thresholds have changed
type DefaultThresholdsChangedEvent interface {
	userevent.UserEvent
	OldDefaultThresholds() Thresholds // Default thresholds set before change
	NewDefaultThresholds() Thresholds // Default thresholds set after change
	isDefaultThresholdsChangedEvent()
}

// Event: Sensor thresholds have changed
type ThresholdsChangedEvent interface {
	userevent.UserEvent
	OldThresholds() Thresholds // Threshold set before change
	NewThresholds() Thresholds // Threshold set after change
	isThresholdsChangedEvent()
}

// Event: Sensor min or max value has changed
//
//	The event is sent when MinMax::minReading or MinMax::maxReading have
//	changed enough to affect a digit to be displayed according to MetaData::decdigits,
//	or if MinMax::valid has changed.
type MinMaxChangedEvent interface {
	event.Event
	NewMinMax() MinMax // Minimum / maximum of sensor value
	isMinMaxChangedEvent()
}

// Event: Min / Max value has been reset
type MinMaxResetEvent interface {
	userevent.UserEvent
	OldMinMax() MinMax // Min / max before reset
	NewMinMax() MinMax // Min / max after reset, incl. new observedSince timestamp
	isMinMaxResetEvent()
}
