// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package controller was generated by IDLC from Controller.idl.
// It is part of module pdumodel.
// The remaining comment is for module pdumodel.
//
// PDU Model
package controller

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40410/idl"
	"github.com/arminguenther/xeruspower-go/v40410/idl/event"
)

// Sub controller statistics
type CtrlStatistic struct {
	MainCSumErrCnt int32 // Main controller CRC error counter
	SubCSumErrCnt  int32 // Sub controller CRC error counter
	TimeoutCnt     int32 // Main controller timeout counter
	ResetCnt       int32 // Controller reset counter
	EmResetCnt     int32 // Energy meter reset counter
}

const ERR_NOT_SUPPORTED int32 = 1 // Operation not supported

// Sub controller interface
type Controller interface {
	idl.Object

	// Retrieve the current status of communication with controller
	//
	//	@return communication status
	GetCommunicationStatus(ctx context.Context) (Status, error)

	// Retrieve statistics
	//
	//	@return statistics of Controller
	GetStatistics(ctx context.Context) (CtrlStatistic, error)

	// Retrieve the sub controller metadata.
	//
	//	@return Controller metadata
	GetMetaData(ctx context.Context) (MetaData, error)

	// Reset this sub controller.
	//
	// Note: Depending on the hardware setup of the specific device, calling
	//
	//	     this method may also cause other sub controllers to be reset.
	//
	//	@return 0 on success
	//	        ERR_NOT_SUPPORTED if the hardware setup doesn't allow resetting the controller
	Reset(ctx context.Context) (int32, error)
}

// Communication status
type Status int

const (
	OK                     Status = iota // Communication with controller is known to be working
	COMMUNICATION_UNSTABLE               // Controller can be communicated with sporadically
	COMMUNICATION_FAILURE                // Controller can't be communicated with
	UNKNOWN                              // Communication status is unknown, e.g. after startup
	INCOMPATIBLE                         // The characteristics of the controller don't meet the expectations
	FIRMWARE_UPDATE                      // A controller firmware update is in progress
)

// Sub controller type
type Type int

const (
	OUTLET_CTRL Type = iota // Outlet controller
	INLET_CTRL              // Inlet controller
	METER_CTRL              // General metering controller
)

// Sub controller metadata
type MetaData struct {
	Type             Type   // Controller type
	Address          string // Sub controller address
	Magic            int32  // Magic code
	VersionAvailable bool   // true if version information and serial number is available
	FwAppVersion     int32  // Firmware application version; 0 if unavailable
	FwBootVersion    int32  // Firmware bootloader version; 0 if unavailable
	HwVersion        int32  // Hardware version; 0 if unavailable
	Serial           string // Serial number; empty if unavailable
	HaveResetCnt     bool   // true if controller reset counter is available
	HaveEmResetCnt   bool   // true if energy meter reset counter is available
	IsOptional       bool   // true if this controller is optional (temporary absence may be expected)
}

// Event: Controller communication status has changed
type StatusChangedEvent interface {
	event.Event
	OldStatus() Status // Status before change
	NewStatus() Status // Status after change
	isStatusChangedEvent()
}

// Event: Controller metadata has changed
type MetaDataChangedEvent interface {
	event.Event
	OldMetaData() MetaData // Metadata before change
	NewMetaData() MetaData // Metadata after change
	isMetaDataChangedEvent()
}
