// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Code generated by "stringer -output=enum_strings.go -type=Status,Type"; DO NOT EDIT.

package controller

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OK-0]
	_ = x[COMMUNICATION_UNSTABLE-1]
	_ = x[COMMUNICATION_FAILURE-2]
	_ = x[UNKNOWN-3]
	_ = x[INCOMPATIBLE-4]
	_ = x[FIRMWARE_UPDATE-5]
}

const _Status_name = "OKCOMMUNICATION_UNSTABLECOMMUNICATION_FAILUREUNKNOWNINCOMPATIBLEFIRMWARE_UPDATE"

var _Status_index = [...]uint8{0, 2, 24, 45, 52, 64, 79}

func (i Status) String() string {
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OUTLET_CTRL-0]
	_ = x[INLET_CTRL-1]
	_ = x[METER_CTRL-2]
}

const _Type_name = "OUTLET_CTRLINLET_CTRLMETER_CTRL"

var _Type_index = [...]uint8{0, 11, 21, 31}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
