// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package sessionmanager was generated by IDLC from SessionManager.idl.
// It is part of module session.
// The remaining comment is for module session.
//
// Session Management
package sessionmanager

import (
	"context"
	"time"

	"github.com/arminguenther/xeruspower-go/v40010/idl"
)

// Session information
type Session struct {
	SessionId    int32     // ID of the session
	Username     string    // Name of user owning the session
	RemoteIp     string    // Session IP address
	ClientType   string    // Client type
	CreationTime time.Time // Session creation timestamp (seconds since system boot)
	Timeout      int32     // Session timeout in seconds
	Idle         int32     // Session idle time in seconds
	UserIdle     int32     // User idle time in seconds
}

// Session history entry
type HistoryEntry struct {
	CreationTime time.Time // Session creation timestamp (UNIX timestamp, UTC)
	RemoteIp     string    // Session IP address
	ClientType   string    // Session client type
}

const ERR_ACTIVE_SESSION_EXCLUSIVE_FOR_USER int32 = 1 // Session creation denied due to single login limitation

// Session manager interface
//
// Session manager allows clients to announce a user session,
// i.e. consecutive activity that is related to each other,
// and make use of session services.
// Depending on transport protocoll an established session
// allows simplified authentication using the session token.
// For instance, for HTTP transport implementation sessiontoken
// can be written into HTTP Header while other authentication
// schemes may be omitted (for details, see transport mapping
// documentation).
// Each session has a defined timeout and an idle timer.
// A session is deleted once idle time is equal or greater
// than session timeout. Idle timer is implicitely touched
// by transport implementation whenever a call arrives that
// can be mapped to a particular session. In addition a client
// may decide to call touchCurrentSession with userActivity flag
// set to true. In this case userIdle attribute of session is reset
// to 0. This has purely informational character and will not cause
// any further action of session manager. It may be used to determine
// user activity under the assumptions that clients may do frequent
// background calls without actual user activity.
type SessionManager interface {
	idl.Object

	// Open a new session.
	//
	// This function will create a new session for the authenticated user.
	// Upon success it will return a session token which can be used to
	// authenticate future requests.
	//
	//	@param session  Session information
	//	@param token    Returned token for the newly created session
	//
	//	@return 0 if OK
	//	@return 1 if session creation was denied due to single login limitation
	NewSession(ctx context.Context) (ret int32, session Session, token string, err error)

	// Retrieve current session information.
	//
	// This call must be authenticated using a session token.
	//
	//	@return Session information
	GetCurrentSession(ctx context.Context) (Session, error)

	// Retrieve all open sessions.
	//
	//	@return List of sessions
	GetSessions(ctx context.Context) ([]Session, error)

	// Close a session identified by its token.
	//
	//	@param sessionId ID of the session that should be closed
	//	@param reason    close reason
	CloseSession(ctx context.Context, sessionId int32, reason CloseReason) error

	// Close the current session.
	//
	// This call must be authenticated using a session token.
	//
	//	@param reason close reason
	CloseCurrentSession(ctx context.Context, reason CloseReason) error

	// Reset the current session's idle timer.
	//
	//	@param userActivity  Indicates that the session is touched
	//	                     due to user activity.
	//
	// If userActivity is not set, this is internally a NOP since
	// any RPC call will implicitly touch the session.
	// This call must be authenticated using a session token.
	TouchCurrentSession(ctx context.Context, userActivity bool) error

	// Get previous session data for the current user
	//
	//	@return History data, sorted from newer to older sessions
	GetSessionHistory(ctx context.Context) ([]HistoryEntry, error)
}

// Session close reasons
type CloseReason int

const (
	CLOSE_REASON_LOGOUT            CloseReason = iota // Regular logout
	CLOSE_REASON_TIMEOUT                              // Session timed out
	CLOSE_REASON_BROWSER_CLOSED                       // Browser window was closed
	CLOSE_REASON_FORCED_DISCONNECT                    // Session was forcibly closed
)
