// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package ldapserversettings was generated by IDLC from LdapServerSettings.idl.
// It is part of module ldapsrv.
// The remaining comment is for module ldapsrv.
//
// LDAP server interface
package ldapserversettings

// LDAP server type
type ServerType int

const (
	ACTIVE_DIRECTORY ServerType = iota // Active directory
	OPEN_LDAP                          // OpenLDAP
)

// LDAP server type
type SecurityProtocol int

const (
	SEC_PROTO_NONE     SecurityProtocol = iota // no security protocol
	SEC_PROTO_SSL                              // use SSL
	SEC_PROTO_STARTTLS                         // use STARTTLS
)

// Server settings
type ServerSettings struct {
	Id                     string           // Entry ID
	Server                 string           // IP or name of ldap server
	AdoptSettingsId        string           // Use settings from LDAP server with <ID>
	Type                   ServerType       // Type of LDAP server
	SecProto               SecurityProtocol // Security protocol
	Port                   int32            // Server port (only for SEC_PROT_NONE and SEC_PROT_STARTTLS)
	SslPort                int32            // SSL port (only for SEC_PROT_SSL)
	ForceTrustedCert       bool             // Enforce trusted certificates
	AllowOffTimeRangeCerts bool             // allow expired and not yet valid certificates
	Certificate            string           // Certificates
	AdsDomain              string           // ADS domain
	UseAnonymousBind       bool             // use anonymous bind
	BindDN                 string           // Bind DN
	BindPwd                string           // Bind password
	SearchBaseDN           string           // Base DN for search
	LoginNameAttr          string           // Login name attribute
	UserEntryObjClass      string           // User entry object class
	UserSearchFilter       string           // User search subfilter
	GroupInfoInUserEntry   bool             // Group membership info in user entry
	GroupMemberAttr        string           // Group member attribute
	GroupEntryObjClass     string           // Group entry object class
	GroupSearchFilter      string           // Group search subfilter
}
