// Code generated by "stringer -output=enum_strings.go -type=PowerState"; DO NOT EDIT.

package shelfpowersupply

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PS_OFF-0]
	_ = x[PS_ON-1]
}

const _PowerState_name = "PS_OFFPS_ON"

var _PowerState_index = [...]uint8{0, 6, 11}

func (i PowerState) String() string {
	if i < 0 || i >= PowerState(len(_PowerState_index)-1) {
		return "PowerState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PowerState_name[_PowerState_index[i]:_PowerState_index[i+1]]
}
