// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package shelfpowersupply was generated by IDLC from ShelfPowerSupply.idl.
// It is part of module pdumodel.
// The remaining comment is for module pdumodel.
//
// PDU Model
package shelfpowersupply

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40411/event/userevent"
	"github.com/arminguenther/xeruspower-go/v40411/idl/event"
	"github.com/arminguenther/xeruspower-go/v40411/pdumodel/controller"
	"github.com/arminguenther/xeruspower-go/v40411/pdumodel/edevice"
	"github.com/arminguenther/xeruspower-go/v40411/pdumodel/pole"
	"github.com/arminguenther/xeruspower-go/v40411/sensors/numericsensor"
)

const (
	ERR_OPERATION_NOT_SUPPORTED int32 = 1
	ERR_INVALID_ARGUMENT        int32 = 2
)

// Shelf power supply interface
type ShelfPowerSupply interface {
	edevice.EDevice

	// Retrieve the power supply metadata.
	//
	//	@return Metadata
	GetMetaData(ctx context.Context) (MetaData, error)

	// Get current PSU state
	//
	//	@return Current state
	GetState(ctx context.Context) (State, error)

	// Get the input (AC side) sensors.
	//
	//	@return sensors
	GetInputSensors(ctx context.Context) (InputSensors, error)

	// Get the output (DC side) sensors.
	//
	//	@return sensors
	GetOutputSensors(ctx context.Context) (OutputSensors, error)

	// Get the auxiliary sensors.
	//
	//	@return sensors
	GetPowerSupplySensors(ctx context.Context) (PowerSupplySensors, error)

	// Turn PSU on or off
	//
	//	@param pstate  New power state
	//
	//	@return 0 if OK
	//	@return 1 if the PSU does not support power control
	SetPowerState(ctx context.Context, pstate PowerState) (int32, error)

	// Set PSU fan speed override
	//
	//	@param enableOverride   true if fan speed should be overridden; false to operate fan in automatic mode
	//	@param fanSpeedPercent  New fan speed target in %
	//
	//	@return 0 if OK
	//	@return 1 if fan speed control is not supported
	//	@return 2 if the supplied target is out of range (1..100%)
	SetFanSpeedOverride(ctx context.Context, enableOverride bool, fanSpeedPercent int32) (int32, error)

	// Get the input (AC side) poles
	//
	//	@return List of poles
	GetInputPoles(ctx context.Context) ([]pole.Pole, error)

	// Get the output (DC side) poles
	//
	//	@return List of poles
	GetOutputPoles(ctx context.Context) ([]pole.Pole, error)

	// Get the controller for this power supply.
	//
	//	@return Sub controller reference
	GetController(ctx context.Context) (controller.Controller, error)
}

// Power supply metadata
type MetaData struct {
	SlotLabel                string // Label of PSU slot the PSU is plugged into
	Manufacturer             string // PSU manufacturer
	Model                    string // PSU model
	SerialNumber             string // PSU serial number
	FirmwareVersion          string // PSU firmware version (in PSU specific format)
	ProductionDate           string // Production date of PSU (in PSU specific format)
	HardwareRevision         string // Hardware revision of PDU (in PSU specific format)
	MaxOutputPower           int32  // Maximum output power of PSU (in W)
	HotplugSupported         bool   // PSU can be removed or inserted while shelf is powered
	PowerControlSupported    bool   // PSU can be turned on or off
	FanSpeedControlSupported bool   // Fan speed of PSU can be controlled
	RatedLoad                int32  // Load (in percent) at which efficiency is determined (0 if unsupported)
	EfficiencyPercent        int32  // Efficiency (in percent) at rated load (0 if unsupported)
}

// Power supply power state. Used both for switching and representing the current state
type PowerState int

const (
	PS_OFF PowerState = iota // Turn off / Power is off
	PS_ON                    // Turn on / Power is on
)

// Power supply state
type State struct {
	Available               bool       // State reading is valid
	IsPresent               bool       // PSU is plugged into the slot
	PowerState              PowerState // Current power state of PSU (always PS_ON if power control is not supported)
	FanSpeedOverridePercent int32      // Current PSU fan speed override (in %); 0 if fan speed is not overridden
}

// Power supply input (AC) sensors
type InputSensors struct {
	Voltage                 numericsensor.NumericSensor // RMS voltage sensor
	Current                 numericsensor.NumericSensor // RMS current sensor
	PeakCurrent             numericsensor.NumericSensor // Peak current sensor
	UnbalancedCurrent       numericsensor.NumericSensor // Current unbalance sensor
	ActivePower             numericsensor.NumericSensor // Active power sensor
	ReactivePower           numericsensor.NumericSensor // Reactive power sensor
	ApparentPower           numericsensor.NumericSensor // Apparent power sensor
	PowerFactor             numericsensor.NumericSensor // Power factor sensor
	DisplacementPowerFactor numericsensor.NumericSensor // Displacement power factor sensor
	ActiveEnergy            numericsensor.NumericSensor // Active energy sensor
	ApparentEnergy          numericsensor.NumericSensor // Apparent energy sensor
	PhaseAngle              numericsensor.NumericSensor // Phase angle sensor
	LineFrequency           numericsensor.NumericSensor // AC line frequency sensor
	CrestFactor             numericsensor.NumericSensor // Crest factor sensor
	VoltageThd              numericsensor.NumericSensor // Voltage total harmonic distortion sensor
	CurrentThd              numericsensor.NumericSensor // Current total harmonic distortion sensor
}

// Power supply output (DC) sensors
type OutputSensors struct {
	Voltage      numericsensor.NumericSensor // Voltage sensor
	Current      numericsensor.NumericSensor // Current sensor
	ActivePower  numericsensor.NumericSensor // Active power sensor
	ActiveEnergy numericsensor.NumericSensor // Active energy sensor
}

// Power supply auxiliary sensors
type PowerSupplySensors struct {
	Fans         map[string]numericsensor.NumericSensor // PSU fan sensors (map of position label to sensor)
	Temperatures map[string]numericsensor.NumericSensor // PSU temperature sensors (map of position label to sensor)
}

// Event: Power control was initiated
type PowerControlEvent interface {
	userevent.UserEvent
	State() PowerState // State the supply was switched to
	isPowerControlEvent()
}

// Event: Fan speed target was set
type FanSpeedControlEvent interface {
	userevent.UserEvent
	OverrideEnabled() bool // Fan speed override is enabled
	TargetPercent() int32  // Newly set fan speed target
	isFanSpeedControlEvent()
}

// Event: Power supply state has changed
type StateChangedEvent interface {
	event.Event
	OldState() State // State before change
	NewState() State // State after change
	isStateChangedEvent()
}

// Event: Metadata has changed
type MetaDataChangedEvent interface {
	event.Event
	OldMetaData() MetaData // Metadata before change
	NewMetaData() MetaData // Metadata after change
	isMetaDataChangedEvent()
}
