// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package sensorhub was generated by IDLC from SensorHub.idl.
// It is part of module peripheral.
// The remaining comment is for module peripheral.
//
// Peripheral Devices
package sensorhub

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40413/idl"
	"github.com/arminguenther/xeruspower-go/v40413/peripheral/peripheraldevicepackage"
	"github.com/arminguenther/xeruspower-go/v40413/peripheral/poselement"
	"github.com/arminguenther/xeruspower-go/v40413/portsmodel/portfuse"
)

// Sensor Hub interface
type SensorHub interface {
	idl.Object

	// Get static (hardware and firmware) information
	//
	//	@return Result: hardware and firmware information
	GetDeviceInfo(ctx context.Context) (DeviceInfo, error)

	// Retrieve hub package information
	//
	//	@return package information
	GetPackageInfo(ctx context.Context) (peripheraldevicepackage.PackageInfo, error)
}

// peripheral device hw configuration
type UpstreamType int

const (
	BUILTIN    UpstreamType = iota // a built-in hardware
	ENV_HUB                        // a not galvanically isolated environmental hub with reduced fuse capability
	REMOTE_HUB                     // a galvanically isolated remote hub with full fuse capability
)

// Information for a single hub Port
type HubPortInfo struct {
	HubPort string            // Sensor hub port a peripheral device is connected to
	Fuse    portfuse.PortFuse // Reference to the port fuse
}

// Static (type, version) information for a SensorHub.
type DeviceInfo struct {
	Serial          string                // Serial number of device
	Model           string                // Model name of device
	UpstreamType    UpstreamType          // Hardware type (indicated a certain upstream type)
	Position        poselement.PosElement // Peripheral device position element, list forms position
	ProtocolVersion int32                 // Protocol version the hub is supporting
	BootVersion     int32                 // Bootcode software version
	AppVersion      int32                 // Application code software version
	HubPortInfos    []HubPortInfo         // Information about contained hub ports
}
