// Code generated by "stringer -output=enum_strings.go -type=ScanMode,LEDMode,Orientation,LEDOperationMode,NumberingMode"; DO NOT EDIT.

package assetstripconfig

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SCANMODE_DISABLED-0]
	_ = x[SCANMODE_BOTH-1]
}

const _ScanMode_name = "SCANMODE_DISABLEDSCANMODE_BOTH"

var _ScanMode_index = [...]uint8{0, 17, 30}

func (i ScanMode) String() string {
	if i < 0 || i >= ScanMode(len(_ScanMode_index)-1) {
		return "ScanMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ScanMode_name[_ScanMode_index[i]:_ScanMode_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LED_MODE_ON-0]
	_ = x[LED_MODE_OFF-1]
	_ = x[LED_MODE_BLINK_FAST-2]
	_ = x[LED_MODE_BLINK_SLOW-3]
}

const _LEDMode_name = "LED_MODE_ONLED_MODE_OFFLED_MODE_BLINK_FASTLED_MODE_BLINK_SLOW"

var _LEDMode_index = [...]uint8{0, 11, 23, 42, 61}

func (i LEDMode) String() string {
	if i < 0 || i >= LEDMode(len(_LEDMode_index)-1) {
		return "LEDMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LEDMode_name[_LEDMode_index[i]:_LEDMode_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TOP_CONNECTOR-0]
	_ = x[BOTTOM_CONNECTOR-1]
}

const _Orientation_name = "TOP_CONNECTORBOTTOM_CONNECTOR"

var _Orientation_index = [...]uint8{0, 13, 29}

func (i Orientation) String() string {
	if i < 0 || i >= Orientation(len(_Orientation_index)-1) {
		return "Orientation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Orientation_name[_Orientation_index[i]:_Orientation_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LED_OPERATION_MANUAL-0]
	_ = x[LED_OPERATION_AUTO-1]
}

const _LEDOperationMode_name = "LED_OPERATION_MANUALLED_OPERATION_AUTO"

var _LEDOperationMode_index = [...]uint8{0, 20, 38}

func (i LEDOperationMode) String() string {
	if i < 0 || i >= LEDOperationMode(len(_LEDOperationMode_index)-1) {
		return "LEDOperationMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LEDOperationMode_name[_LEDOperationMode_index[i]:_LEDOperationMode_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TOP_DOWN-0]
	_ = x[BOTTOM_UP-1]
}

const _NumberingMode_name = "TOP_DOWNBOTTOM_UP"

var _NumberingMode_index = [...]uint8{0, 8, 17}

func (i NumberingMode) String() string {
	if i < 0 || i >= NumberingMode(len(_NumberingMode_index)-1) {
		return "NumberingMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NumberingMode_name[_NumberingMode_index[i]:_NumberingMode_index[i+1]]
}
