// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package luaservice was generated by IDLC from LuaService.idl.
// It is part of module luaservice.
// The remaining comment is for module luaservice.
//
// # Lua-Service
//
// Lua-Service is a service that you can use to upload and execute a Lua script.
//
// When the service is starting, a cleanup will be happend at first. That means
// still running scripts will be killed and it will be tested for which script is
// an option given. Does here something not match, then the script or the option
// will be deleted.
//
// After the service is launched, the option 'autoRestart' will be for any script
// evaluated. If the flag is 'true', the script is going to be executed with a
// short delay (Environment->autoStartDelay).
//
// You can download and upload a script with the commands getScript() and setScript().
// When on uploading the script name is not present a new script will be created.
// If the name is already taken, then the old script will be overwritten.
//
// Use startScript() to execute a lua script and terminateScript() to stop a script.
// If the option 'autoRestart' is set to 'true', then the script starts automatically
// after it has exited.
//
// To get the output for a script use the command getScriptOutput(). The output
// is limited to 'Environment->outputBufferSize' bytes and mapped to a virtual
// address. On the first query call the method with starting address zero. After
// that use the returned address 'nAddr' for the next request.
//
// A script can be called with arguments (see options and startWithArgs).
package luaservice

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40220/idl"
)

// A structure that descripts the state of a script.
//
// When a script is uploaded the new execState is STAT_NEW. exitCode and
// signal is not valid.
//
// When the execState is changing to STAT_TERMINATED then exitCode and signal
// will be set.
type ScriptState struct {
	ExecState  ScriptStateExecState // execution state of the script
	ExitType   ScriptStateExitType  // type of exit code
	ExitStatus int32                // exit status or signal
}

// execution state for a scripts
type ScriptStateExecState int

const (
	STAT_NEW        ScriptStateExecState = iota // the script never ran (after uploading or system (re)start)
	STAT_RUNNING                                // script state is running
	STAT_TERMINATED                             // script state is terminated
	STAT_RESTARTING                             // script is terminated and restarts after 'restart interval'
)

// Descripts the type of exitStatus
type ScriptStateExitType int

const (
	EXIT_CODE ScriptStateExitType = iota // exitStatus is an exit code
	SIGNAL                               // exitStatus is a signal
)

// some script options
type ScriptOptions struct {
	DefaultArgs map[string]string // default arguments are passed to the lua script
	AutoStart   bool              // starts a script after system booting
	AutoRestart bool              // restarts a script after termination or crash
}

// The struct represents two kinds of information:
//   - limit (l)
//   - current status (cs)
//
// Is a limit set to zero then there is no limit set. The unit of size
// is byte. The unit of interval is millisecond.
type Environment struct {
	MaxScriptMemoryGrowth int32 // maximum virtual memory growth per script  (l)
	MaxAmountOfScripts    int32 // number of scripts that can be stored  (l)
	AmountOfScripts       int32 // number of scripts that are stored  (cs)
	MaxScriptSize         int32 // maximum size of a script file  (l)
	MaxAllScriptSize      int32 // maximum size of all script files  (l)
	AllScriptSize         int32 // size of all script files  (cs)
	OutputBufferSize      int32 // output buffer size per script  (l)
	RestartInterval       int32 // minimum delay to next (re)start (cs)
	AutoStartDelay        int32 // minimum delay to 'autoStart' a script
}

// Error codes
const (
	NO_ERROR                         int32 = 0  // no Error
	ERR_INVALID_NAME                 int32 = 1  // script name is invalid
	ERR_NO_SUCH_SCRIPT               int32 = 2  // script name not found
	ERR_MAX_SCRIPT_NUMBERS_EXCEEDED  int32 = 3  // maximum amount of stored script files is reached
	ERR_MAX_SCRIPT_SIZE_EXCEEDED     int32 = 4  // maximum size of a script file is reached
	ERR_MAX_ALL_SCRIPT_SIZE_EXCEEDED int32 = 5  // maximum size of all script files is reached
	ERR_NOT_TERMINATED               int32 = 6  // script is not terminated
	ERR_NOT_RUNNING                  int32 = 7  // script is not running
	ERR_INVALID_ADDR                 int32 = 8  // address parameter is wrong
	ERR_TOO_MANY_ARGUMENTS           int32 = 10 // too many arguments
	ERR_ARGUMENT_NOT_VALID           int32 = 11 // the argument has one or more invalid characters
)

// There is a single manager instance.
type Manager interface {
	idl.Object

	// Upload a script to instance
	//
	// If there is a script with the same name the new script will replace
	// the existing script (script must be in STAT_NEW or STAT_TERMINATED).
	//
	//	@param name The name of the script file
	//	@param script The script file packed in a string
	//	@param options Options that can be set or not
	//
	//	@return NO_ERROR                           if OK
	//	@return ERR_INVALID_NAME                   if script name is invalid
	//	@return ERR_MAX_SCRIPT_SIZE_EXCEEDED       if the size of the new script is greater then the maximum file size
	//	@return ERR_MAX_ALL_SCRIPT_SIZE_EXCEEDED   if maximum size of all script files is reached
	//	@return ERR_MAX_SCRIPT_NUMBERS_EXCEEDED    if maximum amount of script files is reached
	//	@return ERR_NOT_TERMINATED                 if try to replace a running script
	SetScript(ctx context.Context, name string, script string, options ScriptOptions) (int32, error)

	// To download a script file to user.
	//
	//	@param name The name of an existing script
	//
	//	@return NO_ERROR             if OK
	//	@return ERR_INVALID_NAME     if script name is invalid
	//	@return ERR_NO_SUCH_SCRIPT   if there is no script with the name
	GetScript(ctx context.Context, name string) (ret int32, script string, err error)

	// Returns all script names in a string vector.
	//
	// If there are no scripts the vector is empty.
	//
	//	@return A vector with all script names.
	GetScriptNames(ctx context.Context) ([]string, error)

	// Deletes a script.
	//
	//	@param name The name of the script
	//
	//	@return NO_ERROR             if OK
	//	@return ERR_INVALID_NAME     if script name is invalid
	//	@return ERR_NO_SUCH_SCRIPT   if there is no script with the name
	//	@return ERR_NOT_TERMINATED   if try to delete a running script
	DeleteScript(ctx context.Context, name string) (int32, error)

	// Sets new options for a script.
	//
	//	@param name The name of the script
	//	@param options The new options
	//
	//	@return NO_ERROR                      if OK
	//	@return ERR_INVALID_NAME              if script name is invalid
	//	@return ERR_NO_SUCH_SCRIPT            if there is no script with the name
	//	@return ERR_TOO_MANY_ARGUMENTS        if the size of the map is to big
	//	@return ERR_ARGUMENT_NOT_VALID        if a string in the arguments is not
	SetScriptOptions(ctx context.Context, name string, options ScriptOptions) (int32, error)

	// Returns the options for a script.
	//
	//	@param name The name of the script
	//	@param options The return value
	//
	//	@return NO_ERROR             if OK
	//	@return ERR_INVALID_NAME     if script name is invalid
	//	@return ERR_NO_SUCH_SCRIPT   if there is no script with the name
	GetScriptOptions(ctx context.Context, name string) (ret int32, options ScriptOptions, err error)

	// To query the environment information.
	//
	//	@return a struct with the environment information
	GetEnvironment(ctx context.Context) (Environment, error)

	// To get output from a script as a string
	//
	// The output is stored in a string buffer with a defined size. The buffer is addressable with an
	// (virtual) address. The address will be increased ervery time when the buffer will be filled.
	//
	// To get the output for the first time just call with address zero and then use the returned nAddr
	// argument.
	//
	// If iAddr is negative then the last n bytes will be returned, e.g. -9 returns the last 9 characters.
	// If iAddr is zero then the whole available buffer will be returned.
	// If iAddr is positive then the returned buffer starts at this address.
	// If iAddr is equal to nAddr then there is no data available
	// If iAddr and oAddr is not equal then there were data lost (execption: first call with zero).
	//
	//	@param name The name of the script
	//	@param iAddr The virtual start address where the returned output should begin.
	//	@param oAddr The virtual address from where the string starts.
	//	@param nAddr The virtual address for the next query.
	//	@param more A boolean whitch indicates if there is more data available.
	//
	//	@return NO_ERROR                      if OK
	//	@return ERR_INVALID_NAME              if file name is invalid
	//	@return ERR_NO_SUCH_SCRIPT            if there is no script with the name
	//	@return ERR_INVALID_ADDR              if iAddr is negative and the absolute value of parameter iAddr is greater as the limit
	GetScriptOutput(ctx context.Context, name string, iAddr int64) (ret int32, oAddr int64, nAddr int64, oString string, more bool, err error)

	// Clear the output buffer of a script.
	//
	//	@param name The name of the script
	//
	//	@return NO_ERROR                      if OK
	//	@return ERR_INVALID_NAME              if file name is invalid
	//	@return ERR_NO_SUCH_SCRIPT            if there is no script with the name
	ClearScriptOutput(ctx context.Context, name string) (int32, error)

	// To start a script
	//
	// The function starts a lua script.
	//
	//	@return NO_ERROR             if OK
	//	@return ERR_INVALID_NAME     if file name is invalid
	//	@return ERR_NO_SUCH_SCRIPT   if there is no script with the name
	//	@return ERR_NOT_TERMINATED   if the script is running or restarting
	StartScript(ctx context.Context, name string) (int32, error)

	// To start a script with arguments
	//
	// The function starts a lua script. Additionally you can add arguments which are available from the
	// lua script. This args will override the default arguments. All args are stored in a global table
	// called ARGS in lua.
	//
	//	@return NO_ERROR                      if OK
	//	@return ERR_INVALID_NAME              if file name is invalid
	//	@return ERR_NO_SUCH_SCRIPT            if there is no script with the name
	//	@return ERR_NOT_TERMINATED            if the script is running or restarting
	//	@return ERR_TOO_MANY_ARGUMENTS        if the size of the map is to big
	//	@return ERR_ARGUMENT_NOT_VALID        if a string in the arguments is not valid
	StartScriptWithArgs(ctx context.Context, name string, arguments map[string]string) (int32, error)

	// To stop a script
	//
	// This command stops a running or restarting script. After terminating the option autorestart will
	// not be evaluated.
	//
	//	@return NO_ERROR             if OK
	//	@return ERR_INVALID_NAME     if file name is invalid
	//	@return ERR_NO_SUCH_SCRIPT   if there is no script with the name
	//	@return ERR_NOT_RUNNING      if the script is not running or restarting
	TerminateScript(ctx context.Context, name string) (int32, error)

	// Returns the state for a single script.
	//
	//	@param name The script name
	//	@param state The state of the script
	//
	//	@return NO_ERROR             if OK
	//	@return ERR_INVALID_NAME     if file name is invalid
	//	@return ERR_NO_SUCH_SCRIPT   if there is no script with the name
	GetScriptState(ctx context.Context, name string) (ret int32, state ScriptState, err error)

	// Returns the state for all scripts. If the map is empty then there are no scripts on the machine.
	//
	//	@return A map<string name, ScriptState state> with name and state for all available scripts.
	GetScriptStates(ctx context.Context) (map[string]ScriptState, error)
}
