// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package cfg was generated by IDLC from Cfg.idl.
// It is part of module cfg.
// The remaining comment is for module cfg.
//
// Low-Level Device Configuration Access
package cfg

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40410/idl"
)

// Configuration key-value pair
type KeyValue struct {
	Key   string // Configuration key name
	Value string // Configuration value
}

const (
	ERR_INVALID_KEY              int32 = 1 // Configuration key invalid
	ERR_INVALID_VALUE            int32 = 2 // Configuration value invalid
	ERR_NOT_ALLOWED_IN_FIPS_MODE int32 = 3 // Method disallowed in FIPS mode; currently unused
)

// Device configuration access methods
type Cfg interface {
	idl.Object

	// Retrieve one or more configuration values from the device.
	//
	//	@param values  Result: List of configuration values
	//	@param keys    List of configuration keys to return
	//
	//	@return 0 if OK
	//	@return 1 if any configuration key is invalid
	GetValues(ctx context.Context, keys []string) (ret int32, values []string, err error)

	// Set one or more configuration keys.
	//
	//	@param keyvaluepairs  List of configuration key-value pairs
	//
	//	@return 0 if OK
	//	@return 1 if any configuration key is invalid
	//	@return 2 if any configuration value is invalid
	SetValues(ctx context.Context, keyvaluepairs []KeyValue) (int32, error)
}
