// Code generated by "stringer -output=enum_strings.go -type=DongleState"; DO NOT EDIT.

package zigbeemanager

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NOT_INIT-0]
	_ = x[READY-1]
	_ = x[ERROR-2]
	_ = x[INIT_IN_PROGRESS-3]
	_ = x[FW_UPGRADE-4]
	_ = x[IN_MODEM_STATE-5]
}

const _DongleState_name = "NOT_INITREADYERRORINIT_IN_PROGRESSFW_UPGRADEIN_MODEM_STATE"

var _DongleState_index = [...]uint8{0, 8, 13, 18, 34, 44, 58}

func (i DongleState) String() string {
	if i < 0 || i >= DongleState(len(_DongleState_index)-1) {
		return "DongleState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DongleState_name[_DongleState_index[i]:_DongleState_index[i+1]]
}
