// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Code generated by "stringer -output=enum_strings.go -type=AuthType"; DO NOT EDIT.

package radiusserversettings

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PAP-0]
	_ = x[CHAP-1]
	_ = x[MSCHAPv2-2]
}

const _AuthType_name = "PAPCHAPMSCHAPv2"

var _AuthType_index = [...]uint8{0, 3, 7, 15}

func (i AuthType) String() string {
	if i < 0 || i >= AuthType(len(_AuthType_index)-1) {
		return "AuthType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AuthType_name[_AuthType_index[i]:_AuthType_index[i+1]]
}
