// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Code generated by "stringer -output=enum_strings.go -type=Status"; DO NOT EDIT.

package rawconfiguration

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UNKNOWN-0]
	_ = x[UPLOAD_FAILED-1]
	_ = x[UPDATE_PENDING-2]
	_ = x[UPDATE_OK-3]
	_ = x[UPDATE_FAILED-4]
}

const _Status_name = "UNKNOWNUPLOAD_FAILEDUPDATE_PENDINGUPDATE_OKUPDATE_FAILED"

var _Status_index = [...]uint8{0, 7, 20, 34, 43, 56}

func (i Status) String() string {
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
