// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package rawconfiguration was generated by IDLC from RawConfiguration.idl.
// It is part of module rawcfg.
// The remaining comment is for module rawcfg.
//
// Raw Configuration
package rawconfiguration

import (
	"context"
	"time"

	"github.com/arminguenther/xeruspower-go/v40010/event/userevent"
	"github.com/arminguenther/xeruspower-go/v40010/idl"
)

// Raw Configuration Interface
type RawConfiguration interface {
	idl.Object

	// Retrieve the status of the last raw configuration update
	// operation.
	//
	//	@param status     Result: Raw configuration update status
	//	@param timeStamp  Result: Time of last update operation (UNIX timestamp, UTC)
	GetStatus(ctx context.Context) (status Status, timeStamp time.Time, err error)
}

// Status of the last raw configuration update operation
type Status int

const (
	UNKNOWN        Status = iota // No raw configuration was done yet
	UPLOAD_FAILED                // Uploading a raw configuration failed
	UPDATE_PENDING               // Update is pending
	UPDATE_OK                    // Updating raw configuration successful
	UPDATE_FAILED                // Updating raw configuration failed
)

// Event: Raw configuration downloaded
type RawConfigDownloadedEvent interface {
	userevent.UserEvent
	isRawConfigDownloadedEvent()
}

// Event: Raw configuration updated
type RawConfigUpdatedEvent interface {
	userevent.UserEvent
	isRawConfigUpdatedEvent()
}
