// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package dooraccesscontrol was generated by IDLC from DoorAccessControl.idl.
// It is part of module smartlock.
// The remaining comment is for module smartlock.
package dooraccesscontrol

import (
	"context"
	"time"

	"github.com/arminguenther/xeruspower-go/v40200/event/userevent"
	"github.com/arminguenther/xeruspower-go/v40200/idl"
	"github.com/arminguenther/xeruspower-go/v40200/idl/event"
	"github.com/arminguenther/xeruspower-go/v40200/peripheral/peripheraldeviceslot"
)

const (
	ERR_INVALID_SETTINGS  int32 = 1 // Invalid settings
	ERR_NO_SUCH_ID        int32 = 2 // No such ID
	ERR_MAX_RULES_REACHED int32 = 3 // Maximum number of rules
)

// Access control for door locks
type DoorAccessControl interface {
	idl.Object

	// Get all stored door access control rules
	//
	//	@return list of rules by id
	GetDoorAccessRules(ctx context.Context) (map[int32]DoorAccessRule, error)

	// Replace all the currently existing rules. Note that this not only
	// adds and modifies rules, but also deletes existing rules that are
	// not present in the given rule set.
	//
	// In case of any rule being invalid, no changes will be made at all.
	//
	//	@param rules             the new rule set
	//	@param invalidRules      in case of an error, return ids of invalid rules
	//
	//	@return 0 if OK
	//	@return 1 if the rule set contains a rule with invalid values
	SetAllDoorAccessRules(ctx context.Context, rules map[int32]DoorAccessRule) (ret int32, invalidRuleIds []int32, err error)

	// Add a door access control rule. If successful, the id of the new
	// rule will be returned.
	//
	//	@param rule          the new rule
	//
	//	@return 0 if OK
	//	@return 1 if rule has invalid values
	//	@return 3 if maximum number of rules reached
	AddDoorAccessRule(ctx context.Context, rule DoorAccessRule) (ret int32, ruleId int32, err error)

	// Modify an existing door access control rule
	//
	//	@param id            id of the rule to modify
	//	@param modifiedRule  rule containing the new settings
	//
	//	@return 0 if OK
	//	@return 1 if modifiedRule has invalid values
	//	@return 2 if no rule with this id
	ModifyDoorAccessRule(ctx context.Context, id int32, modifiedRule DoorAccessRule) (int32, error)

	// Delete an existing door access control rule
	//
	//	@param id            id of the rule to delete
	//
	//	@return 0 if OK
	//	@return 2 if no rule with this id
	DeleteDoorAccessRule(ctx context.Context, id int32) (int32, error)
}

// A condition representing an absolute time range.
//
// Timestamps are UNIX timestamps (UTC)
type AbsoluteTimeCondition struct {
	Enabled   bool      // Condition is enabled
	ValidFrom time.Time // Time range starting from this date or 0 if not set
	ValidTill time.Time // Time range valid until this date or 0 if not set
}

// A condition representing a periodic time range.
//
// Once this condition is enabled, weekdays have to be specified in
// order to get granted access. A specific clock time range can be set
// to allow access only certain times of the day. The system's local time
// will be used (as defined by the configured time zone).
//
// The clock time range will wrap over into the next day if
// fromHourOfDay:fromMinuteOfHour >= tillHourOfDay:tillMinuteOfHour,
// meaning that the weekday of fromHourOfDay:fromMinuteOfHour will be checked.
type PeriodicTimeCondition struct {
	Enabled          bool    // Condition is enabled
	DaysOfWeek       []int32 // Range for these days of the week (valid values are 0 - 6, 0 is Sunday)
	FromHourOfDay    int32   // Range periodically starts from this hour of the day (0 - 23)
	TillHourOfDay    int32   // Range periodically ends this hour of the day (0 - 23)
	FromMinuteOfHour int32   // Specify minute of starting hour (0 - 59)
	TillMinuteOfHour int32   // Specify minute of ending hour (0 - 59)
}

// Information in order to refer to a specific card reader
type CardReaderInfo struct {
	LinkId int32 // Unit the card reader is attached to
	// Position of the card reader.
	// This can be fetched from the CardReader MetaData
	Position string
}

// Information in order to refer to a specific keypad
type KeypadInfo struct {
	LinkId int32 // Unit the keypad is attached to
	// Position of the keypad
	// This can be fetched from the Keypad MetaData
	Position string
}

// A condition for specific cards and card readers.
type CardCondition struct {
	Enabled    bool           // Condition is enabled
	CardUid    string         // Matching card uid
	CardReader CardReaderInfo // The card reader that has to be used
}

// A condition for keypads with a secret pin
type KeypadCondition struct {
	Enabled bool       // Condition is enabled
	Pin     string     // Pin that has to be entered
	Keypad  KeypadInfo // The keypad that has to be used
}

// Data representing a rule to control access to certain doors.
//
// Access is granted (i.e. the defined locks are opened) if the defined
// and enabled conditions are met. At least one CardCondition or one
// KeypadCondition must be enabled. If multiple conditions are enabled, all
// conditions have to be met during the timeout that is defined in
// conditionsTimeout.
type DoorAccessRule struct {
	Name              string                            // A name to describe this rule
	DoorHandleLocks   []peripheraldeviceslot.DeviceSlot // Open these door handle locks
	CardCondition1    CardCondition                     // Condition that has to be fulfilled when inserting a card
	CardCondition2    CardCondition                     // Additional card condition that is needed
	KeypadCondition1  KeypadCondition                   // Condition that has to be fulfilled when using a keypad
	KeypadCondition2  KeypadCondition                   // Additional keypad condition that is needed
	ConditionsTimeout int32                             // Timeout for matching multiple card / keypad conditions
	AbsoluteTime      AbsoluteTimeCondition             // Absolute time range condition
	PeriodicTime      PeriodicTimeCondition             // Periodic time range condition
}

// Door Access Denial Reason
type DoorAccessDenialReason int

const (
	DENIED_NO_MATCHING_RULE        DoorAccessDenialReason = iota // No rule that matches the triggering event
	DENIED_ABSOLUTE_TIME_CONDITION                               // Absolute time condition was not met
	DENIED_PERIODIC_TIME_CONDITION                               // Periodic time condition was not met
	DENIED_CONDITIONS_TIMEOUT                                    // A needed condition was not fulfilled during conditionsTimeout
)

// Event: Door access granted
//
// This Event will be triggered for every rule whose conditions were fulfilled.
type DoorAccessGrantedEvent interface {
	event.Event
	RuleId() int32        // Rule id of rule that granted access
	Rule() DoorAccessRule // Rule settings of rule that granted access, cardUid and pin will be filtered
	isDoorAccessGrantedEvent()
}

// Event: Door access denied
//
// This event will only be triggered if at least one DoorAccessRule
// exists and a card was inserted or keypad PIN entered, but none of
// the defined rules were sufficiently fulfilled to grant access.
//
// If matching rules are found, this will be triggered for every
// matching rule that could not be fulfilled. Otherwise it will only be
// triggered once with the according DoorAccessDenialReason.
type DoorAccessDeniedEvent interface {
	event.Event
	Reason() DoorAccessDenialReason // A DoorAccessDenialReason, specifying why the access was denied
	RuleId() int32                  // A matching rule that could not be fulfilled or -1 if no matching rule
	RuleName() string               // Name of the rule that could not be fulfilled or empty if no matching rule
	isDoorAccessDeniedEvent()
}

// Event: Door access rule added
type DoorAccessRuleAddedEvent interface {
	userevent.UserEvent
	RuleId() int32        // New rule id
	Rule() DoorAccessRule // Rule that was added, cardUid and pin will be filtered
	isDoorAccessRuleAddedEvent()
}

// Event: Door access rule modified
type DoorAccessRuleChangedEvent interface {
	userevent.UserEvent
	RuleId() int32           // Id of modified rule
	OldRule() DoorAccessRule // Old rule settings, cardUid and pin will be filtered
	NewRule() DoorAccessRule // New rule settings, cardUid and pin will be filtered
	isDoorAccessRuleChangedEvent()
}

// Event: Door access rule deleted
type DoorAccessRuleDeletedEvent interface {
	userevent.UserEvent
	RuleId() int32        // Id of deleted rule
	Rule() DoorAccessRule // Rule that was deleted, cardUid and pin will be filtered
	isDoorAccessRuleDeletedEvent()
}
