// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Code generated by "stringer -output=enum_strings.go -type=DoorAccessDenialReason"; DO NOT EDIT.

package dooraccesscontrol

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DENIED_NO_MATCHING_RULE-0]
	_ = x[DENIED_ABSOLUTE_TIME_CONDITION-1]
	_ = x[DENIED_PERIODIC_TIME_CONDITION-2]
	_ = x[DENIED_CONDITIONS_TIMEOUT-3]
}

const _DoorAccessDenialReason_name = "DENIED_NO_MATCHING_RULEDENIED_ABSOLUTE_TIME_CONDITIONDENIED_PERIODIC_TIME_CONDITIONDENIED_CONDITIONS_TIMEOUT"

var _DoorAccessDenialReason_index = [...]uint8{0, 23, 53, 83, 108}

func (i DoorAccessDenialReason) String() string {
	if i < 0 || i >= DoorAccessDenialReason(len(_DoorAccessDenialReason_index)-1) {
		return "DoorAccessDenialReason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DoorAccessDenialReason_name[_DoorAccessDenialReason_index[i]:_DoorAccessDenialReason_index[i+1]]
}
