// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package keypadmanager was generated by IDLC from KeypadManager.idl.
// It is part of module smartlock.
// The remaining comment is for module smartlock.
//
// Keypad Manager
package keypadmanager

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40040/event/userevent"
	"github.com/arminguenther/xeruspower-go/v40040/idl"
	"github.com/arminguenther/xeruspower-go/v40040/idl/event"
	"github.com/arminguenther/xeruspower-go/v40040/smartlock/keypad"
)

// Keypad Manager Interface
type KeypadManager interface {
	idl.Object

	// Retrieve the list of connected keypads.
	//
	//	@return Keypads list
	GetKeypads(ctx context.Context) ([]keypad.Keypad, error)

	// Get keypad for a specific id.
	//
	//	@param  keypadId     keypad id
	//
	//	@return Keypad with given id or null
	GetKeypadById(ctx context.Context, keypadId string) (keypad.Keypad, error)

	// Set settings for a keypad.
	//
	//	@param position      position of keypad (see Keypad.MetaData)
	//	@param settings      new settings for keypad
	//
	//	@return NO_ERROR                     if OK
	//	@return ERR_INVALID_PARAMS           if any setting is invalid
	SetKeypadSettings(ctx context.Context, position string, setting KeypadSettings) (int32, error)

	// Get settings for all keypads.
	//
	//	@return Map of settings by keypad position (see Keypad.MetaData)
	GetAllKeypadSettings(ctx context.Context) (map[string]KeypadSettings, error)
}

type KeypadSettings struct {
	Name        string // User-defined name
	Description string // User-defined description
}

// Keypad base event
type KeypadEvent interface {
	event.Event
	Keypad() keypad.Keypad     // Affected keypad
	MetaData() keypad.MetaData // MetaData of affected keypad
	isKeypadEvent()
}

// Keypad attached event
type KeypadAttachedEvent interface {
	KeypadEvent
	isKeypadAttachedEvent()
}

// Keypad detached event
type KeypadDetachedEvent interface {
	KeypadEvent
	isKeypadDetachedEvent()
}

type KeypadSettingsChangedEvent interface {
	userevent.UserEvent
	Keypad() keypad.Keypad       // affected keypad
	OldSettings() KeypadSettings // Settings before change
	NewSettings() KeypadSettings // Settings after change
	Position() string            // Position of the keypad (see Keypad.MetaData)
	isKeypadSettingsChangedEvent()
}
