// Code generated by "stringer -output=enum_strings.go -type=PowerLineFrequency,PixelFormat"; DO NOT EDIT.

package webcam

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NOT_SUPPORTED-0]
	_ = x[HZ50-1]
	_ = x[HZ60-2]
	_ = x[DISABLED-3]
}

const _PowerLineFrequency_name = "NOT_SUPPORTEDHZ50HZ60DISABLED"

var _PowerLineFrequency_index = [...]uint8{0, 13, 17, 21, 29}

func (i PowerLineFrequency) String() string {
	if i < 0 || i >= PowerLineFrequency(len(_PowerLineFrequency_index)-1) {
		return "PowerLineFrequency(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PowerLineFrequency_name[_PowerLineFrequency_index[i]:_PowerLineFrequency_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MJPEG-0]
	_ = x[JPEG-1]
	_ = x[RGB-2]
	_ = x[YUV-3]
}

const _PixelFormat_name = "MJPEGJPEGRGBYUV"

var _PixelFormat_index = [...]uint8{0, 5, 9, 12, 15}

func (i PixelFormat) String() string {
	if i < 0 || i >= PixelFormat(len(_PixelFormat_index)-1) {
		return "PixelFormat(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PixelFormat_name[_PixelFormat_index[i]:_PixelFormat_index[i+1]]
}
