// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package webcam was generated by IDLC from Webcam.idl.
// It is part of module webcam.
// The remaining comment is for module webcam.
//
// Webcam Management
package webcam

import (
	"context"

	"github.com/arminguenther/xeruspower-go/event/userevent"
	"github.com/arminguenther/xeruspower-go/idl"
)

// PixelFormat
type PixelFormat int

const (
	MJPEG PixelFormat = iota // Motion JPEG
	JPEG                     // JPEG
	RGB                      // RGB encoded
	YUV                      // YUV encoded
)

// PowerLineFrequency
type PowerLineFrequency int

const (
	NOT_SUPPORTED PowerLineFrequency = iota
	HZ50
	HZ60
	DISABLED
)

// Format
type Format struct {
	Width       int32       // image width
	Height      int32       // image height
	PixelFormat PixelFormat // pixel format
}

// Controls
//
// All int values are normed to a range of 1 to 1000
// 0 means "auto" if available, -1 means not supported by the webcam
type Controls struct {
	Brightness         int32              // brightness
	Contrast           int32              // contrast
	Saturation         int32              // saturation
	Gain               int32              // gain
	Gamma              int32              // gamma
	PowerLineFrequency PowerLineFrequency // power line frequency (50Hz, 60Hz or disabled)
}

// Location
type Location struct {
	Name string // location name
	X    string // x
	Y    string // y
	Z    string // z
}

// Image meta data
type ImageMetaData struct {
	Format    Format   // image format information
	Timestamp int64    // image timestamp
	Location  Location // source webcam location
}

// Image
type Image struct {
	Meta ImageMetaData // image meta data
	Data string        // base64 encoded image data
}

// Webcam settings
type Settings struct {
	Format          Format   // currently selected image format
	Controls        Controls // image settings like brightness, contrast, gain, ...
	Name            string   // webcam name
	Location        Location // webcam location
	RefreshInterval int32    // in ms, toggle "video" and "static image" mode
}

// Webcam information
type Information struct {
	Id               string   // port and camera specific ID string
	Model            string   // camera model
	SupportedFormats []Format // supported image formats
}

// Error codes
const (
	NO_ERROR          int32 = 0 // Operation successful, no error
	ERR_INVALID_PARAM int32 = 1 // Invalid parameter for an operation
)

// The webcam interface
type Webcam interface {
	idl.Object

	// Retrieve information of a specific webcam.
	//
	//	@return Information
	GetInformation(ctx context.Context) (Information, error)

	// Retrieve settings of a specific webcam.
	//
	//	@return Settings
	GetSettings(ctx context.Context) (Settings, error)

	// Change settings of a specific webcam.
	//
	//	@param settings  New webcam settings
	//
	//	@return 0 if success
	//	@return 1 if any parameter is invalid
	SetSettings(ctx context.Context, settings Settings) (int32, error)

	// Apply webcam control settings without storing them
	//
	//	@param controls  Control settings
	//
	//	@return 0 if success
	//	@return 1 if any parameter is invalid
	SetControls(ctx context.Context, controls Controls) (int32, error)

	// Retrieve the default value of the controls.
	//
	//	@return Controls
	GetControlDefaults(ctx context.Context) (Controls, error)
}

// This event is emitted after the settings of a webcam were changed
type SettingsChangedEvent interface {
	userevent.UserEvent
	OldSettings() Settings // the old settings
	NewSettings() Settings // the new settings
	isSettingsChangedEvent()
}
