// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package memorymapcontroller was generated by IDLC from MemoryMapController.idl.
// It is part of module pdumodel.
// The remaining comment is for module pdumodel.
//
// PDU Model
package memorymapcontroller

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40410/pdumodel/controller"
)

// Memory map controller
type MemoryMapController interface {
	controller.Controller

	// Read a given number of bytes from an address
	//
	//	@param address  The address to read
	//	@param size  The number of bytes to read
	//	@param memory  The vector with the read bytes
	//
	//	@return 0 if OK
	//	@return an error code otherwise
	ReadMemory(ctx context.Context, address int32, size int32) (ret int32, memory []byte, err error)

	// Write bytes to an address
	//
	//	@param address  The address to write
	//	@param memory   The vector with the bytes to write
	//
	//	@return 0 if OK
	//	@return an error code otherwise
	WriteMemory(ctx context.Context, address int32, memory []byte) (int32, error)
}
