// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package keypad was generated by IDLC from Keypad.idl.
// It is part of module smartlock.
// The remaining comment is for module smartlock.
//
// Keypad
package keypad

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40100/idl"
	"github.com/arminguenther/xeruspower-go/v40100/idl/event"
)

// Error codes
const (
	NO_ERROR       int32 = 0 // operation successful, no error
	ERR_SLOT_EMPTY int32 = 1 // no PIN present in keypad
)

// Keypad Interface
type Keypad interface {
	idl.Object

	// Retrieve keypad metadata.
	//
	//	@return metadata
	GetMetaData(ctx context.Context) (MetaData, error)

	// Retrieve last entered PIN from keypad. PINs are cleared after 10
	// seconds or subsituted whenever a new PIN was entered.
	//
	//	@param pin    PIN
	//
	//	@return NO_ERROR                     if OK
	//	@return ERR_SLOT_EMPTY               if keypad sees no PIN
	GetPIN(ctx context.Context) (ret int32, pin string, err error)
}

// Keypad Metadata
type MetaData struct {
	Id           string // Keypad ID used in events and traps
	Manufacturer string // manufacturer
	Product      string // product
	SerialNumber string // serial number (S/N)
	Channel      int32  // one device (S/N) can provide multiple keypads
	// Position of the keypad.
	// A string, representing the position in the 1-wire topology
	// and the channel of the keypad (e.g. D1:H1:C1-1)
	Position string
}

// PIN entered event
//
// A PIN was entered on this Keypad, retrieve it by using getPIN().
type PINEnteredEvent interface {
	event.Event
	MetaData() MetaData // MetaData of this keypad
	isPINEnteredEvent()
}
