// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package cardreadermanager was generated by IDLC from CardReaderManager.idl.
// It is part of module smartcard.
// The remaining comment is for module smartcard.
//
// Card Reader Manager
package cardreadermanager

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40412/event/userevent"
	"github.com/arminguenther/xeruspower-go/v40412/idl"
	"github.com/arminguenther/xeruspower-go/v40412/idl/event"
	"github.com/arminguenther/xeruspower-go/v40412/smartcard/cardreader"
)

// Card Reader Manager Interface
type CardReaderManager interface {
	idl.Object

	// Retrieve the list of connected card readers.
	//
	//	@return Card Readers list
	GetCardReaders(ctx context.Context) ([]cardreader.CardReader, error)

	// Get card reader for a specific id.
	//
	//	@param  readerId     card reader id
	//
	//	@return Card Reader with given id or null
	GetCardReaderById(ctx context.Context, readerId string) (cardreader.CardReader, error)

	// Set settings for a card reader.
	//
	//	@param position      position of card reader (see CardReader.MetaData)
	//	@param setting       new settings for card reader
	//
	//	@return NO_ERROR                     if OK
	//	@return ERR_INVALID_PARAMS           if any setting is invalid
	//
	//	@note The CardReaderSettings structure can be "sparse"; fields missing
	//	      in the JSON representation will remain unchanged.
	SetCardReaderSettings(ctx context.Context, position string, setting CardReaderSettings) (int32, error)

	// Get settings for all card readers.
	//
	//	@return Map of settings by card reader position (see CardReader.MetaData)
	GetAllCardReaderSettings(ctx context.Context) (map[string]CardReaderSettings, error)

	// Retrieve the list of supported card formats like "RAW", "H10301", etc.
	//
	//	@return Card Formats list
	GetSupportedCardFormats(ctx context.Context) ([]string, error)
}

// Card Reader Settings
type CardReaderSettings struct {
	Name        string // User-defined name
	Description string // User-defined description
	// Card format, must be one of the values returned by
	// getSupportedCardFormats(); use "RAW" for plain
	// hexadecimal representation.
	CardFormat string
}

// Card Reader base event
type CardReaderEvent interface {
	event.Event
	CardReader() cardreader.CardReader // Affected card reader
	MetaData() cardreader.MetaData     // Metadata of affected card reader
	isCardReaderEvent()
}

// Card Reader attached event
type CardReaderAttachedEvent interface {
	CardReaderEvent
	isCardReaderAttachedEvent()
}

// Card Reader detached event
type CardReaderDetachedEvent interface {
	CardReaderEvent
	isCardReaderDetachedEvent()
}

type CardReaderSettingsChangedEvent interface {
	userevent.UserEvent
	CardReader() cardreader.CardReader // affected card reader
	OldSettings() CardReaderSettings   // Settings before change
	NewSettings() CardReaderSettings   // Settings after change
	Position() string                  // Position of the card reader (see CardReader.MetaData)
	isCardReaderSettingsChangedEvent()
}
