// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package zeroconf was generated by IDLC from Zeroconf.idl.
// It is part of module devsettings.
// The remaining comment is for module devsettings.
//
// Device Settings
package zeroconf

import (
	"context"

	"github.com/arminguenther/xeruspower-go/idl"
	"github.com/arminguenther/xeruspower-go/idl/event"
)

// Zero-config service settings interface
type Zeroconf interface {
	idl.Object

	// Retrieve the service settings.
	//
	//	@return Zero-config service settings
	GetSettings(ctx context.Context) (Settings, error)

	// Set the service settings.
	//
	//	@param settings New settings
	SetSettings(ctx context.Context, settings Settings) error
}

// Zero-configservice settings
type Settings struct {
	MdnsEnabled  bool // Enable zero-config advertising via mDNS for device
	LlmnrEnabled bool // Enable zero-config advertising via LLMNR for device
}

type SettingsChangedEvent interface {
	event.Event
	OldSettings() Settings // old settings
	NewSettings() Settings // new settings
	isSettingsChangedEvent()
}
