// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package testdisplay was generated by IDLC from TestDisplay.idl.
// It is part of module test.
// The remaining comment is for module test.
//
// Test Interfaces
package testdisplay

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40010/idl"
)

// Type-independent display test interface
type Display interface {
	idl.Object

	// Retrieve display's meta information.
	//
	//	@return Display information
	GetInfo(ctx context.Context) (DisplayInfo, error)

	// Execute a test sequence that is a bit more elaborate than
	// just on and off all.
	//
	//	@param cycleTime_ms  Delay between state changes in ms
	TestSequence(ctx context.Context, cycleTime_ms int32) error

	// Start an interactive test on units which support it.
	//
	//	@param showColorNames  Show names along with each tested color
	EnterTestMode(ctx context.Context, showColorNames bool) error

	// Get the current status of the interactive test.
	//
	//	@return Test status
	GetTestStatus(ctx context.Context) (DisplayTestStatus, error)
}

// Display orientation
type DisplayOrientation int

const (
	NORMAL  DisplayOrientation = iota // Normal orientation
	FLIPPED                           // Upside-down
	LEFT                              // Left side down
	RIGHT                             // Right side down
)

// Collected display meta information
type DisplayInfo struct {
	Type        string             // Display type
	Address     string             // Display address
	Options     map[string]string  // Display options
	Orientation DisplayOrientation // Display orientation
}

// Status of interactive test
type DisplayTestStatus int

const (
	TEST_IDLE   DisplayTestStatus = iota // Test has not been started
	TEST_BUSY                            // Test is in progress
	TEST_PASSED                          // The test finished successfully
	TEST_FAILED                          // The test failed
)
