// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package userevent was generated by IDLC from UserEvent.idl.
// It is part of module event.
// The remaining comment is for module event.
//
// Event interface
package userevent

import "github.com/arminguenther/xeruspower-go/idl/event"

// This UserEvent may be used as base valueobject for
// all concrete events that are triggered because of
// user interaction.
type UserEvent interface {
	event.Event
	ActUserName() string // user who triggered event
	ActIpAddr() string   // ip or device on which user is logged in
	isUserEvent()
}
