// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package scannerctrl was generated by IDLC from ScannerCtrl.idl.
// It is part of module tfw.
// The remaining comment is for module tfw.
//
// Topology Framework Base
package scannerctrl

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40410/idl"
)

// Scanner control interface
type ScannerCtrl interface {
	idl.Object

	// Retrieve the current scan interval.
	//
	//	@return Scan interval in milliseconds
	GetScanInterval(ctx context.Context) (int32, error)

	// Change the scan interval.
	//
	//	@param interval  New scan interval in milliseconds
	SetScanInterval(ctx context.Context, interval int32) error
}
