// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package assetstrip was generated by IDLC from AssetStrip.idl.
// It is part of module assetmgrmodel.
// The remaining comment is for module assetmgrmodel.
//
// Asset Management Model
package assetstrip

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40000/assetmgrmodel/assetstripconfig"
	"github.com/arminguenther/xeruspower-go/v40000/event/userevent"
	"github.com/arminguenther/xeruspower-go/v40000/idl"
	"github.com/arminguenther/xeruspower-go/v40000/idl/event"
)

// Error codes
const (
	NO_ERROR             int32 = 0 // Operation successful, no error
	ERR_INVALID_PARAM    int32 = 1 // Invalid parameter for an operation
	ERR_NO_SUCH_OBJECT   int32 = 2 // Requested object does not exist
	ERR_NOT_SUPPORTED    int32 = 3 // Requested operation is not supported
	ERR_OPERATION_FAILED int32 = 4 // Operation did not succeed
)

// Constants
const MAIN_STRIP_COLUMN int32 = 0

// Asset Management Strip interface
type AssetStrip interface {
	idl.Object

	// Get the current state of the AssetStrip
	//
	//	@return State of the Asset Strip
	GetState(ctx context.Context) (State, error)

	// Get static (hardware and firmware) information
	//
	//	@return                      Result: hardware and firmware information
	GetDeviceInfo(ctx context.Context) (DeviceInfo, error)

	// Get dynamic (number of tags) information
	//
	//	@return                      Result: tag related information
	GetStripInfo(ctx context.Context) (StripInfo, error)

	// Get info with all settings of a rack unit at once
	//
	//	@param  rackUnitNumber       rack unit to get the info for, range 0..rackUnitCount-1
	//	@param  info                 Result: info for this rack unit
	//	@return NO_ERROR             on success
	//	@return ERR_INVALID_PARAM    rack unit count exceeded
	GetRackUnitInfo(ctx context.Context, rackUnitNumber int32) (ret int32, info RackUnitInfo, err error)

	// Get infos with settings for all rack units
	//
	//	@return                      Result: the rack unit infos with settings
	GetAllRackUnitInfos(ctx context.Context) ([]RackUnitInfo, error)

	// Get the asset tag for a rack unit
	//
	//	@param  rackUnitNumber       rack unit to read the asset tag for, range 0..rackUnitCount-1
	//	@param  slotNumber           slot to read the asset tag for, 0 for the main strip, >0 for blades
	//	@param  tagInfo              Result: asset tag information
	//	@return NO_ERROR             on success
	//	@return ERR_INVALID_PARAM    rack unit count exceeded or colum not existing
	//	@return ERR_NO_SUCH_OBJECT   no tag connected to this rack unit
	GetTag(ctx context.Context, rackUnitNumber int32, slotNumber int32) (ret int32, tagInfo TagInfo, err error)

	// Get all asset tags of the strip
	//
	// Please note that in case there is not a single tag connected to the
	// strip the resulting list will be empty, only connected tag info
	// structures are returned
	// It is guaranteed that extensions on the main strip are returned
	// before any tag on an extension itself.
	//
	//	@return                      Result: list asset tag infos
	GetAllTags(ctx context.Context) ([]TagInfo, error)

	// Get all asset tags on the main strip
	//
	// Same as getAllTags, but only consider tags connected to the main
	// asset strip and not on any connected extension.
	// Extensions on the main strip themselves are returned.
	//
	//	@return                      Result: list asset tag infos
	GetMainTags(ctx context.Context) ([]TagInfo, error)

	// Get all asset tags on an extension
	//
	// Gets all tags on a single extension for a certain rack unit.
	// List will be empty if there are no tags connected
	//
	//	@param  rackUnitNumber       rack unit to get the extension tags for, range 0..rackUnitCount-1
	//	@param  tags                 Result: list asset tag infos
	//	@return NO_ERROR             on success
	//	@return ERR_INVALID_PARAM    rack unit count exceeded or rack unit
	//	                             does not contain an extension
	GetExtensionTags(ctx context.Context, rackUnitNumber int32) (ret int32, tags []TagInfo, err error)

	// Trigger a powercycle of either the whole asset strip port or the
	// LED part power supply on the asset strip
	//
	//	@param  hard                 true=whole port, false=LEDs only
	TriggerPowercycle(ctx context.Context, hard bool) error

	// Program custom tag IDs
	//
	// Asset tags of type AMT-P may be programmed by user (custom ID). This method
	// takes a list of (rack unit, slot number, id) tuples that determine
	// which connected tag should be programmed with which ID.
	// TagInfo::rawId specifies the ID. An empty string erases the current
	// custom ID which brings back the original 1-wire ID.
	// Set TagInfo::slotNumber to 0 for tags on main strip and > 0 for blades.
	// TagInfo::familyDesc and TagInfo::programmable are ignored.
	//
	//	@param tagInfos               vector of tag information that will be programmed
	//	@return NO_ERROR              on success
	//	@return ERR_INVALID_PARAM     rack unit out of bounds or custom ID too long
	//	@return ERR_NO_SUCH_OBJECT    rack unit does not exist or has no tag
	//	@return ERR_NOT_SUPPORTED     tag is not programmable
	//	@return ERR_OPERATION_FAILED  programming failed
	ProgramTagIDs(ctx context.Context, tagInfos []TagInfo) (int32, error)

	// Retrieve state of firmware update on main strip
	//
	//	@return asset strip firmware update state
	GetFirmwareUpdateState(ctx context.Context) (FirmwareUpdateState, error)
}

// AssetStrip state
type State int

const (
	DISCONNECTED    State = iota // No strip connected
	FIRMWARE_UPDATE              // Firmware update in progress on main strip
	UNSUPPORTED                  // Connected asset strip is unsupported
	AVAILABLE                    // Asset strip is up and running normally
)

// Type of the connected asset strip
type StripType int

const (
	SIMPLE    StripType = iota // single, monolitic strip
	COMPOSITE                  // strip consisting of multiple cascaded strips
)

// Type of an asset tag connected to a rack unit
type TagType int

const (
	SINGLE    TagType = iota // single asset tag connected to main strip or an extension
	EXTENSION                // blade server extension, only possible on the main strip
	NONE                     // no asset tag connected to main strip or an extension
)

// For composite asset strips CascadeState shows additional information
// about the state of the complete cascade
type CascadeState int

const (
	CASCADE_ACTIVE          CascadeState = iota // cascade is up and running
	CASCADE_FIRMWARE_UPDATE                     // a device in the cascade receives a firmware update
)

// Static (type, version) information for an AssetStrip.
type DeviceInfo struct {
	DeviceId                  int32 // Device type (indicated a certain hardware)
	HardwareId                int32 // Hardware ID, revision
	ProtocolVersion           int32 // Protocol version the strip is supporting
	BootVersion               int32 // Bootcode software version
	AppVersion                int32 // Application code software version
	OrientationSensAvailable  bool  // Indicates whether the strip has an orientation sensor
	IsCascadable              bool  // The asset strip type
	RackUnitCountConfigurable bool  // Rack unit count has to be configured, i.e. is not auto detected
}

// Dynamic (may change with a connected strip) information for an AssetStrip.
type StripInfo struct {
	MaxMainTagCount  int32        // Maximum number of tags supported on the main strip
	MaxBladeTagCount int32        // Maximum number of tags supported on blade extensions
	MainTagCount     int32        // Current number of tags on the main asset strip
	BladeTagCount    int32        // Current number of tags on all blade extensions
	BladeOverflow    bool         // Out of space for new blade extension tags, read-only
	RackUnitCount    int32        // Rack unit count, i.e. number of tags connectable
	ComponentCount   int32        // Number of components
	CascadeState     CascadeState // State of the cascade (only for composite strips)
}

// Information for a single tag
type TagInfo struct {
	RackUnitNumber int32  // The rack unit this tag is connected to, range 0..rackUnitCount-1
	SlotNumber     int32  // Blade slot this tag is connected to, 0 is the main strip, >0 for blades
	FamilyDesc     string // Tag family description, indicating different tag hardware
	RawId          string // The asset tag ID (6 byte hexadecimal string 'AABBCCDDEEFF')
	Programmable   bool   // Is the asset tag ID programmable?
}

// Infos for a single rack unit
//
// In case no asset strip is connected, type defaults to single and size defaults to 1
type RackUnitInfo struct {
	RackUnitNumber              int32                             // rack unit for the settings, range 0..rackUnitCount-1
	RackUnitPosition            int32                             // resulting rack unit position (display number)
	Type                        TagType                           // type of the asset tag (single, extension, none or unknown)
	Size                        int32                             // blade extension size (4,8,16), 1 for single tags or 0 if nothing connected
	Settings                    assetstripconfig.RackUnitSettings // settings for a single rack unit
	AssetStripCascadePosition   int32                             // number of strip in cascade
	RackUnitRelativePosition    int32                             // relative position to strip
	AssetStripNumberOfRackUnits int32                             // number of rack units in strip that this rack unit belongs to
}

// Event: Asset strip dynamic information has changed
type StripInfoChangedEvent interface {
	event.Event
	OldInfo() StripInfo // Information before change
	NewInfo() StripInfo // Information after change
	isStripInfoChangedEvent()
}

// Event: Asset strip state has changed
type StateChangedEvent interface {
	event.Event
	OldState() State // State before change
	NewState() State // State after change
	// Information about connected strip, only valid
	// if newState is AVAILABLE
	DeviceInfo() DeviceInfo
	isStateChangedEvent()
}

// Event: A rack unit has changed
type RackUnitChangedEvent interface {
	userevent.UserEvent
	RackUnitNumber() int32  // Affected rack unit position
	RackUnit() RackUnitInfo // New rack unit information
	isRackUnitChangedEvent()
}

// Information describing a tag change
type TagChangeInfo struct {
	Tag  TagInfo      // Tag which was attached or detached
	Info RackUnitInfo // Rack unit the tag was/is connected to
	// Asset tag ID of the parent blade tag,
	// empty if the tag is not an extension tag
	ParentBladeTagId string
	// Blade slot position of the tag,
	// 0 if the tag is not an extension tag
	SlotPosition int32
}

// Event: A tag was added or removed
type TagEvent interface {
	event.Event
	Tags() []TagChangeInfo // Affected tags
	AllTags() []TagInfo    // New list of detected tags after change
	isTagEvent()
}

// Event: A tag was added
type TagAddedEvent interface {
	TagEvent
	isTagAddedEvent()
}

// Event: A tag was removed
type TagRemovedEvent interface {
	TagEvent
	isTagRemovedEvent()
}

// Enumeration: State of firmware update
type FirmwareUpdateState int

const (
	UPDATE_STARTED    FirmwareUpdateState = iota // Update is running
	UPDATE_SUCCESSFUL                            // Update was completed successfully
	UPDATE_FAILED                                // Update has failed
)

// Event: Firmware update on main strip was started or has finished
type FirmwareUpdateStateChangedEvent interface {
	event.Event
	State() FirmwareUpdateState // Update state
	isFirmwareUpdateStateChangedEvent()
}

// Event: Tag overflow
type BladeOverflowChangedEvent interface {
	event.Event
	// Whether the strip is out of space
	// for new blade extension tags
	Overflow() bool
	isBladeOverflowChangedEvent()
}

// Event: Detected strip orientation has changed
type OrientationChangedEvent interface {
	event.Event
	OldOrientation() assetstripconfig.Orientation // Strip orientation before change
	NewOrientation() assetstripconfig.Orientation // Strip orientation after change
	isOrientationChangedEvent()
}

// Event: Strip composition has changed
type CompositionChangedEvent interface {
	event.Event
	OldComponentCount() int32 // Component count before change
	NewComponentCount() int32 // Component count after change
	isCompositionChangedEvent()
}
