// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Code generated by "stringer -output=enum_strings.go -type=TagType,CascadeState,State,FirmwareUpdateState,StripType"; DO NOT EDIT.

package assetstrip

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SINGLE-0]
	_ = x[EXTENSION-1]
	_ = x[NONE-2]
}

const _TagType_name = "SINGLEEXTENSIONNONE"

var _TagType_index = [...]uint8{0, 6, 15, 19}

func (i TagType) String() string {
	if i < 0 || i >= TagType(len(_TagType_index)-1) {
		return "TagType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TagType_name[_TagType_index[i]:_TagType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CASCADE_ACTIVE-0]
	_ = x[CASCADE_FIRMWARE_UPDATE-1]
}

const _CascadeState_name = "CASCADE_ACTIVECASCADE_FIRMWARE_UPDATE"

var _CascadeState_index = [...]uint8{0, 14, 37}

func (i CascadeState) String() string {
	if i < 0 || i >= CascadeState(len(_CascadeState_index)-1) {
		return "CascadeState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CascadeState_name[_CascadeState_index[i]:_CascadeState_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DISCONNECTED-0]
	_ = x[FIRMWARE_UPDATE-1]
	_ = x[UNSUPPORTED-2]
	_ = x[AVAILABLE-3]
}

const _State_name = "DISCONNECTEDFIRMWARE_UPDATEUNSUPPORTEDAVAILABLE"

var _State_index = [...]uint8{0, 12, 27, 38, 47}

func (i State) String() string {
	if i < 0 || i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UPDATE_STARTED-0]
	_ = x[UPDATE_SUCCESSFUL-1]
	_ = x[UPDATE_FAILED-2]
}

const _FirmwareUpdateState_name = "UPDATE_STARTEDUPDATE_SUCCESSFULUPDATE_FAILED"

var _FirmwareUpdateState_index = [...]uint8{0, 14, 31, 44}

func (i FirmwareUpdateState) String() string {
	if i < 0 || i >= FirmwareUpdateState(len(_FirmwareUpdateState_index)-1) {
		return "FirmwareUpdateState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FirmwareUpdateState_name[_FirmwareUpdateState_index[i]:_FirmwareUpdateState_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SIMPLE-0]
	_ = x[COMPOSITE-1]
}

const _StripType_name = "SIMPLECOMPOSITE"

var _StripType_index = [...]uint8{0, 6, 15}

func (i StripType) String() string {
	if i < 0 || i >= StripType(len(_StripType_index)-1) {
		return "StripType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StripType_name[_StripType_index[i]:_StripType_index[i+1]]
}
