// Copyright 2026 Raritan Inc. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause

// Package waveform was generated by IDLC from Waveform.idl.
// It is part of module pdumodel.
// The remaining comment is for module pdumodel.
//
// PDU Model
package waveform

// Waveform data, including metadata
type Waveform struct {
	Voltage    []float64 // Voltage waveform samples, each (1/sampleRate) seconds apart
	Current    []float64 // Current waveform samples, each (1/sampleRate) seconds apart
	SampleRate int32     // Number of samples per second
}
