// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package overcurrentprotectortripsensor was generated by IDLC from OverCurrentProtectorTripSensor.idl.
// It is part of module pdumodel.
// The remaining comment is for module pdumodel.
//
// PDU Model
package overcurrentprotectortripsensor

import (
	"context"
	"time"

	"github.com/arminguenther/xeruspower-go/pdumodel/outlet"
	"github.com/arminguenther/xeruspower-go/pdumodel/waveform"
	"github.com/arminguenther/xeruspower-go/sensors/statesensor"
)

// Overcurrent protector trip sensor interface
type OverCurrentProtectorTripSensor interface {
	statesensor.StateSensor

	// Deprecated:
	// Get the outlet that is most likely to have caused the last OCP trip.
	//
	//	@return The outlet that most likely caused the OCP to trip. If either
	//	        the OCP is not currently tripped or no outlet can be determined
	//	        to have caused the trip, null is returned.
	//
	// This method is deprecated, use {@link getTripEventInformation} instead.
	GetTripCause(ctx context.Context) (outlet.Outlet, error)

	// Get information about the last trip event.
	//
	//	@return Trip event information, or an empty structure if the OCP currently isn't tripped.
	GetTripEventInformation(ctx context.Context) (TripEventInformation, error)

	// Get the voltage and current waveform during the last OCP trip event.
	//
	//	@return The waveform during OCP trip in case both
	//	        - A potential trip cause outlet could be determined and
	//	        - The device supports waveform reading
	//	        If either condition is not met, an empty waveform is returned.
	GetTripWaveform(ctx context.Context) (waveform.Waveform, error)
}

type TripEventInformation struct {
	Cause     outlet.Outlet // Outlet that is most likely to have caused the OCP to trip.
	Timestamp time.Time     // Timestamp of trip event
	// Current flow in outlet causing the event at trip time.
	// If current flow can not be determined, this value is sent as 0.
	Current float64
}

// Event: Overcurrent protector trip state has changed
type TripStateChangedEvent interface {
	statesensor.StateChangedEvent
	// Outlet that is most likely to have caused the OCP to trip.
	// Deprecated, use the tripInformation field instead.
	TripCause() outlet.Outlet
	TripInformation() TripEventInformation // Information about the event that caused a trip event.
	isTripStateChangedEvent()
}
