// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package diagnostics was generated by IDLC from Diagnostics.idl.
// It is part of module net.
// The remaining comment is for module net.
//
// Network Configuration
package diagnostics

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40010/idl"
)

const (
	NO_ERROR          int32 = 0 // No error
	ERR_INVALID_PARAM int32 = 1 // Invalid parameters
	ERR_EXEC_FAIL     int32 = 2 // Error during execution
	ERR_TIMEOUT       int32 = 3 // Timeout
	ERR_RESOLVE_FAIL  int32 = 4 // Name resolution failure
)

// Diagnostics interface
type Diagnostics interface {
	idl.Object

	// Ping a network host (send out ICMP echo requests)
	//
	//	@param hostName      host that should be pinged
	//	@param count         number of echo requests that should be sent (up to 20)
	//	@param results       output of the ping command
	//
	//	@return NO_ERROR             if ping command was successful
	//	@return ERR_INVALID_PARAM    if any parameters were invalid
	//	@return ERR_EXEC_FAIL        if there was an error during ping execution
	//	@return ERR_RESOLVE_FAIL     if the host name could not be resolved
	Ping(ctx context.Context, hostName string, count int32) (ret int32, results []string, err error)

	// Get the route packet trace to a network host
	//
	//	@param hostName      destination host to track
	//	@param timeout       Timeout (in seconds) to wait for traceroute results (up to 900)
	//	@param useIcmp       use ICMP packets instead of UDP packets
	//	@param results       trace output
	//
	//	@return NO_ERROR             if traceroute was successful
	//	@return ERR_INVALID_PARAM    if any parameters were invalid
	//	@return ERR_EXEC_FAIL        if there was an error during traceroute execution
	//	@return ERR_TIMEOUT          if traceroute didn't finish before timeout elapsed
	//	@return ERR_RESOLVE_FAIL     if the host name could not be resolved
	TraceRoute(ctx context.Context, hostName string, timeout int32, useIcmp bool) (ret int32, results []string, err error)

	// List the currently active TCP connections
	//
	//	@return NO_ERROR             if successful
	//	@return ERR_EXEC_FAIL        if an error occured during execution of the socket statistic utility
	ListTcpConnections(ctx context.Context) (ret int32, results []string, err error)

	// List TCP/UDP listen (server) sockets
	//
	//	@return NO_ERROR             if successful
	//	@return ERR_EXEC_FAIL        if an error occured during execution of the socket statistic utility
	ListTcpUdpListenSockets(ctx context.Context) (ret int32, results []string, err error)

	// Test whether resolving a host name works and provide diagnostic information.
	//
	//	@param hostName              host name to resolve
	//	@param results               result (includes meta data and the actual result or error message)
	ResolveHostName(ctx context.Context, hostName string) (results []string, err error)
}
