// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package servermonitor was generated by IDLC from ServerMonitor.idl.
// It is part of module servermon.
// The remaining comment is for module servermon.
//
// Server Monitor
package servermonitor

import (
	"context"
	"time"

	"github.com/arminguenther/xeruspower-go/v40412/event/userevent"
	"github.com/arminguenther/xeruspower-go/v40412/idl"
	"github.com/arminguenther/xeruspower-go/v40412/idl/event"
)

const (
	ERR_NO_SUCH_ID          int32 = 1 // No such ID
	ERR_INVALID_SETTINGS    int32 = 2 // Invalid settings
	ERR_DUPLICATE_HOSTNAME  int32 = 3 // Duplicate hostname
	ERR_MAX_SERVERS_REACHED int32 = 4 // Maximum number of server entries
)

// Server Monitor Interface
type ServerMonitor interface {
	idl.Object

	// Add a new server entry.
	//
	//	@param id        New entry id, automatically assigned
	//	@param settings  New server settings
	//
	//	@return 0 if OK
	//	@return 2 if the settings are invalid
	//	@return 3 if an entry for the given hostname exists
	//	@return 4 if the maximum number of servers is reached
	//
	//	@note The ServerSettings structure can be "sparse"; fields missing in
	//	      the JSON representation will be set to default values.
	AddServer(ctx context.Context, settings ServerSettings) (ret int32, id int32, err error)

	// Modify an existing server entry.
	//
	//	@param id        Entry id
	//	@param settings  New settings
	//
	//	@return 0 if OK
	//	@return 1 if the entry does not exist
	//	@return 2 if the settings are invalid
	//	@return 3 if an entry for the given hostname exists
	//
	//	@note The ServerSettings structure can be "sparse"; fields missing in
	//	      the JSON representation will remain unchanged.
	ModifyServer(ctx context.Context, id int32, settings ServerSettings) (int32, error)

	// Delete a server entry.
	//
	//	@param id        Entry id
	//
	//	@return 0 if OK
	//	@return 1 if the entry does not exist
	DeleteServer(ctx context.Context, id int32) (int32, error)

	// Retrieve a server entry (settings and status).
	//
	//	@param server    Server settings and status
	//	@param id        Entry id
	//
	//	@return 0 if OK
	//	@return 1 if the entry does not exist
	GetServer(ctx context.Context, id int32) (ret int32, server Server, err error)

	// Retrieve a list of server entries (settings and status).
	//
	//	@return Server list
	ListServers(ctx context.Context) (map[int32]Server, error)

	// Control the power state of the outlets the server uses.
	// Attempting to switch the power off will issue a graceful shutdown of
	// the server beforehand.
	//
	//	@param id       Entry id
	//	@param on       Switch power on if true, off if false
	//
	//	@return 0 if OK
	//	@return 1 if the entry does not exist
	//	@return 2 if the settings are invalid
	PowerControl(ctx context.Context, id int32, on bool) (int32, error)
}

// Server Reachability State
type ServerReachability int

const (
	WAITING     ServerReachability = iota // Waiting for reliable connection
	REACHABLE                             // Server is up and running
	UNREACHABLE                           // No response from server
	ERROR                                 // Error pinging server (e.g. DNS lookup failure)
)

// Server Power Control State
type ServerPowerState int

const (
	UNKNOWN       ServerPowerState = iota // Power state currently not known
	ON                                    // Server power target is on
	OFF                                   // Server power target is off
	SHUTTING_DOWN                         // Server is being manually shut down
)

// Server Power Control Result
type ServerPowerControlResult int

const (
	NO_ERROR             ServerPowerControlResult = iota // No error, operation may still be in progress
	SHUTDOWN_CMD_FAILED                                  // Error issuing the shutdown command to the server
	SWITCHING_OFF_FAILED                                 // Switching the outlet or outlet group off failed
	SWITCHING_ON_FAILED                                  // Switching the outlet or outlet group on failed
	POWER_CHECK_TIMEOUT                                  // Checking if power is off timed out
)

// Methods of checking power state
type ServerPowerCheckMethod int

const (
	TIMER      ServerPowerCheckMethod = iota // Server is assumed to be off after a time interval
	POWER_DROP                               // Server is off if power consumption dropped
)

// Settings for controlling and checking power state of the server
type ServerPowerSettings struct {
	Enabled        bool                   // Power control for this server enabled
	Target         idl.Object             // Target for power control, Outlet or OutletGroup
	PowerCheck     ServerPowerCheckMethod // Method to check server's power state
	PowerThreshold float64                // Active power below this threshold means server is off (in Watt)
	Timeout        int32                  // Seconds the power check takes before it ends / times out
	ShutdownCmd    string                 // Shutdown command to send to the server
	Username       string                 // Login used to issue shutdown command to the server
	Password       string                 // Password for the login, write-only, not set if empty
	SshPort        int32                  // SSH port of the server
}

// Server Reachability Settings
type ServerSettings struct {
	Host            string              // Server hostname/IP address
	Enabled         bool                // Pinging enabled
	PingInterval    int32               // Wait time after successful ping
	RetryInterval   int32               // Wait time after unsuccessful ping
	ActivationCount int32               // Minimum number of successful pings to enable feature
	FailureCount    int32               // Number of unsuccessful pings to consider server down
	ResumeDelay     int32               // Wait time before resuming pinging
	ResumeCount     int32               // Number of resumes before going back to WAITING state
	PowerSettings   ServerPowerSettings // Settings for controlling the power state of the server
}

// Server Reachability Status
type ServerStatus struct {
	PowerState             ServerPowerState         // Power control state
	LastPowerControlResult ServerPowerControlResult // Last result of a power control operation
	Reachable              ServerReachability       // Reachability state
	LastRequest            time.Time                // UNIX timestamp (UTC) of last request sent
	LastResponse           time.Time                // UNIX timestamp (UTC) of last response received
	Requests               int32                    // Number of requests sent
	Responses              int32                    // Number of responses received
	Failures               int32                    // Number of consecutive failed pings
	Resumes                int32                    // Number of resumes
}

// Event: ServerPowerState has changed
type ServerPowerStateEvent interface {
	event.Event
	Id() int32                       // id of the server entry
	Host() string                    // Server hostname/IP address
	OldPowerState() ServerPowerState // Old power state
	NewPowerState() ServerPowerState // New power state
	isServerPowerStateEvent()
}

// Event: A power control operation was initiated
type ServerPowerControlInitiatedEvent interface {
	userevent.UserEvent
	Id() int32    // id of the server
	Host() string // Server hostname/IP address
	On() bool     // True if server shall be switched on, false otherwise
	isServerPowerControlInitiatedEvent()
}

// Event: A power control operation was completed
type ServerPowerControlCompletedEvent interface {
	event.Event
	Id() int32                        // id of the server
	Host() string                     // Server hostname/IP address
	Result() ServerPowerControlResult // Result of the power control operation
	isServerPowerControlCompletedEvent()
}

// Event: Reachability status for a monitored server has changed or
// server continues to be unreachable
type ServerReachabilityEvent interface {
	event.Event
	Id() int32                     // id of the server entry
	Host() string                  // Server hostname/IP address
	Reachable() ServerReachability // Current Reachability state
	isServerReachabilityEvent()
}

// A new server entry was added
type ServerAddedEvent interface {
	userevent.UserEvent
	Id() int32                // id of the added server entry
	Settings() ServerSettings // Settings of the added server
	isServerAddedEvent()
}

// A server entry was changed
type ServerSettingsChangedEvent interface {
	userevent.UserEvent
	Id() int32                   // id of the server entry
	OldSettings() ServerSettings // Settings before change
	NewSettings() ServerSettings // Settings after change
	isServerSettingsChangedEvent()
}

// A server entry was deleted
type ServerDeletedEvent interface {
	userevent.UserEvent
	Id() int32 // id of the deleted server entry
	isServerDeletedEvent()
}

// Server Entry
type Server struct {
	Settings ServerSettings // Server settings
	Status   ServerStatus   // Server status
}
