// Code generated by "stringer -output=enum_strings.go -type=EntryType"; DO NOT EDIT.

package resmon

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GLOBAL_CPU_USAGE-0]
	_ = x[GLOBAL_FREE_MEM-1]
	_ = x[GLOBAL_PROC_COUNT-2]
	_ = x[FS_FREE_SPACE-3]
	_ = x[FS_FREE_INODES-4]
	_ = x[PROC_CPU_USAGE-5]
	_ = x[PROC_VM_SIZE-6]
	_ = x[PROC_FREE_FILE_DESC-7]
	_ = x[PROC_LIFE_TIME-8]
	_ = x[PROC_COUNT-9]
}

const _EntryType_name = "GLOBAL_CPU_USAGEGLOBAL_FREE_MEMGLOBAL_PROC_COUNTFS_FREE_SPACEFS_FREE_INODESPROC_CPU_USAGEPROC_VM_SIZEPROC_FREE_FILE_DESCPROC_LIFE_TIMEPROC_COUNT"

var _EntryType_index = [...]uint8{0, 16, 31, 48, 61, 75, 89, 101, 120, 134, 144}

func (i EntryType) String() string {
	if i < 0 || i >= EntryType(len(_EntryType_index)-1) {
		return "EntryType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EntryType_name[_EntryType_index[i]:_EntryType_index[i+1]]
}
