// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package panel was generated by IDLC from Panel.idl.
// It is part of module pdumodel.
// The remaining comment is for module pdumodel.
//
// PDU Model
package panel

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40032/event/userevent"
	"github.com/arminguenther/xeruspower-go/v40032/pdumodel/circuit"
	"github.com/arminguenther/xeruspower-go/v40032/pdumodel/powermeter"
)

// PMC panel.
//
// A panel contains:
//   - a three-phase power meter
//   - a configurable number of branch meter channels
//   - a configurable number of circuit positions
//   - configurable logical circuits combining multiple positions
type Panel interface {
	powermeter.PowerMeter

	// Retrieve the panel settings.
	//
	//	@return Panel settings
	GetPanelSettings(ctx context.Context) (Settings, error)

	// Change the panel settings.
	//
	//	@param settings  New panel settings
	//
	//	@return 0 if OK
	//	@return 1 if any parameters are invalid
	SetPanelSettings(ctx context.Context, settings Settings) (int32, error)

	// Retrieve the list of circuits.
	//
	//	@return Configured circuits by position
	GetCircuits(ctx context.Context) (map[int32]circuit.Circuit, error)

	// Create a new circuit.
	//
	//	@param circuit   Result: Newly created instance
	//	@param config    New circuit config
	//	@param settings  New circuit settings
	//
	//	@return 0 if OK
	//	@return 1 if the circuit config or settings are invalid
	CreateCircuit(ctx context.Context, config circuit.Config, settings circuit.Settings) (ret int32, circuit circuit.Circuit, err error)

	// Delete a circuit.
	//
	//	@param position  Position of circuit to be deleted
	//
	//	@return 0 if OK
	//	@return 1 if the circuit position is invalid
	DeleteCircuit(ctx context.Context, position int32) (int32, error)
}

// Mapping of physical circuit positions (0-based) to logical labels.
type LabelingScheme int

const (
	SEQUENTIAL LabelingScheme = iota // Circuit positions 0..2 are labeled 1, 2 and 3
	ODD_EVEN                         // Circuit positions 0..2 are labeled 1, 3 and 5 (two columns)
)

// Panel settings
type Settings struct {
	MeterCount     int32          // Number of branch meter channels
	PanelSize      int32          // Panel size (number of circuit positions)
	Columns        int32          // Display circuit positions in two columns
	LabelingScheme LabelingScheme // Mapping of physical circuit positions to logical labels
}

// Event: Panel settings have changed
type SettingsChangedEvent interface {
	userevent.UserEvent
	OldSettings() Settings // Panel settings before change
	NewSettings() Settings // Panel settings after change
	isSettingsChangedEvent()
}

// Event: A new circuit was added
type CircuitCreatedEvent interface {
	userevent.UserEvent
	Circuit() circuit.Circuit   // New circuit
	Config() circuit.Config     // New circuit config
	Settings() circuit.Settings // New circuit settings
	isCircuitCreatedEvent()
}

// Event: A circuit was deleted
type CircuitDeletedEvent interface {
	userevent.UserEvent
	Config() circuit.Config     // Old circuit config
	Settings() circuit.Settings // Old circuit settings
	isCircuitDeletedEvent()
}
