// Code generated by "stringer -output=enum_strings.go -type=PortType"; DO NOT EDIT.

package poselement

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ONBOARD-0]
	_ = x[DEV_PORT-1]
	_ = x[ONEWIRE_HUB_PORT-2]
	_ = x[ONEWIRE_CHAIN_POS-3]
	_ = x[REMOTE_HUB_PORT-4]
	_ = x[WIRELESS_BRIDGE-5]
	_ = x[WIRELESS_DEVICE-6]
	_ = x[UNSPECIFIED-7]
	_ = x[GATEWAY_SENSOR-8]
	_ = x[FEATURE_PORT-9]
	_ = x[USB_PORT-10]
	_ = x[USB_HUB_PORT-11]
	_ = x[USB_RS485_DONGLE-12]
}

const _PortType_name = "ONBOARDDEV_PORTONEWIRE_HUB_PORTONEWIRE_CHAIN_POSREMOTE_HUB_PORTWIRELESS_BRIDGEWIRELESS_DEVICEUNSPECIFIEDGATEWAY_SENSORFEATURE_PORTUSB_PORTUSB_HUB_PORTUSB_RS485_DONGLE"

var _PortType_index = [...]uint8{0, 7, 15, 31, 48, 63, 78, 93, 104, 118, 130, 138, 150, 166}

func (i PortType) String() string {
	if i < 0 || i >= PortType(len(_PortType_index)-1) {
		return "PortType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PortType_name[_PortType_index[i]:_PortType_index[i+1]]
}
