// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package poselement was generated by IDLC from PosElement.idl.
// It is part of module peripheral.
// The remaining comment is for module peripheral.
//
// Peripheral Devices
package poselement

// peripheral device port types
type PortType int

const (
	ONBOARD           PortType = iota // a built-in, inaccessible port
	DEV_PORT                          // a sensor port on the device
	ONEWIRE_HUB_PORT                  // a port on a Hub
	ONEWIRE_CHAIN_POS                 // a chain position
	REMOTE_HUB_PORT                   // a RS485 remote hub port
	WIRELESS_BRIDGE                   // a wireless bridge, e.g. usb dongle
	WIRELESS_DEVICE                   // a wireless device
	UNSPECIFIED                       // device type is unknown
	GATEWAY_SENSOR                    // a gateway sensor
	FEATURE_PORT                      // the feature port
	USB_PORT                          // USB port
	USB_HUB_PORT                      // USB hub port
	USB_RS485_DONGLE                  // USB dongle with rs485 port
)

// peripheral device position element, list forms position
type PosElement struct {
	PortType PortType // type of the element
	Port     string   // value of the element, a label
}
