// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package inlet was generated by IDLC from Inlet.idl.
// It is part of module pdumodel.
// The remaining comment is for module pdumodel.
//
// PDU Model
package inlet

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40033/event/userevent"
	"github.com/arminguenther/xeruspower-go/v40033/pdumodel/edevice"
	"github.com/arminguenther/xeruspower-go/v40033/pdumodel/nameplate"
	"github.com/arminguenther/xeruspower-go/v40033/pdumodel/pole"
	"github.com/arminguenther/xeruspower-go/v40033/pdumodel/residualcurrentstatesensor"
	"github.com/arminguenther/xeruspower-go/v40033/sensors/numericsensor"
	"github.com/arminguenther/xeruspower-go/v40033/sensors/statesensor"
)

// Inlet interface
type Inlet interface {
	edevice.EDevice

	// Retrieve the inlet metadata.
	//
	//	@return Inlet metadata
	GetMetaData(ctx context.Context) (MetaData, error)

	// Get the inlet sensors.
	//
	//	@return Inlet sensors
	GetSensors(ctx context.Context) (Sensors, error)

	// Get the list of inlet poles.
	//
	//	@return List of inlet poles
	GetPoles(ctx context.Context) ([]pole.Pole, error)

	// Get the list of inlet line pairs.
	//
	//	@return List of inlet line pairs
	GetLinePairs(ctx context.Context) ([]pole.MeteredLinePair, error)

	// Retrieve the inlet settings.
	//
	//	@return Inlet settings
	GetSettings(ctx context.Context) (Settings, error)

	// Change the inlet settings.
	//
	//	@param settings  New inlet settings
	//
	//	@return 0 if OK
	//	@return 1 if any parameters are invalid
	SetSettings(ctx context.Context, settings Settings) (int32, error)

	// Enable/disable PDU operation for this inlet.
	//
	// When PDU operation is disabled the sensors for this inlet and all
	// children will no longer be updated, and outlet switching is no
	// longer allowed. This can be useful for multi-inlet units if one
	// inlet is temporarily expected to be powered down.
	//
	//	@param enabled  true to enable PDU operation
	SetEnabled(ctx context.Context, enabled bool) error

	// Test whether PDU operation is enabled for this inlet.
	//
	//	@return true if PDU operation is enabled
	IsEnabled(ctx context.Context) (bool, error)
}

// Inlet metadata
type MetaData struct {
	Label              string              // Inlet label
	PlugType           string              // Plug type
	NamePlate          nameplate.Nameplate // Nameplate information
	Rating             nameplate.Rating    // Numerical usage ratings
	HasWaveformSupport bool                // Whether waveform reading is supported on this inlet
	IsDC               bool                // Current type, true for DC, false for AC
}

// Inlet sensors
type Sensors struct {
	Voltage         numericsensor.NumericSensor // RMS voltage sensor (may be a VoltageMonitoringSensor)
	Current         numericsensor.NumericSensor // RMS current sensor
	PeakCurrent     numericsensor.NumericSensor // Peak current sensor
	ResidualCurrent numericsensor.NumericSensor // Residual current sensor
	// AC Residual current sensor
	// (AC portion of residual operating current)
	ResidualACCurrent numericsensor.NumericSensor
	// DC Residual current sensor
	// (DC portion of residual operating current)
	ResidualDCCurrent         numericsensor.NumericSensor
	ActivePower               numericsensor.NumericSensor                           // Active power sensor
	ReactivePower             numericsensor.NumericSensor                           // Reactive power sensor
	ApparentPower             numericsensor.NumericSensor                           // Apparent power sensor
	PowerFactor               numericsensor.NumericSensor                           // Power factor sensor
	DisplacementPowerFactor   numericsensor.NumericSensor                           // Displacement power factor sensor
	ActiveEnergy              numericsensor.NumericSensor                           // Active energy sensor
	ApparentEnergy            numericsensor.NumericSensor                           // Apparent energy sensor
	UnbalancedCurrent         numericsensor.NumericSensor                           // Current unbalance sensor
	UnbalancedLineLineCurrent numericsensor.NumericSensor                           // Line-Line current unbalance sensor
	UnbalancedVoltage         numericsensor.NumericSensor                           // Voltage unbalance sensor
	UnbalancedLineLineVoltage numericsensor.NumericSensor                           // Line-Line voltage unbalance sensor
	LineFrequency             numericsensor.NumericSensor                           // Line AC frequency sensor
	PhaseAngle                numericsensor.NumericSensor                           // Phase angle sensor
	CrestFactor               numericsensor.NumericSensor                           // Crest factor sensor
	VoltageThd                numericsensor.NumericSensor                           // Voltage total harmonic distortion sensor
	CurrentThd                numericsensor.NumericSensor                           // Current total harmonic distortion sensor
	PowerQuality              statesensor.StateSensor                               // Power quality sensor
	SurgeProtectorStatus      statesensor.StateSensor                               // Surge protector status sensor
	ResidualCurrentStatus     residualcurrentstatesensor.ResidualCurrentStateSensor // Residual current monitor state sensor
}

// Inlet settings
type Settings struct {
	Name string // User-defined name
}

// Event: Inlet settings have been changed
type SettingsChangedEvent interface {
	userevent.UserEvent
	OldSettings() Settings // Settings before change
	NewSettings() Settings // Settings after change
	isSettingsChangedEvent()
}

// Event: Inlet has been enabled or disabled
type EnableStateChangedEvent interface {
	userevent.UserEvent
	Enabled() bool // New enable state
	isEnableStateChangedEvent()
}
