// Code generated by "stringer -output=enum_strings.go -type=EnrollmentRunStatus"; DO NOT EDIT.

package scep

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NOT_RUN-0]
	_ = x[STARTED-1]
	_ = x[PENDING-2]
	_ = x[SUCCESS-3]
	_ = x[FAILED-4]
}

const _EnrollmentRunStatus_name = "NOT_RUNSTARTEDPENDINGSUCCESSFAILED"

var _EnrollmentRunStatus_index = [...]uint8{0, 7, 14, 21, 28, 34}

func (i EnrollmentRunStatus) String() string {
	if i < 0 || i >= EnrollmentRunStatus(len(_EnrollmentRunStatus_index)-1) {
		return "EnrollmentRunStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EnrollmentRunStatus_name[_EnrollmentRunStatus_index[i]:_EnrollmentRunStatus_index[i+1]]
}
