// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package diaglogsettings was generated by IDLC from DiagLogSettings.idl.
// It is part of module diag.
// The remaining comment is for module diag.
//
// Diagnostics
package diaglogsettings

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40411/idl"
)

const (
	ERR_NONE                     int32 = 0 // no error
	ERR_UNKNOWN_LOG_CONTEXT_NAME int32 = 1 // unknown log context
	ERR_UNKNOWN_LOG_LEVEL        int32 = 2 // unknown log level
)

// Diagnostic log settings
type DiagLogSettings interface {
	idl.Object

	// Reset log levels of all contexts to default.
	ResetLogLevelsForAllCtxNames(ctx context.Context) error

	// Get log levels of all contexts.
	//
	//	@return vector of LogLevelEntry structures
	GetLogLevelsForAllCtxNames(ctx context.Context) ([]LogLevelEntry, error)

	// Set the log level for all contexts at once.
	//
	//	@param logLevel - log level
	//
	//	@return ERR_NONE on success
	//	@return ERR_UNKNOWN_LOG_LEVEL if log level is unknown
	SetLogLevelForAllCtxNames(ctx context.Context, logLevel LogLevel) (int32, error)

	// Get the log level for a specific context.
	//
	//	@param ctxName - context name
	//	@param logLevel - result: log level
	//
	//	@return ERR_NONE on success
	//	@return ERR_UNKNOWN_LOG_CONTEXT_NAME if the context is unknown
	//	@return ERR_UNKNOWN_LOG_LEVEL if log level cannot be mapped to JSON
	GetLogLevelByCtxName(ctx context.Context, ctxName string) (ret int32, logLevel LogLevel, err error)

	// Set the log level for a specific context.
	//
	//	@param ctxName - context name
	//	@param logLevel - log level
	//
	//	@return ERR_NONE on success
	//	@return ERR_UNKNOWN_LOG_CONTEXT_NAME if the context is unknown
	//	@return ERR_UNKNOWN_LOG_LEVEL if log level is unknown
	SetLogLevelByCtxName(ctx context.Context, ctxName string, logLevel LogLevel) (int32, error)
}

// Log levels
type LogLevel int

const (
	LOG_LEVEL_NONE  LogLevel = iota // no log messages
	LOG_LEVEL_ERR                   // errors
	LOG_LEVEL_WARN                  // warnings + errors
	LOG_LEVEL_INFO                  // info + warnings + errors
	LOG_LEVEL_DEBUG                 // debug + info + warnings + errors
	LOG_LEVEL_TRACE                 // trace + debug + info + warnings + errors
)

// An entry containing a context name and its associated context.
type LogLevelEntry struct {
	CtxName  string   // log context name
	LogLevel LogLevel // log level
}
