// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Code generated by "stringer -output=enum_strings.go -type=AuthenType"; DO NOT EDIT.

package tacplusserversettings

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ASCII-0]
	_ = x[PAP-1]
	_ = x[CHAP-2]
	_ = x[MSCHAP-3]
}

const _AuthenType_name = "ASCIIPAPCHAPMSCHAP"

var _AuthenType_index = [...]uint8{0, 5, 8, 12, 18}

func (i AuthenType) String() string {
	if i < 0 || i >= AuthenType(len(_AuthenType_index)-1) {
		return "AuthenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AuthenType_name[_AuthenType_index[i]:_AuthenType_index[i+1]]
}
