// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package tacplusserversettings was generated by IDLC from TacPlusServerSettings.idl.
// It is part of module tacplus.
// The remaining comment is for module tacplus.
//
// TACACS+ server interface
package tacplusserversettings

// TACACS+ authentication type
type AuthenType int

const (
	ASCII AuthenType = iota
	PAP
	CHAP
	MSCHAP
)

// Server settings
type ServerSettings struct {
	Server            string // TACACS+ server name or IP address
	Port              int32  // TACACS+ server TCP port
	TimeoutSeconds    int32  // max time from connecting until session completion
	Retries           int32  // max number of allowed retries
	SharedSecret      string
	AuthenType        AuthenType
	DisableAccounting bool
}
