// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package fitness was generated by IDLC from Fitness.idl.
// It is part of module fitness.
// The remaining comment is for module fitness.
//
// Fitness Daemon
package fitness

import (
	"context"
	"time"

	"github.com/arminguenther/xeruspower-go/v40010/idl"
)

// The value/worstValue/rawValue is invalid (e.g. not initialized).
const FLAG_VALUE_INVALID int32 = 0x1

// The value/rawValue is out-dated.
const FLAG_VALUE_OLD int32 = 0x2

// Violating the threshold is a critical event.
const FLAG_ENTRY_CRITICAL int32 = 0x4

// Fitness Daemon interface
type Fitness interface {
	idl.Object

	// Returns the fitness data entries.
	//
	// The count of entries depends on the device. For example a PDU each
	// sub controller currently has 3 entries + 2 entries per relay. The
	// data is updated only once or twice a minute.
	//
	//	@return -- the vector with the fitness data entries
	GetDataEntries(ctx context.Context) ([]DataEntry, error)

	// Returns the error log index range.
	//
	//	@param firstIndex -- the first valid index
	//	@param entryCount -- the count of entries in the error log
	GetErrorLogIndexRange(ctx context.Context) (firstIndex int32, entryCount int32, err error)

	// Returns the error log.
	//
	// If the startIndex is smaller than the first index in the log than
	// the count of returned entries is smaller (or even 0) as well.
	//
	//	@param startIndex -- the index of the first entry to return
	//	@param count -- the count of entries starting from the startIndex
	//	@return -- the vector with the error log entries
	GetErrorLogEntries(ctx context.Context, startIndex int32, count int32) ([]ErrorLogEntry, error)
}

// An entry in the reliability database
type DataEntry struct {
	Id             string // unique id of the entry
	Value          int32  // normalized value
	MaxValue       int32  // maximum possible normalized value
	WorstValue     int32  // worst normalized value seen yet
	ThresholdValue int32  // normalized threshold value
	RawValue       int64  // raw value
	Flags          int32  // flags (see above)
}

// An entry in the reliability error log
//
// An error log entry is made when the normalized value of a data entry
// drops below the normalized threshold value.
type ErrorLogEntry struct {
	Id             string    // id of the associated data entry
	Value          int32     // normalized value
	ThresholdValue int32     // normalized threshold value
	RawValue       int64     // raw value
	PowerOnHours   int32     // power on hours when error occured
	TimeStampUTC   time.Time // UTC time stamp when error occured
}
