// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package authmanager was generated by IDLC from AuthManager.idl.
// It is part of module auth.
// The remaining comment is for module auth.
//
// Local and Remote Authentication Management
package authmanager

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40410/idl"
)

// Authentication type
type Type int

const (
	LOCAL       Type = iota // local authentication
	RADIUS                  // authentication via radius server
	KERBEROS                // authentication with kerberos tickets (not implemented)
	TACACS_PLUS             // authentication via TACACS+
	LDAP                    // authentication via LDAP server
)

// Authentication policy
//
// The authentication policy does only partly apply to SNMPv3 as it always uses local authentication.
// When SNMPv3 is enabled, all local user accounts for which SNMPv3 access is configured will be
// available via SNMPv3 except the account has admin privilege and disallowLocalAuthAdminRemoteAccess
// is set to true.
type Policy struct {
	Type                               Type // Authentication type
	DisallowLocalAuthAdminRemoteAccess bool // Disallow remote access for locally authenticated administrators
	UseLocalIfRemoteFailed             bool // Fall back to local authentication if remote authentication fails (deprecated; recommended setting: false)
}

const ERR_UNSUPPORTED_TYPE int32 = 1 // Unsupported authentication type

// Authentication manager interface
type AuthManager interface {
	idl.Object

	// Gets a policy.
	//
	//	@return a Policy object
	GetPolicy(ctx context.Context) (Policy, error)

	// Sets a policy.
	//
	//	@return 0 on success
	//	@return 1 in case authentication type is not supported
	SetPolicy(ctx context.Context, p Policy) (int32, error)
}
