// Code generated by "stringer -output=enum_strings.go -type=Type"; DO NOT EDIT.

package authmanager

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LOCAL-0]
	_ = x[RADIUS-1]
	_ = x[KERBEROS-2]
	_ = x[TACACS_PLUS-3]
	_ = x[LDAP-4]
}

const _Type_name = "LOCALRADIUSKERBEROSTACACS_PLUSLDAP"

var _Type_index = [...]uint8{0, 5, 11, 19, 30, 34}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
