// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package powerbus was generated by IDLC from PowerBus.idl.
// It is part of module pdumodel.
// The remaining comment is for module pdumodel.
//
// PDU Model
package powerbus

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40413/pdumodel/edevice"
	"github.com/arminguenther/xeruspower-go/v40413/pdumodel/pole"
	"github.com/arminguenther/xeruspower-go/v40413/sensors/numericsensor"
)

// Power bus interface
type PowerBus interface {
	edevice.EDevice

	// Retrieve the bus sensors.
	//
	//	@return Bus sensors
	GetSensors(ctx context.Context) (Sensors, error)

	// Get the list of poles.
	//
	//	@return List of poles
	GetPoles(ctx context.Context) ([]pole.Pole, error)
}

// Bus sensors
type Sensors struct {
	Current      numericsensor.NumericSensor // Current sensor
	Voltage      numericsensor.NumericSensor // Voltage sensor
	ActivePower  numericsensor.NumericSensor // Active power sensor
	ActiveEnergy numericsensor.NumericSensor // Active energy sensor
}
