// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package usb was generated by IDLC from Usb.idl.
// It is part of module usb.
// The remaining comment is for module usb.
//
// USB Ports
package usb

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40220/event/userevent"
	"github.com/arminguenther/xeruspower-go/v40220/idl"
)

// USB device information
type Device struct {
	PortNumber   int32  // USB Port number (1-based)
	Bus          int32  // Bus number
	Device       int32  // Device address
	VendorId     int32  // Vendor ID
	ProductId    int32  // Product ID
	Manufacturer string // Manufacturer
	Product      string // Product
}

// USB interface
type Usb interface {
	idl.Object

	// Retrieve the USB interface settings.
	//
	//	@return USB interface settings
	GetSettings(ctx context.Context) (Settings, error)

	// Change the USB interface settings.
	//
	//	@param settings  New settings
	//
	//	@return 0 if OK
	SetSettings(ctx context.Context, settings Settings) (int32, error)

	// Retrieve the number of external USB-A ports.
	//
	//	@return Number of host ports
	GetHostPortCount(ctx context.Context) (int32, error)

	// Get a list of USB devices connected to the host ports.
	//
	//	@param usbDevices  Result: List of discovered devices
	GetDevices(ctx context.Context) (usbDevices []Device, err error)
}

// USB interface settings
type Settings struct {
	HostPortsEnabled bool // \false to deactivate the device's USB-A host ports
}

// Event: Settings have changed
type SettingsChangedEvent interface {
	userevent.UserEvent
	OldSettings() Settings // Settings before change
	NewSettings() Settings // Settings after change
	isSettingsChangedEvent()
}
