// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package dsamdevice was generated by IDLC from DsamDevice.idl.
// It is part of module dsam.
// The remaining comment is for module dsam.
package dsamdevice

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40412/dsam/dsamport"
	"github.com/arminguenther/xeruspower-go/v40412/idl"
)

// Success code
const SUCCESS int32 = 0

// DSAM device interface
type DsamDevice interface {
	idl.Object

	// Get DSAM device info
	//
	//	@return DSAM device info
	GetInfo(ctx context.Context) (Info, error)

	// Retrieve the current DSAM ports.
	//
	//	@return Map with DSAM ports. Index is the port number (1-based).
	GetPorts(ctx context.Context) (map[int32]dsamport.DsamPort, error)

	// Start firmware update on the DSAM device.
	//
	//	@return SUCCESS if no error occurred
	StartFirmwareUpdate(ctx context.Context) (int32, error)
}

// Firmware version
type FirmwareVersion struct {
	Major int32 // major version number
	Minor int32 // minor version number
}

// DSAm device info
type Info struct {
	DsamNumber      int32           // DSAM number (1-based)
	SerialNumber    string          // DSAM serial number
	PortCount       int32           // Number of ports on the DSAM
	HardwareVersion int32           // Hardware version number
	FirmwareVersion FirmwareVersion // Firmware version
}
