// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package bluetooth was generated by IDLC from Bluetooth.idl.
// It is part of module devsettings.
// The remaining comment is for module devsettings.
//
// Device Settings
package bluetooth

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40510/event/userevent"
	"github.com/arminguenther/xeruspower-go/v40510/idl"
)

// Bluetooth settings
type Bluetooth interface {
	idl.Object

	// Retrieve the Bluetooth settings.
	//
	//	@return Bluetooth settings
	GetSettings(ctx context.Context) (Settings, error)

	// Change the Bluetooth settings.
	//
	//	@param settings  New settings
	//
	//	@return 0 if OK
	SetSettings(ctx context.Context, settings Settings) (int32, error)
}

// Bluetooth antenna selection
type Antenna int

const (
	Internal Antenna = iota // Internal antenna
	External                // External antenna
)

// Bluetooth settings
type Settings struct {
	Enabled bool    // Enable Bluetooth radio
	Antenna Antenna // Antenna selection
}

// Event: Bluetooth settings have been changed
type SettingsChangedEvent interface {
	userevent.UserEvent
	OldSettings() Settings // Settings before change
	NewSettings() Settings // Settings after change
	isSettingsChangedEvent()
}
