// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package radiusmanager was generated by IDLC from RadiusManager.idl.
// It is part of module auth.
// The remaining comment is for module auth.
//
// Local and Remote Authentication Management
package radiusmanager

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40200/idl"
)

const (
	ERR_INVALID_CFG           int32 = 1 // The server configuration is invalid
	ERR_SERVER_UNSPECIFIED    int32 = 2 // Unspecified error
	ERR_INVALID_SHARED_SECRET int32 = 3 // The shared secret is invalid
	ERR_SERVER_UNREACHABLE    int32 = 4 // RADIUS server could not be contacted
	ERR_AUTHENTICATION_FAILED int32 = 5 // User could not be authenticated
	ERR_NO_ROLES              int32 = 6 // No roles are defined for the user
	ERR_NO_KNOWN_ROLES        int32 = 7 // No known rules are defined for the user
)

// RADIUS server configuration interface
type RadiusManager interface {
	idl.Object

	// Get a list of RADIUS server settings
	//
	//	@return list of ServerSettings
	GetRadiusServers(ctx context.Context) ([]ServerSettings, error)

	// Sets a list of RADIUS servers.
	// Any existing RADIUS Server configuration will be cleared / overwritten.
	//
	//	@return 0                            on success
	//	@return ERR_INVALID_CFG           in case of invalid configuration
	SetRadiusServers(ctx context.Context, serverList []ServerSettings) (int32, error)

	// Tests an RADIUS server configuration.
	//
	//	@return 0                                    on success
	//	@return ERR_SERVER_UNSPECIFIED            an unspecified error occurred
	//	@return ERR_INVALID_CFG                   RADIUS server configuration is invalid (reused from setRadiusServers)
	//	@return ERR_INVALID_SHARED_SECRET         the shared secret is invalid
	//	@return ERR_SERVER_UNREACHABLE            RADIUS server could not be contacted
	//	@return ERR_AUTHENTICATION_FAILED         user could not be authenticated
	//	@return ERR_NO_ROLES                      no roles are defined for the user
	//	@return ERR_NO_KNOWN_ROLES                no known roles are defined for the user
	TestRadiusServer(ctx context.Context, username string, password string, settings ServerSettings) (int32, error)
}

// RADIUS auth type
type AuthType int

const (
	PAP      AuthType = iota // PAP authentication
	CHAP                     // CHAP authentication
	MSCHAPv2                 // MSCHAPv2 authentication
)

// Server settings
type ServerSettings struct {
	Id                string   // This field is unused; empty on read, ignored on write
	Server            string   // IP or name of the radius servers
	SharedSecret      string   // Shared secret between the Xerus device and the RADIUS server
	UdpAuthPort       int32    // UDP port for RADIUS Authenticating service
	UdpAccountPort    int32    // UDP port for RADIUS Accounting service
	Timeout           int32    // Timeout in seconds
	Retries           int32    // Number of retries
	AuthType          AuthType // Authentication type
	DisableAccounting bool     // true to disable accounting, false to enable accounting
}
