// Code generated by "stringer -output=enum_strings.go -type=Type,TransferReason"; DO NOT EDIT.

package transferswitch

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[STS-0]
	_ = x[ATS-1]
	_ = x[HTS-2]
}

const _Type_name = "STSATSHTS"

var _Type_index = [...]uint8{0, 3, 6, 9}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[REASON_UNKNOWN-0]
	_ = x[REASON_STARTUP-1]
	_ = x[REASON_MANUAL_TRANSFER-2]
	_ = x[REASON_AUTO_RETRANSFER-3]
	_ = x[REASON_POWER_FAILURE-4]
	_ = x[REASON_POWER_QUALITY-5]
	_ = x[REASON_OVERLOAD-6]
	_ = x[REASON_OVERHEAT-7]
	_ = x[REASON_INTERNAL_FAILURE-8]
	_ = x[REASON_BYPASS_ACTIVE-9]
}

const _TransferReason_name = "REASON_UNKNOWNREASON_STARTUPREASON_MANUAL_TRANSFERREASON_AUTO_RETRANSFERREASON_POWER_FAILUREREASON_POWER_QUALITYREASON_OVERLOADREASON_OVERHEATREASON_INTERNAL_FAILUREREASON_BYPASS_ACTIVE"

var _TransferReason_index = [...]uint8{0, 14, 28, 50, 72, 92, 112, 127, 142, 165, 185}

func (i TransferReason) String() string {
	if i < 0 || i >= TransferReason(len(_TransferReason_index)-1) {
		return "TransferReason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TransferReason_name[_TransferReason_index[i]:_TransferReason_index[i+1]]
}
