// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package statesensor was generated by IDLC from StateSensor.idl.
// It is part of module sensors.
// The remaining comment is for module sensors.
//
// Sensors Model
package statesensor

import (
	"context"
	"time"

	"github.com/arminguenther/xeruspower-go/v40032/idl/event"
	"github.com/arminguenther/xeruspower-go/v40032/sensors/sensor"
)

// Sensor with discrete readings
//
// Sensor states are represented as a numerical field in the State
// structure. The interpretation of this value depends on the sensor
// type which can be queried with the getTypeSpec() method.
//
// Mappings for typical sensor types are:
//
// | Sensor Type         | States                |
// |---------------------|-----------------------|
// | CONTACT_CLOSURE     | normal(0), alarmed(1) |
// | ON_OFF_SENSOR       | off(0), on(1)         |
// | TRIP_SENSOR         | open(0), close(1)     |
// | VIBRATION           | normal(0), alarmed(1) |
// | WATER_LEAK          | normal(0), alarmed(1) |
// | SMOKE_DETECTOR      | normal(0), alarmed(1) |
// | FAULT_STATE         | OK(0), fault(1)       |
// | OCCUPANCY           | normal(0), alarmed(1) |
// | TAMPER              | normal(0), alarmed(1) |
// | DOOR_LOCKSTATE      | open(0), close(1)     |
// | DOORHANDLE_LOCK     | open(0), close(1)     |
// | DOORHANDLE_SWITCH   | open(0), close(1)     |
//
// For some special sensors there are constants defining the possible
// state values, for instance in PowerQualitySensor.idl or
// ResidualCurrentStateSensor.idl.
type StateSensor interface {
	sensor.Sensor

	// Get the sensor state.
	//
	//	@return Sensor state
	GetState(ctx context.Context) (State, error)
}

// Sensor state
type State struct {
	Timestamp time.Time // UNIX timestamp (UTC) of last sample
	Available bool      // true if the sensor is available
	Value     int32     // Discrete sensor value; intrepretation depends on the type of sensor
}

type StateChangedEvent interface {
	event.Event
	OldState() State
	NewState() State
	isStateChangedEvent()
}
