// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package portfuse was generated by IDLC from PortFuse.idl.
// It is part of module portsmodel.
// The remaining comment is for module portsmodel.
//
// Ports
package portfuse

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40220/idl"
	"github.com/arminguenther/xeruspower-go/v40220/idl/event"
)

// Interface describing a controllable fuse for a device port
type PortFuse interface {
	idl.Object

	// Get the current status of the fuse
	//
	//	@return Current fuse status
	GetStatus(ctx context.Context) (Status, error)

	// Attempt a fuse reset
	//
	// Tries to recover the fuse from tripped state. When calling
	// this after correcting the previous short circuit condition,
	// the fuse should transition into 'good' state again. If the
	// short circuit condition is still present, this operation
	// is a no-op.
	Reset(ctx context.Context) error

	// Get the trip count of the fuse (since last reboot)
	//
	//	@return Current fuse trip count
	GetTripCount(ctx context.Context) (int32, error)
}

// Status type for port fuse
type Status int

const (
	UNKNOWN Status = iota // Status can't be determined
	TRIPPED               // Fuse is open (tripped)
	GOOD                  // Fuse is closed (good)
)

// Event: The state of the fuse has changed
type StatusChangedEvent interface {
	event.Event
	OldStatus() Status // Previous fuse status
	NewStatus() Status // Current (new) fuse status
	isStatusChangedEvent()
}
