// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package alertedsensormanager was generated by IDLC from AlertedSensorManager.idl.
// It is part of module sensors.
// The remaining comment is for module sensors.
//
// Sensors model
package alertedsensormanager

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40020/idl"
	"github.com/arminguenther/xeruspower-go/v40020/idl/event"
	"github.com/arminguenther/xeruspower-go/v40020/sensors/sensor"
)

// A global instance keeping track of sensors in alerted state
type AlertedSensorManager interface {
	idl.Object

	// Retrieve the current sensor counts.
	//
	//	@return  Current sensor counts
	GetSensorCounts(ctx context.Context) (SensorCounts, error)

	// Retrieve a list of all monitored sensors.
	//
	//	@return  List of monitored sensors including alert state
	GetAllSensors(ctx context.Context) ([]SensorData, error)

	// Retrieve a list of currently alerted sensors.
	//
	//	@return  List of alerted sensors
	GetAlertedSensors(ctx context.Context) ([]SensorData, error)
}

// Sensor alert state
type AlertState int

const (
	UNAVAILABLE AlertState = iota // Sensor is unavailable
	NORMAL                        // Sensor is not alerted
	CRITICAL                      // Sensor is in critical state
	WARNED                        // Sensor is in warned state
)

// Statistics about monitored sensors
type SensorCounts struct {
	Total       int32 // Total number of monitored sensors
	Unavailable int32 // Number of unavailable sensors
	Critical    int32 // Number of critical sensors
	Warned      int32 // Number of warned sensors
}

// Data about a monitored sensor.
//
// All entries include a reference to the sensor's parent object (e.g.
// an inlet or a peripheral device slot), allowing a client to identify
// an unknown alerted sensor with just a few RPC calls.
type SensorData struct {
	Sensor     sensor.Sensor // Reference to the sensor object
	Parent     idl.Object    // Reference to the sensor's parent object
	AlertState AlertState    // Current alert state of the sensor
}

// Event: A change in the list of monitored sensors occurred.
//
// This event is fired when sensors are added to or removed from the
// list of monitored sensors. It is not fired when a monitored sensor's
// alert state changes.
type MonitoredSensorsChangedEvent interface {
	event.Event
	Counts() SensorCounts // Sensor statistics after the change
	isMonitoredSensorsChangedEvent()
}

// Event: One or more sensors' alert states have changed.
//
// This event is fired whenever the result of getAlertedSensors()
// changes, i.e. in the following cases:
//   - An existing sensor's alert state changes
//   - A newly added sensor is alerted
//   - A sensor that was alerted is removed
type AlertedSensorsChangedEvent interface {
	event.Event
	Counts() SensorCounts            // Sensor statistics after the change
	ChangedSensors() []SensorData    // Changed or added sensors
	RemovedSensors() []sensor.Sensor // Removed sensors
	isAlertedSensorsChangedEvent()
}
