// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package redfish was generated by IDLC from Redfish.idl.
// It is part of module devsettings.
// The remaining comment is for module devsettings.
//
// Device Settings
package redfish

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40100/idl"
)

// Redfish API service settings interface
type Redfish interface {
	idl.Object

	// Retrieve Redfish settings.
	//
	//	@return Redfish settings
	GetSettings(ctx context.Context) (Settings, error)

	// Set Redfish settings.
	//
	//	@param settings New settings
	SetSettings(ctx context.Context, settings Settings) error
}

// Redfish settings
type Settings struct {
	Enabled bool // Enable the Redfish API service
}
