// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package datetime was generated by IDLC from DateTime.idl.
// It is part of module datetime.
// The remaining comment is for module datetime.
//
// Device Date and Time Configuration
package datetime

import (
	"context"
	"time"

	"github.com/arminguenther/xeruspower-go/v40000/idl"
	"github.com/arminguenther/xeruspower-go/v40000/idl/event"
)

// Date and time configuration methods
type DateTime interface {
	idl.Object

	// List all supported time zones.
	//
	//	@param zoneInfos  Result: List of time zones
	//	@param useOlson   Use Olson zoneinfo names
	GetZoneInfos(ctx context.Context, useOlson bool) (zoneInfos []ZoneInfo, err error)

	// Check if a specified NTP server is usable.
	//
	//	@param ntpServer  NTP server to be checked
	//
	//	@return true if the NTP server is usable
	CheckNtpServer(ctx context.Context, ntpServer string) (bool, error)

	// Get active NTP servers.
	//
	//	@return List of currently active NTP servers (IP addresses and/or hostnames)
	GetActiveNtpServers(ctx context.Context) ([]string, error)

	// Retrieve the device date and time configuration.
	//
	//	@param cfg  Result: Current date and time configration
	GetCfg(ctx context.Context) (cfg Cfg, err error)

	// Set the device date and time configuration.
	// Depending on the value of the protocol field either deviceTime
	// or ntpCfg will be used from the cfg parameter.
	//
	//	@param cfg  New date and time configuration.
	//
	//	@return 0 if OK
	//	@return 1 if the configuration is invalid
	SetCfg(ctx context.Context, cfg Cfg) (int32, error)

	// Retrieve the current device date and time.
	//
	//	@param useOlson     Use Olson zoneinfo name
	//	@param zone         Result: Active time zone
	//	@param dstEnabled   if false, the time zone DST flag is not used
	//	@param utcOffset    Result: Offset (in minutes) between local time and UTC
	//	@param currentTime  Result: Device date and time (UNIX timestamp, UTC)
	GetTime(ctx context.Context, useOlson bool) (zone ZoneInfo, dstEnabled bool, utcOffset int32, currentTime time.Time, err error)
}

// Time zone information
type ZoneInfo struct {
	Id         int32  // Time zone id
	Name       string // Time zone name
	HasDSTInfo bool   // true if the time zone uses DST
}

// Time zone configuration
type ZoneCfg struct {
	Id            int32  // Selected time zone id
	Name          string // Selected time zone name
	EnableAutoDST bool   // Enable automatic DST adjustment
}

// Time synchronization protocol
type Protocol int

const (
	STATIC Protocol = iota // Device time is configured locally
	NTP                    // Device time is synchronized via NTP
)

// Static NTP server configuration
type NtpCfg struct {
	Server1 string // Primary NTP server
	Server2 string // Secondary NTP server
}

// Device date and time configuration
type Cfg struct {
	ZoneCfg    ZoneCfg   // Time zone configuration
	Protocol   Protocol  // Time synchronization protocol
	DeviceTime time.Time // Device date and time (local time)
	NtpCfg     NtpCfg    // NTP server configuration
}

// Event that is send when the configuration changes
type ConfigurationChangedEvent interface {
	event.Event
	isConfigurationChangedEvent()
}
