// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package datetime was generated by IDLC from DateTime.idl.
// It is part of module datetime.
// The remaining comment is for module datetime.
//
// Device Date and Time Configuration
package datetime

import (
	"context"
	"time"

	"github.com/arminguenther/xeruspower-go/idl"
	"github.com/arminguenther/xeruspower-go/idl/event"
)

// Date and time configuration methods
//
// Example to set timezone (id-based approach): @anchor set-timezone-example
//
//	@code{.py}
//	zoneinfos = getZoneInfos(False)
//	cfg = getCfg()
//	cfg.zoneCfg.id = ... # choose zone id from returned zoneinfos
//	status = setCfg(cfg)
//	if status != 0: ... # error handling
//	@endcode
type DateTime interface {
	idl.Object

	// List all supported time zones.
	//
	//	@param zoneInfos  Result: List of time zones
	//	@param useOlson   Use Olson timezone names (see also ZoneCfg)
	GetZoneInfos(ctx context.Context, useOlson bool) (zoneInfos []ZoneInfo, err error)

	// Check if a specified NTP server is usable.
	//
	//	@param ntpServer  NTP server to be checked
	//
	//	@return true if the NTP server is usable
	CheckNtpServer(ctx context.Context, ntpServer string) (bool, error)

	// Get active NTP servers.
	//
	//	@return List of currently active NTP servers (IP addresses and/or hostnames)
	GetActiveNtpServers(ctx context.Context) ([]string, error)

	// Retrieve the device date and time configuration.
	//
	//	@param cfg  Result: Current date and time configuration
	GetCfg(ctx context.Context) (cfg Cfg, err error)

	// Set the device date and time configuration.
	// Depending on the value of the protocol field either deviceTime
	// or ntpCfg will be used from the cfg parameter.
	//
	// Specific @ref set-timezone-example "example" to set timezone.
	//
	//	@param cfg  New date and time configuration.
	//
	//	@return 0 if OK
	//	@return 1 if the configuration is invalid
	SetCfg(ctx context.Context, cfg Cfg) (int32, error)

	// Retrieve the current device date and time.
	//
	//	@param useOlson     Use Olson timezone name (see also ZoneCfg)
	//	@param zone         Result: Active time zone
	//	@param dstEnabled   if false, the time zone daylight saving time flag is not used
	//	@param utcOffset    Result: Offset (in minutes) between local time and UTC
	//	@param currentTime  Result: Device date and time (UNIX timestamp, UTC)
	GetTime(ctx context.Context, useOlson bool) (zone ZoneInfo, dstEnabled bool, utcOffset int32, currentTime time.Time, err error)
}

// Time zone information (see also ZoneCfg)
//
// There are two different approaches on how to identify timezones. See the ZoneCfg description.
//
// For timezones with non-trivial daylight saving time rules hasDSTInfo is false.
type ZoneInfo struct {
	Id         int32  // Time zone id
	Name       string // Time zone name
	HasDSTInfo bool   // true if the time zone has daylight saving time rules
}

// Time zone configuration
//
// There are two approaches on how timezones are identified:
//
// 1. id-based
//   - timezone data identified with a numeric non-zero id
//   - id != 0
//   - name is the display name of the timezone and ignored on setCfg()
//
// 2. name-based (see NOTES below!)
//   - timezone data identified with a name from the IANA timezone database (aka Olson database)
//   - id == 0
//   - name is the official IANA timezone name, e.g. Europe/Berlin or America/New_York
//
// **NOTES**:
//   - The user frontends currently only support the id-based approach and may not work correctly with
//     the name-based approach.
//   - Setting enableAutoDST to true has only an effect if the according ZoneInfo::hasDSTInfo
//     field is also true.
type ZoneCfg struct {
	Id            int32  // Selected time zone id
	Name          string // Selected time zone name (ignored on setCfg() if id != 0)
	EnableAutoDST bool   // Enable automatic daylight saving time adjustment
}

// Time synchronization protocol
type Protocol int

const (
	STATIC Protocol = iota // Device time is configured locally
	NTP                    // Device time is synchronized via NTP
)

// Static NTP server configuration
type NtpCfg struct {
	Server1 string // Primary NTP server
	Server2 string // Secondary NTP server
}

// Device date and time configuration
type Cfg struct {
	ZoneCfg    ZoneCfg   // Time zone configuration
	Protocol   Protocol  // Time synchronization protocol
	DeviceTime time.Time // Device date and time (local time)
	NtpCfg     NtpCfg    // NTP server configuration
}

// Event that is sent when the configuration changes
type ConfigurationChangedEvent interface {
	event.Event
	isConfigurationChangedEvent()
}

// Event that is sent when the device time is changed
type ClockChangedEvent interface {
	event.Event
	OldTime() time.Time // Device time before change (UNIX timestamp, UTC)
	NewTime() time.Time // Device time after change (UNIX timestamp, UTC)
	isClockChangedEvent()
}
