// Code generated by "stringer -output=enum_strings.go -type=Protocol"; DO NOT EDIT.

package datetime

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[STATIC-0]
	_ = x[NTP-1]
}

const _Protocol_name = "STATICNTP"

var _Protocol_index = [...]uint8{0, 6, 9}

func (i Protocol) String() string {
	if i < 0 || i >= Protocol(len(_Protocol_index)-1) {
		return "Protocol(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Protocol_name[_Protocol_index[i]:_Protocol_index[i+1]]
}
