// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package sensor was generated by IDLC from Sensor.idl.
// It is part of module sensors.
// The remaining comment is for module sensors.
//
// Sensors Model
package sensor

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40020/idl"
	"github.com/arminguenther/xeruspower-go/v40020/idl/event"
)

const ERR_NOT_SUPPORTED int32 = 1 // The operation is not supported

// Sensor reading type
const (
	NUMERIC         int32 = 0
	DISCRETE_ON_OFF int32 = 1
	DISCRETE_MULTI  int32 = 2
)

// Sensor type
const (
	UNSPECIFIED               int32 = 0
	VOLTAGE                   int32 = 1
	CURRENT                   int32 = 2
	UNBALANCE_CURRENT         int32 = 3
	POWER                     int32 = 4
	POWER_FACTOR              int32 = 5
	ENERGY                    int32 = 6
	FREQUENCY                 int32 = 7
	TEMPERATURE               int32 = 8
	HUMIDITY                  int32 = 9
	AIR_FLOW                  int32 = 10
	AIR_PRESSURE              int32 = 11
	CONTACT_CLOSURE           int32 = 12
	ON_OFF_SENSOR             int32 = 13
	TRIP_SENSOR               int32 = 14
	VIBRATION                 int32 = 15
	WATER_LEAK                int32 = 16
	SMOKE_DETECTOR            int32 = 17
	TOTAL_HARMONIC_DISTORTION int32 = 18
	MASS                      int32 = 19
	ELECTRICAL_RESISTANCE     int32 = 20
	FLUX                      int32 = 21
	LUMINOUS_INTENSITY        int32 = 22
	ACCELERATION              int32 = 23
	MAGNETIC_FLUX_DENSITY     int32 = 24
	ELECTRIC_FIELD_STRENGTH   int32 = 25
	MAGNETIC_FIELD_STRENGTH   int32 = 26
	ANGLE                     int32 = 27
	SELECTION                 int32 = 28
	FAULT_STATE               int32 = 29
	POWER_QUALITY             int32 = 30
	ROTATIONAL_SPEED          int32 = 31
	LUMINOUS_ENERGY           int32 = 32
	LUMINOUS_FLUX             int32 = 33
	ILLUMINANCE               int32 = 34
	LUMINOUS_EMITTANCE        int32 = 35
	MOTION                    int32 = 36
	OCCUPANCY                 int32 = 37
	TAMPER                    int32 = 38
	DRY_CONTACT               int32 = 39
	POWERED_DRY_CONTACT       int32 = 40
	ABSOLUTE_HUMIDITY         int32 = 41
	DOOR_STATE                int32 = 42
	DOOR_LOCK_STATE           int32 = 43
	DOOR_HANDLE_LOCK          int32 = 44
	CREST_FACTOR              int32 = 45
	DISTANCE                  int32 = 46
	LENGTH                    int32 = 47
	UNBALANCE_VOLTAGE         int32 = 48
	PARTICLE_DENSITY          int32 = 49
)

// Sensor unit
const (
	NONE                   int32 = 0
	VOLT                   int32 = 1
	AMPERE                 int32 = 2
	WATT                   int32 = 3
	VOLT_AMP               int32 = 4
	WATT_HOUR              int32 = 5
	VOLT_AMP_HOUR          int32 = 6
	DEGREE_CELSIUS         int32 = 7
	HZ                     int32 = 8
	PERCENT                int32 = 9
	METER_PER_SEC          int32 = 10
	PASCAL                 int32 = 11
	G                      int32 = 12
	RPM                    int32 = 13
	METER                  int32 = 14
	HOUR                   int32 = 15
	MINUTE                 int32 = 16
	SECOND                 int32 = 17
	VOLT_AMP_REACTIVE      int32 = 18
	VOLT_AMP_REACTIVE_HOUR int32 = 19
	GRAM                   int32 = 20
	OHM                    int32 = 21
	LITERS_PER_HOUR        int32 = 22
	CANDELA                int32 = 23
	METER_PER_SQUARE_SEC   int32 = 24
	METER_PER_SQARE_SEC    int32 = 24
	TESLA                  int32 = 25
	VOLT_PER_METER         int32 = 26
	VOLT_PER_AMPERE        int32 = 27
	DEGREE                 int32 = 28
	DEGREE_FAHRENHEIT      int32 = 29
	KELVIN                 int32 = 30
	JOULE                  int32 = 31
	COULOMB                int32 = 32
	NIT                    int32 = 33
	LUMEN                  int32 = 34
	LUMEN_SECOND           int32 = 35
	LUX                    int32 = 36
	PSI                    int32 = 37
	NEWTON                 int32 = 38
	FOOT                   int32 = 39
	FOOT_PER_SEC           int32 = 40
	CUBIC_METER            int32 = 41
	RADIANT                int32 = 42
	STERADIANT             int32 = 43
	HENRY                  int32 = 44
	FARAD                  int32 = 45
	MOL                    int32 = 46
	BECQUEREL              int32 = 47
	GRAY                   int32 = 48
	SIEVERT                int32 = 49
	G_PER_CUBIC_METER      int32 = 50
	UG_PER_CUBIC_METER     int32 = 51
)

// Sensor interface
type Sensor interface {
	idl.Object

	// Retrieve the sensor type specification.
	//
	//	@return Type specification
	GetTypeSpec(ctx context.Context) (TypeSpec, error)

	// Check whether the sensor type can be changed using setType().
	//
	//	@return \true if type change is allowed
	IsTypeChangeAllowed(ctx context.Context) (bool, error)

	// Set sensor type and unit
	//
	//	@param type  the sensor type to set
	//	@param unit  the sensor unit to set
	//
	//	@return ERR_NOT_SUPPORTED or 0
	SetType(ctx context.Context, type_ int32, unit int32) (int32, error)
}

// Sensor states for DISCRETE_ON_OFF sensors
type OnOffState int

const (
	OFF OnOffState = iota // off
	ON                    // on
)

type OpenClosedState int

const (
	OPEN   OpenClosedState = iota // open
	CLOSED                        // closed
)

type NormalAlarmedState int

const (
	NORMAL  NormalAlarmedState = iota // normal (not alarmed)
	ALARMED                           // alarmed
)

type OkFaultState int

const (
	OK    OkFaultState = iota // OK
	FAULT                     // fault
)

// Complete sensor type specification
type TypeSpec struct {
	Readingtype int32 // Sensor reading type
	Type        int32 // Sensor type
	Unit        int32 // Sensor unit
}

// Event: The type specification of the sensor changed
type TypeSpecChangedEvent interface {
	event.Event
	OldTypeSpec() TypeSpec // Type specification before change
	NewTypeSpec() TypeSpec // Type specification after change
	isTypeSpecChangedEvent()
}
