// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package sensor was generated by IDLC from Sensor.idl.
// It is part of module sensors.
// The remaining comment is for module sensors.
//
// Sensors Model
package sensor

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40411/idl"
	"github.com/arminguenther/xeruspower-go/v40411/idl/event"
)

const ERR_NOT_SUPPORTED int32 = 1 // The operation is not supported

// Sensor reading type
const (
	NUMERIC         int32 = 0 // Sensor has numeric readings
	DISCRETE_ON_OFF int32 = 1 // Sensor has two discrete readings: 0 (off) and 1 (on), see OnOffState
	DISCRETE_MULTI  int32 = 2 // Sensor has multiple discrete readings
)

// Sensor type
const (
	UNSPECIFIED               int32 = 0  // Unspecified
	VOLTAGE                   int32 = 1  // Voltage
	CURRENT                   int32 = 2  // Current
	UNBALANCE_CURRENT         int32 = 3  // Current unbalance
	POWER                     int32 = 4  // Power
	POWER_FACTOR              int32 = 5  // Power factor
	ENERGY                    int32 = 6  // Energy
	FREQUENCY                 int32 = 7  // Frequency
	TEMPERATURE               int32 = 8  // Temperature
	HUMIDITY                  int32 = 9  // Relative humidity
	AIR_FLOW                  int32 = 10 // Air flow
	AIR_PRESSURE              int32 = 11 // Air pressure
	CONTACT_CLOSURE           int32 = 12 // Contact Closure [uses NormalAlarmedState mapping]
	ON_OFF_SENSOR             int32 = 13 // Switch state [uses OnOffState mapping]
	TRIP_SENSOR               int32 = 14 // Circuit breaker tripped [uses OpenClosedState mapping]
	VIBRATION                 int32 = 15 // Vibration [uses NormalAlarmedState mapping]
	WATER_LEAK                int32 = 16 // Water leak [uses NormalAlarmedState mapping]
	SMOKE_DETECTOR            int32 = 17 // Smoke detector [uses NormalAlarmedState mapping]
	TOTAL_HARMONIC_DISTORTION int32 = 18 // Total harmonic distortion
	MASS                      int32 = 19 // Mass
	ELECTRICAL_RESISTANCE     int32 = 20 // Electrical resistance
	FLUX                      int32 = 21 // Flux (mass per time, e.g. water flow)
	LUMINOUS_INTENSITY        int32 = 22 // Luminous intensity
	ACCELERATION              int32 = 23 // Acceleration
	MAGNETIC_FLUX_DENSITY     int32 = 24 // Magnetic flux density
	ELECTRIC_FIELD_STRENGTH   int32 = 25 // Electric field strength
	MAGNETIC_FIELD_STRENGTH   int32 = 26 // Magnetic field strength [uses NormalAlarmedState mapping if of DISCRETE_ON_OFF type]
	ANGLE                     int32 = 27 // Angle (e.g. phase angle)
	SELECTION                 int32 = 28 // Selected index (one of n)
	FAULT_STATE               int32 = 29 // Fault state [uses NormalAlarmedState mapping if of DISCRETE_ON_OFF type]
	POWER_QUALITY             int32 = 30 // Power quality
	ROTATIONAL_SPEED          int32 = 31 // Rotational speed (e.g. fan speed)
	LUMINOUS_ENERGY           int32 = 32 // Luminous energy
	LUMINOUS_FLUX             int32 = 33 // Luminous flux
	ILLUMINANCE               int32 = 34 // Illuminance used for light incident on a surface
	LUMINOUS_EMITTANCE        int32 = 35 // Luminous emittance used for light emitted from a surface
	MOTION                    int32 = 36 // Motion detection
	OCCUPANCY                 int32 = 37 // Occupancy detection [uses NormalAlarmedState mapping]
	TAMPER                    int32 = 38 // Tamper detection [uses NormalAlarmedState mapping]
	DRY_CONTACT               int32 = 39 // Dry contact (actuator) [uses OnOffState mapping]
	POWERED_DRY_CONTACT       int32 = 40 // Powered dry contact (actuator) [uses OnOffState mapping]
	ABSOLUTE_HUMIDITY         int32 = 41 // Absolute humidity
	DOOR_STATE                int32 = 42 // Door state [uses OpenClosedState mapping]
	DOOR_LOCK_STATE           int32 = 43 // Door lock state [uses OpenClosedState mapping]
	DOOR_HANDLE_LOCK          int32 = 44 // Door handle switch [uses OpenClosedState mapping]
	CREST_FACTOR              int32 = 45 // Crest factor
	DISTANCE                  int32 = 46 // Distance
	LENGTH                    int32 = 47 // Length
	UNBALANCE_VOLTAGE         int32 = 48 // Voltage unbalance
	PARTICLE_DENSITY          int32 = 49 // Particle Density
	DEW_POINT                 int32 = 50 // Dew Point
	ELECTRICAL_IMPEDANCE      int32 = 51 // Electrical impedance
	TS_BYPASS_STATE           int32 = 52 // Transfer switch bypass state
	BATTERY_LEVEL             int32 = 53 // Battery level
)

// Sensor unit
const (
	NONE                   int32 = 0  // No unit
	VOLT                   int32 = 1  // Electric Potential, Volts (V)
	AMPERE                 int32 = 2  // Electric Current, Amperes (A)
	WATT                   int32 = 3  // Electric Power, Watts (W)
	VOLT_AMP               int32 = 4  // Electric Capacity, Volt Amperes (VA)
	WATT_HOUR              int32 = 5  // Active Energy, Watt hours (Wh)
	VOLT_AMP_HOUR          int32 = 6  // Apparent Energy, Volt-Ampere hours (VAh)
	DEGREE_CELSIUS         int32 = 7  // Temperature, Celsius (deg C)
	HZ                     int32 = 8  // Frequency, Hertz (Hz)
	PERCENT                int32 = 9  // Ratio, Percent (%)
	METER_PER_SEC          int32 = 10 // Speed, Meters per second (m/s)
	PASCAL                 int32 = 11 // Pressure, Pascal (Pa)
	G                      int32 = 12 // Acceleration, G-force (g)
	RPM                    int32 = 13 // Rotation, Revolutions per minute (rpm)
	METER                  int32 = 14 // Distance, Meters (m)
	HOUR                   int32 = 15 // Time, Hours (h)
	MINUTE                 int32 = 16 // Time, Minutes (min)
	SECOND                 int32 = 17 // Time, Seconds (s)
	VOLT_AMP_REACTIVE      int32 = 18 // Reactive Power, Volt Amperes reactive (var)
	VOLT_AMP_REACTIVE_HOUR int32 = 19 // Reactive Energy, Volt Ampere reactive hours (varh)
	GRAM                   int32 = 20 // Mass, Gram (g)
	OHM                    int32 = 21 // Resistance, Ohm (omega, R)
	LITERS_PER_HOUR        int32 = 22 // Flow, Liters per hour (l/h)
	CANDELA                int32 = 23 // Luminous Intensity, Candela (cd)
	METER_PER_SQUARE_SEC   int32 = 24 // Acceleration, Meter per square second (m/s^2)
	METER_PER_SQARE_SEC    int32 = 24 // Typo, preserved for backward compatibility
	TESLA                  int32 = 25 // Magnetic Flux Density, Tesla (T)
	VOLT_PER_METER         int32 = 26 // Electric Field, Volt per meter (V/m)
	VOLT_PER_AMPERE        int32 = 27 // Resistance, Volt per ampere (V/A)
	DEGREE                 int32 = 28 // Angle, Degrees (deg)
	DEGREE_FAHRENHEIT      int32 = 29 // Temperature, Fahrenheit (deg F)
	KELVIN                 int32 = 30 // Temperature, Kelvin (K)
	JOULE                  int32 = 31 // Energy, Joules (J)
	COULOMB                int32 = 32 // Electric Charge, Coulombs (C)
	NIT                    int32 = 33 // Luminance, Nits (cd/m^2)
	LUMEN                  int32 = 34 // Luminous Flux, Lumen (lm)
	LUMEN_SECOND           int32 = 35 // Luminous Energy, Lumen second (lm s)
	LUX                    int32 = 36 // Luminous Flux, Lux (lx)
	PSI                    int32 = 37 // Pressure, Pounds per square inch (psi)
	NEWTON                 int32 = 38 // Force, Newtons (N, J/m)
	FOOT                   int32 = 39 // Distance, Feet (ft)
	FOOT_PER_SEC           int32 = 40 // Speed, Feet per second (ft/s)
	CUBIC_METER            int32 = 41 // Volume, Cubic meters (m^3)
	RADIANT                int32 = 42 // Angle, Radians (rad)
	STERADIANT             int32 = 43 // Solid Angle, Steradians (sr)
	HENRY                  int32 = 44 // Inductance, Henries (H, Vs/A, Ohm s)
	FARAD                  int32 = 45 // Capacitance, Farads (F)
	MOL                    int32 = 46 // Substance Quantity, Moles (mol)
	BECQUEREL              int32 = 47 // Radiation, Becquerels (Bq)
	GRAY                   int32 = 48 // Radiation, Grays (Gy, J/kg)
	SIEVERT                int32 = 49 // Radiation, Sieverts (Sv = J/kg)
	G_PER_CUBIC_METER      int32 = 50 // Density, Grams per cubic meter (g/m^3)
	UG_PER_CUBIC_METER     int32 = 51 // Density, Micrograms per cubic meter (µg/m^3)
)

// Sensor interface
type Sensor interface {
	idl.Object

	// Retrieve the sensor type specification.
	//
	//	@return Type specification
	GetTypeSpec(ctx context.Context) (TypeSpec, error)

	// Check whether the sensor type can be changed using setType().
	//
	//	@return true if type change is allowed
	IsTypeChangeAllowed(ctx context.Context) (bool, error)

	// Set sensor type and unit
	//
	//	@param type  the sensor type to set
	//	@param unit  the sensor unit to set
	//
	//	@return ERR_NOT_SUPPORTED or 0
	SetType(ctx context.Context, type_ int32, unit int32) (int32, error)
}

// Sensor states for DISCRETE_ON_OFF sensors
type OnOffState int

const (
	OFF OnOffState = iota // off
	ON                    // on
)

type OpenClosedState int

const (
	OPEN   OpenClosedState = iota // open
	CLOSED                        // closed
)

type NormalAlarmedState int

const (
	NORMAL  NormalAlarmedState = iota // normal (not alarmed)
	ALARMED                           // alarmed
)

type OkFaultState int

const (
	OK    OkFaultState = iota // OK
	FAULT                     // fault
)

// Complete sensor type specification
type TypeSpec struct {
	Readingtype int32 // Sensor reading type
	Type        int32 // Sensor type
	Unit        int32 // Sensor unit
}

// Event: The type specification of the sensor changed
type TypeSpecChangedEvent interface {
	event.Event
	OldTypeSpec() TypeSpec // Type specification before change
	NewTypeSpec() TypeSpec // Type specification after change
	isTypeSpecChangedEvent()
}
