// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package tacplusmanager was generated by IDLC from TacPlusManager.idl.
// It is part of module auth.
// The remaining comment is for module auth.
//
// Local and Remote Authentication Management
package tacplusmanager

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40220/idl"
)

const (
	ERR_INVALID_CFG           int32 = 1 // The server configuration is invalid
	ERR_SERVER_UNSPECIFIED    int32 = 2 // Unspecified error
	ERR_INVALID_SHARED_SECRET int32 = 3 // The shared secret is invalid
	ERR_SERVER_UNREACHABLE    int32 = 4 // TACACS+ server could not be contacted
	ERR_AUTHENTICATION_FAILED int32 = 5 // User could not be authenticated
	ERR_NO_ROLES              int32 = 6 // No roles are defined for the user
	ERR_NO_KNOWN_ROLES        int32 = 7 // No known rules are defined for the user
)

// TACACS+ server configuration interface
type TacPlusManager interface {
	idl.Object

	// Get a list of TACACS+ server settings
	//
	//	@return list of ServerSettings
	GetTacPlusServers(ctx context.Context) ([]ServerSettings, error)

	// Sets a list of TACACS+ servers.
	// Any existing TACACS+ Server configuration will be cleared / overwritten.
	//
	//	@return 0                            on success
	//	@return ERR_INVALID_CFG           in case of invalid configuration
	SetTacPlusServers(ctx context.Context, serverList []ServerSettings) (int32, error)

	// Tests an TACACS+ server configuration.
	//
	//	@return 0                                    on success
	//	@return ERR_SERVER_UNSPECIFIED            an unspecified error occurred
	//	@return ERR_INVALID_CFG                   server configuration is invalid (reused from setTacPlusServers)
	//	@return ERR_INVALID_SHARED_SECRET         the shared secret is invalid
	//	@return ERR_SERVER_UNREACHABLE            TACACS+ server could not be contacted
	//	@return ERR_AUTHENTICATION_FAILED         user could not be authenticated
	//	@return ERR_NO_ROLES                      no roles are defined for the user
	//	@return ERR_NO_KNOWN_ROLES                no known roles are defined for the user
	TestTacPlusServer(ctx context.Context, username string, password string, settings ServerSettings) (int32, error)
}

// TACACS+ authentication type
type AuthenType int

const (
	ASCII  AuthenType = iota // Plain text authentication
	PAP                      // PAP authentication
	CHAP                     // CHAP authentication
	MSCHAP                   // MSCHAP authentication
)

// Server settings
type ServerSettings struct {
	Server            string     // TACACS+ server name or IP address
	Port              int32      // TACACS+ server TCP port
	TimeoutSeconds    int32      // max time from connecting until session completion
	Retries           int32      // max number of allowed retries
	SharedSecret      string     // Shared secret between Xerus device and TACACs+ server
	AuthenType        AuthenType // Authentication type
	DisableAccounting bool       // true to disable accounting, false to enable accounting
}
