// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package internalbeeper was generated by IDLC from InternalBeeper.idl.
// It is part of module hmi.
// The remaining comment is for module hmi.
//
// Human Machine Interface
package internalbeeper

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40211/event/userevent"
	"github.com/arminguenther/xeruspower-go/v40211/idl"
	"github.com/arminguenther/xeruspower-go/v40211/idl/event"
)

// Internal beeper interface
type InternalBeeper interface {
	idl.Object

	// Mute beeper, turn off all internal alarm notifications.
	//
	//	@param mute  true to mute beeper, false for normal mode
	Mute(ctx context.Context, muted bool) error

	// Check whether beeper is currently muted
	//
	//	@return true if muted, false if not
	IsMuted(ctx context.Context) (bool, error)

	// Activate the beeper for a given time.
	//
	//	@param activate Whether to turn on or off the beeper
	//	@param reason   Description of the reason to turn on the beeper
	//	                (only valid whtn turning on the beeper)
	//	@param timeout  Activation timeout in milliseconds
	//	                (only valid when turning on the beeper, 0 = infinite activation)
	Activate(ctx context.Context, on bool, reason string, timeout int32) error

	// Retrieve the current beeper activation state.
	//
	//	@param reason           Return value for activation reason if the beeper
	//	                        is currently active
	//	@param mutedTemporarily Whether the beeper is currently muted due to a call
	//	                        to {@link muteCurrentActivation}.
	//	@return The current beeper state
	GetState(ctx context.Context) (ret State, reason string, mutedTemporarily bool, err error)

	// Mute the beeper for the current activation.
	//
	// If the beeper is currently on, it will be turned off until another call to
	// the {@link activate} method or until a new internal notification happens.
	MuteCurrentActivation(ctx context.Context) error
}

// Activation state
type State int

const (
	OFF             State = iota // Beeper is currently off
	ON_NOTIFICATION              // Beeper is currently active due to an internal alarm notification
	ON_ACTIVATION                // Beeper is currently active due to an external activation
)

// Event: The beeper has been muted or unmuted
type MuteChangedEvent interface {
	userevent.UserEvent
	Muted() bool
	isMuteChangedEvent()
}

// Event: The beeper activation status has changed
type StateChangedEvent interface {
	event.Event
	State() State   // The current beeper state
	Reason() string // Activation reason
	MutedTemporarily() bool
	isStateChangedEvent()
}
