// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package debuglog was generated by IDLC from DebugLog.idl.
// It is part of module logging.
// The remaining comment is for module logging.
//
// Device Logging
package debuglog

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40413/idl"
	"github.com/arminguenther/xeruspower-go/v40413/logging/log"
)

// Device debug log interface
type DebugLog interface {
	idl.Object

	// Clear the debug log.
	Clear(ctx context.Context) error

	// Get info about the debug log.
	//
	//	@return log info
	GetInfo(ctx context.Context) (log.Info, error)

	// Fetch a chunk from the debug log.
	//
	// For details regarding the behavior of this method refer to the description
	// of the logging module in Log.idl.
	//
	//	@param refId      First log id to fetch
	//	@param count      Number of entries to fetch
	//	@param direction  Range direction
	//
	//	@return log chunk
	GetChunk(ctx context.Context, refId int32, count int32, direction log.RangeDirection) (log.Chunk, error)
}
