// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package services was generated by IDLC from Services.idl.
// It is part of module net.
// The remaining comment is for module net.
//
// Network services configuration
package services

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40211/idl"
)

// Network service settings
type ServiceSettings struct {
	Service string // Service name
	Enable  bool   // true if the service is enabled
	Port    int32  // Service TCP port
}

const ERR_INVALID_PARAMS int32 = 1 // Invalid parameters

// Network services configuration interface
type Services interface {
	idl.Object

	// Retrieve the network services settings.
	//
	//	@param servicesSettings  List of all network services settings
	GetSettings(ctx context.Context) (servicesSettings []ServiceSettings, err error)

	// Change the network services settings.
	//
	// This call changes the settings of one or more network services
	// identified by name. Other services are not affected. The resulting
	// configuration of all enabled services must be consistent, i.e.
	// there must be not port collisions.
	//
	//	@param servicesSettings  List of network services settings to be changed
	//
	//	@return 0 if OK
	//	@return 1 if any parameters were invalid
	SetSettings(ctx context.Context, servicesSettings []ServiceSettings) (int32, error)
}
