// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package powermeter was generated by IDLC from PowerMeter.idl.
// It is part of module pdumodel.
// The remaining comment is for module pdumodel.
//
// PDU Model
package powermeter

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40411/event/userevent"
	"github.com/arminguenther/xeruspower-go/v40411/idl"
	"github.com/arminguenther/xeruspower-go/v40411/pdumodel/controller"
	"github.com/arminguenther/xeruspower-go/v40411/pdumodel/pole"
	"github.com/arminguenther/xeruspower-go/v40411/sensors/numericsensor"
	"github.com/arminguenther/xeruspower-go/v40411/sensors/statesensor"
)

const (
	ERR_INVALID_PARAM      int32 = 1 // Invalid parameters
	ERR_MODBUS_UNIT_IN_USE int32 = 2 // Modbus unit address is already in use
)

// A three-phase power meter (PMC).
type PowerMeter interface {
	idl.Object

	// Retrieve the power meter configuration.
	//
	//	@return Power meter configuration
	GetConfig(ctx context.Context) (Config, error)

	// Get the power meter sensors.
	//
	//	@return Power meter sensors
	GetSensors(ctx context.Context) (Sensors, error)

	// Get the list of power meter poles.
	//
	//	@return List of power meter poles (A, B, C, N, PE)
	GetPoles(ctx context.Context) ([]pole.Pole, error)

	// Get the list of sub controllers for this power meter
	//
	//	@return List of controllers
	GetControllers(ctx context.Context) ([]controller.Controller, error)

	// Retrieve the power meter settings.
	//
	//	@return Power meter settings
	GetSettings(ctx context.Context) (Settings, error)

	// Change the power meter settings.
	//
	//	@param settings  New settings
	//
	//	@return 0 if OK
	//	@return 1 if any parameters are invalid
	//	@return 2 if the Modbus unit address is already in use
	SetSettings(ctx context.Context, settings Settings) (int32, error)

	// Retrieve the energy LED pulse settings.
	//
	//	@return Energy LED pulse settings
	GetEnergyPulseSettings(ctx context.Context) (EnergyPulseSettings, error)

	// Change the energy LED pulse settings.
	//
	//	@param settings  New settings
	//
	//	@return 0 if OK
	//	@return 1 if any parameters are invalid
	SetEnergyPulseSettings(ctx context.Context, settings EnergyPulseSettings) (int32, error)
}

// Power meter type
type Type int

const (
	ONE_PHASE   Type = iota // Single-phase meter (A)
	SPLIT_PHASE             // Split-phase meter (A, B)
	THREE_PHASE             // Three-phase meter (A, B, C)
)

// Power meter configuration
type Config struct {
	PowerMeterId int32 // The meter board ID
	Type         Type  // Power meter type
}

// Power meter sensors
type Sensors struct {
	Voltage                 numericsensor.NumericSensor // RMS voltage sensor
	LineFrequency           numericsensor.NumericSensor // Line AC frequency sensor
	Current                 numericsensor.NumericSensor // RMS current sensor
	ActivePower             numericsensor.NumericSensor // Active power sensor
	ReactivePower           numericsensor.NumericSensor // Reactive power sensor
	ApparentPower           numericsensor.NumericSensor // Apparent power sensor
	PowerFactor             numericsensor.NumericSensor // Power factor sensor
	PhaseAngle              numericsensor.NumericSensor // Phase angle sensor
	DisplacementPowerFactor numericsensor.NumericSensor // Displacement power factor sensor
	ActiveEnergy            numericsensor.NumericSensor // Active energy sensor
	UnbalancedCurrent       numericsensor.NumericSensor // Current unbalance sensor
	CrestFactor             numericsensor.NumericSensor // Crest factor sensor
	ActivePowerDemand       numericsensor.NumericSensor // Active power demand
	PowerQuality            statesensor.StateSensor     // Power quality sensor
}

// Power meter settings
type Settings struct {
	Name              string // User-defined name
	CurrentRating     int32  // Current rating in Amps
	PhaseCtRating     int32  // Phase current transformer rating in Amps (0 for none)
	NeutralCtRating   int32  // Neutral current transformer rating in Amps (0 for none)
	EarthCtRating     int32  // P.E. current transformer rating in Amps (0 for none)
	ModbusUnitAddress int32  // Modbus unit address (1..255, 0 to disable Modbus for this meter)
}

// Event: Power meter settings have changed
type SettingsChangedEvent interface {
	userevent.UserEvent
	OldSettings() Settings // Settings before change
	NewSettings() Settings // Settings after change
	isSettingsChangedEvent()
}

// Energy LED pulse settings
type EnergyPulseSettings struct {
	PulseEnabled bool    // true to enable the energy LED pulse
	Poles        []int32 // Emit pulses for energy counted on any of these poles
	PulsesPerKWh int32   // Number of LED pulses per kWh of energy
}

// Event: Energy LED pulse settings have changed
type EnergyPulseSettingsChangedEvent interface {
	userevent.UserEvent
	OldSettings() EnergyPulseSettings
	NewSettings() EnergyPulseSettings
	isEnergyPulseSettingsChangedEvent()
}
