// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Code generated by "stringer -output=enum_strings.go -type=DeviceManagerDeviceFirmwareUpdateState,DeviceManagerZCoordMode"; DO NOT EDIT.

package peripheraldevicemanager

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UPDATE_STARTED-0]
	_ = x[UPDATE_SUCCESSFUL-1]
	_ = x[UPDATE_FAILED-2]
}

const _DeviceManagerDeviceFirmwareUpdateState_name = "UPDATE_STARTEDUPDATE_SUCCESSFULUPDATE_FAILED"

var _DeviceManagerDeviceFirmwareUpdateState_index = [...]uint8{0, 14, 31, 44}

func (i DeviceManagerDeviceFirmwareUpdateState) String() string {
	if i < 0 || i >= DeviceManagerDeviceFirmwareUpdateState(len(_DeviceManagerDeviceFirmwareUpdateState_index)-1) {
		return "DeviceManagerDeviceFirmwareUpdateState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DeviceManagerDeviceFirmwareUpdateState_name[_DeviceManagerDeviceFirmwareUpdateState_index[i]:_DeviceManagerDeviceFirmwareUpdateState_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RACKUNITS-0]
	_ = x[FREEFORM-1]
}

const _DeviceManagerZCoordMode_name = "RACKUNITSFREEFORM"

var _DeviceManagerZCoordMode_index = [...]uint8{0, 9, 17}

func (i DeviceManagerZCoordMode) String() string {
	if i < 0 || i >= DeviceManagerZCoordMode(len(_DeviceManagerZCoordMode_index)-1) {
		return "DeviceManagerZCoordMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DeviceManagerZCoordMode_name[_DeviceManagerZCoordMode_index[i]:_DeviceManagerZCoordMode_index[i+1]]
}
