// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package peripheraldeviceslot was generated by IDLC from PeripheralDeviceSlot.idl.
// It is part of module peripheral.
// The remaining comment is for module peripheral.
//
// Peripheral Devices
package peripheraldeviceslot

import (
	"context"

	"github.com/arminguenther/xeruspower-go/event/userevent"
	"github.com/arminguenther/xeruspower-go/idl"
	"github.com/arminguenther/xeruspower-go/idl/event"
	"github.com/arminguenther/xeruspower-go/peripheral/poselement"
	"github.com/arminguenther/xeruspower-go/sensors/sensor"
)

// peripheral device identification
type DeviceID struct {
	Serial     string          // Serial number
	Type       sensor.TypeSpec // device's type spec
	IsActuator bool            // true if device is an actuator
	Channel    int32           // Channel number
}

// peripheral device position based address
type Address struct {
	Position   []poselement.PosElement // Position within 1-wire topo
	Type       sensor.TypeSpec         // device's type spec
	IsActuator bool                    // true if device is an actuator
	Channel    int32                   // Channel number
}

// A peripheral device is the collection of
//   - device identification
//   - device position
//   - a flag indicating actuator type
//   - device reference
type Device interface {
	idl.ValueObject
	DeviceID() DeviceID                // device identification
	Position() []poselement.PosElement // Position within 1-wire topo
	PackageClass() string              // physical package identifier
	Device() sensor.Sensor             // device reference
	isDevice()
}

const (
	ERR_INVALID_PARAMS int32 = 1  // Invalid parameters
	ERR_NOT_SUPPORTED  int32 = 2  // Operation not supported
	CHANNEL_INVALID    int32 = -1 // Device has no channels
)

// Peripheral Device Slot
type DeviceSlot interface {
	idl.Object

	// Returns the actual device reference.
	// The reference becomes invalid due to assign/unassign method
	// call. This conditions is also flagged by EVT_KEY_DEVICE_CHANGED
	// event
	GetDevice(ctx context.Context) (Device, error)

	// Associate this slot with a given (old or detected new) peripheral device.
	//
	//	@param devid peripheral device identification
	//
	//	@return 0                    if OK
	//	@return ERR_INVALID_PARAMS   if devid is unknown or invalid
	Assign(ctx context.Context, devid DeviceID) (int32, error)

	// Associate this slot with an addressable (new) peripheral device.
	//
	//	@param address peripheral device address
	//
	//	@return 0                    if OK
	//	@return ERR_INVALID_PARAMS   if address is invalid
	AssignAddress(ctx context.Context, packageClass string, address Address) (int32, error)

	// Break the association for this slot.
	//
	//	@return 0                    if OK
	//	@return ERR_NOT_SUPPORTED    if operation is not supported
	//	                             this is the case for sensors with
	//	                             complete position information
	Unassign(ctx context.Context) (int32, error)

	// Retrieve the user-defined settings.
	//
	//	@return Slot settings
	GetSettings(ctx context.Context) (DeviceSlotSettings, error)

	// Change the slot settings.
	//
	//	@param settings  New slot settings
	//
	//	@return 0                    if OK
	//	@return ERR_INVALID_PARAMS   if any parameters are invalid
	SetSettings(ctx context.Context, settings DeviceSlotSettings) (int32, error)
}

// user writeable location
type DeviceSlotLocation struct {
	X string // X coordinate
	Y string // Y coordinate
	Z string // Z coordinate (semantics depends on ZCoordMode)
}

// user configurable slot attributes
type DeviceSlotSettings struct {
	Name                 string             // User-defined name
	Description          string             // User-defined description
	Location             DeviceSlotLocation // user-defined device location
	UseDefaultThresholds bool               // use default thresholds
	Properties           map[string]string  // sensor specific settings
}

// Event: The device attached to this slot has changed
type DeviceSlotDeviceChangedEvent interface {
	event.Event
	OldDevice() Device // Device before change
	NewDevice() Device // Device after change
	isDeviceSlotDeviceChangedEvent()
}

// Event: The slot settings have been changed
type DeviceSlotSettingsChangedEvent interface {
	userevent.UserEvent
	OldSettings() DeviceSlotSettings // Settings before change
	NewSettings() DeviceSlotSettings // Settings after change
	isDeviceSlotSettingsChangedEvent()
}
