// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package production was generated by IDLC from Production.idl.
// It is part of module production.
// The remaining comment is for module production.
//
// Methods used during production
package production

import (
	"context"

	"github.com/arminguenther/xeruspower-go/idl"
)

// Methods used during production
type Production interface {
	idl.Object

	// Enter factory configuration mode.
	//
	// This mode unlocks several features which should only be available
	// during production, e.g. the RS485 address assignment or sensor
	// calibration. Factory configuration mode will be enabled until
	// the next reboot or until leaveFactoryConfigMode is called.
	//
	//	@param password  Password required to enter factory config mdoe.
	//
	//	@return 0 if OK
	//	@return 1 if the password is wrong
	EnterFactoryConfigMode(ctx context.Context, password string) (int32, error)

	// Leave factory configuration mode.
	LeaveFactoryConfigMode(ctx context.Context) error

	// Check whether device is in factory configuration mode.
	//
	//	@return true if factory configuration mode is enabled
	IsFactoryConfigModeEnabled(ctx context.Context) (bool, error)

	// Instruct RS485 controllers to choose random bus addresses.
	//
	// This command is only allowed in factory configuration mode.
	//
	//	@param deviceId    Device ID of target controllers
	//	@param rangeStart  Start of address range
	//	@param rangeEnd    End of address range
	//
	//	@return 0 if OK
	//	@return 1 if any parameter is invalid
	//	@return 2 if the device is not in factory configuration mode
	AssignRandomRs485Addresses(ctx context.Context, deviceId byte, rangeStart byte, rangeEnd byte) (int32, error)
}
