// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package modbusgatewaymgr was generated by IDLC from ModbusGatewayMgr.idl.
// It is part of module modbus.
// The remaining comment is for module modbus.
package modbusgatewaymgr

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40411/idl"
)

const (
	NO_ERROR           int32 = 0 // No error
	ERR_INVALID_PARAMS int32 = 1 // Invalid parameters
)

type GatewayMgr interface {
	idl.Object

	// Get the modbus gateway settings
	//
	//	@return settings
	GetSettings(ctx context.Context) (GatewayMgrSettings, error)

	// Set the modbus gateway settings
	//
	//	@param   settings
	//
	//	@return 0                  if OK
	//	@return ERR_INVALID_PARAMS if any parameters are invalid
	SetSettings(ctx context.Context, settings GatewayMgrSettings) (int32, error)
}

// Modbus RTU settings
type GatewayMgrRtuSettings struct {
	DefaultAddr byte  // Modbus serial device default address
	Speed       int32 // Modbus serial line speed
	Parity      byte  // Modbus serial line parity (N/E/O)
}

// Modbus gateway settings (extending modb PortMux service)
type GatewayMgrSettings struct {
	Rtu GatewayMgrRtuSettings // Modbus RTU settings
}
