// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Code generated by "stringer -output=enum_strings.go -type=LoggerBackupState"; DO NOT EDIT.

package sensorlogger

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[STOPPED-0]
	_ = x[RUNNING-1]
	_ = x[SUSPENDED-2]
}

const _LoggerBackupState_name = "STOPPEDRUNNINGSUSPENDED"

var _LoggerBackupState_index = [...]uint8{0, 7, 14, 23}

func (i LoggerBackupState) String() string {
	if i < 0 || i >= LoggerBackupState(len(_LoggerBackupState_index)-1) {
		return "LoggerBackupState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LoggerBackupState_name[_LoggerBackupState_index[i]:_LoggerBackupState_index[i+1]]
}
