// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package sensorlogger was generated by IDLC from SensorLogger.idl.
// It is part of module sensors.
// The remaining comment is for module sensors.
//
// Sensors Model
package sensorlogger

import (
	"context"
	"time"

	"github.com/arminguenther/xeruspower-go/v40211/event/userevent"
	"github.com/arminguenther/xeruspower-go/v40211/idl"
	"github.com/arminguenther/xeruspower-go/v40211/idl/event"
	"github.com/arminguenther/xeruspower-go/v40211/peripheral/peripheraldeviceslot"
	"github.com/arminguenther/xeruspower-go/v40211/sensors/sensor"
)

// Sensor state in log record
const (
	STATE_UNAVAILABLE            int32 = 0  // Unavailable
	STATE_OPEN                   int32 = 1  // Circuit breaker open
	STATE_CLOSE                  int32 = 2  // Circuit breaker closed
	STATE_BELOW_LOWER_CRITICAL   int32 = 3  // Numeric sensor below lower critical threshold
	STATE_BELOW_LOWER_WARNING    int32 = 4  // Numeric sensor below lower warning threshold
	STATE_NORMAL                 int32 = 5  // Numeric sensor in normal range; normal operation
	STATE_ABOVE_UPPER_WARNING    int32 = 6  // Numeric sensor above upper warning threshold
	STATE_ABOVE_UPPER_CRITICAL   int32 = 7  // Numeric sensor above upper critical threshold
	STATE_ON                     int32 = 8  // Power state on
	STATE_OFF                    int32 = 9  // Power state off
	STATE_ALARMED                int32 = 10 // Alarmed
	STATE_OK                     int32 = 11 // OK
	STATE_MARGINAL               int32 = 12 // Marginal
	STATE_FAIL                   int32 = 13 // Fail
	STATE_YES                    int32 = 14 // Yes
	STATE_NO                     int32 = 15 // No
	STATE_STANDBY                int32 = 16 // Standby operation
	STATE_ONE                    int32 = 17 // First source active
	STATE_TWO                    int32 = 18 // Second source active
	STATE_IN_SYNC                int32 = 19 // Phases are in sync
	STATE_OUT_OF_SYNC            int32 = 20 // Phases are out of sync
	STATE_FAULT                  int32 = 21 // Fault
	STATE_SELF_TEST              int32 = 22 // Sensor is currently testing itself
	STATE_I1_OPEN_FAULT          int32 = 23 // Inlet 1 switch open fault
	STATE_I1_SHORT_FAULT         int32 = 24 // Inlet 1 switch short fault
	STATE_I2_OPEN_FAULT          int32 = 25 // Inlet 2 switch open fault
	STATE_I2_SHORT_FAULT         int32 = 26 // Inlet 2 switch short fault
	STATE_WARNING                int32 = 27 // Warning
	STATE_CRITICAL               int32 = 28 // Critical
	STATE_NON_REDUNDANT          int32 = 29 // Non-redundant operation
	STATE_INACTIVE               int32 = 30 // Bypass inactive
	STATE_I1_SELECTED            int32 = 31 // Inlet 1 selected
	STATE_I2_SELECTED            int32 = 32 // Inlet 2 selected
	STATE_I1_SELECTED_AND_ACTIVE int32 = 33 // Inlet 1 selected and active
	STATE_I2_SELECTED_AND_ACTIVE int32 = 34 // Inlet 2 selected and active
)

// Sensor logger interface.
//
// The sensor log stores a fixed number of log records for each
// enabled sensor. Log records hold the minimum, maximum and average
// reading of all samples within the period as well as the most
// critical state.
//
// Record IDs start at 1 and grow continuously without wrap-around. To
// avoid race conditions it is allowed to request records that are no
// longer available, i.e. have rotated out of the log. Unavailable
// records come back empty (available = false, timestamp = 0). It is
// not OK to read past newestRecId.
//
// Log record periods are synchronized with the system time, so all
// devices with the same log settings and proper time configuration
// move to a new record simultaneously.
type Logger interface {
	idl.Object

	// Retrieve the sensor logger info.
	//
	//	@return Sensor logger info
	GetInfo(ctx context.Context) (LoggerInfo, error)

	// Retrieve the sensor logger settings.
	//
	//	@return Sensor logger settings
	GetSettings(ctx context.Context) (LoggerSettings, error)

	// Change the sensor logger settings.
	//
	//	@param settings  New settings
	//
	//	@return 0 if OK
	//	@return 1 if any parameters are invalid
	SetSettings(ctx context.Context, settings LoggerSettings) (int32, error)

	// Retrieve a set of log record timestamps.
	//
	//	@param timestamps  Result: Log record timestamps
	//	@param recid       First record id
	//	@param count       Number of records
	//
	//	@return 0 if OK
	//	@return 1 if any record id is invalid
	GetTimeStamps(ctx context.Context, recid int32, count int32) (ret int32, timestamps []time.Time, err error)

	// Retrieve log records for a given sensor.
	//
	//	@param recs    Result: Sensor log records
	//	@param sensor  Sensor reference
	//	@param recid   First record id
	//	@param count   Number of records
	//
	//	@return 0 if OK
	//	@return 1 if any record id is invalid
	GetSensorRecords(ctx context.Context, sensor sensor.Sensor, recid int32, count int32) (ret int32, recs []LoggerRecord, err error)

	// Retrieve log records for an peripheral device slot.
	//
	//	@param recs       Result: Sensor log records
	//	@param slot       Peripheral device slot reference
	//	@param recid      First record id
	//	@param count      Number of records
	//
	//	@return 0 if OK
	//	@return 1 if any record id is invalid
	GetPeripheralDeviceRecords(ctx context.Context, slot peripheraldeviceslot.DeviceSlot, recid int32, count int32) (ret int32, recs []LoggerRecord, err error)

	// Retrieve log records with timestamps for a given sensor.
	//
	//	@param recs    Result: Sensor log records
	//	@param sensor  Sensor reference
	//	@param recid   First record id
	//	@param count   Number of records
	//
	//	@return 0 if OK
	//	@return 1 if any record id is invalid
	GetSensorTimedRecords(ctx context.Context, sensor sensor.Sensor, recid int32, count int32) (ret int32, recs []LoggerTimedRecord, err error)

	// Retrieve log records with timestamps for an peripheral device slot.
	//
	//	@param recs       Result: Sensor log records
	//	@param slot       Peripheral device slot reference
	//	@param recid      First record id
	//	@param count      Number of records
	//
	//	@return 0 if OK
	//	@return 1 if any record id is invalid
	GetPeripheralDeviceTimedRecords(ctx context.Context, slot peripheraldeviceslot.DeviceSlot, recid int32, count int32) (ret int32, recs []LoggerTimedRecord, err error)

	// Retrieve the set of logged sensors.
	//
	//	@return Set of logged sensors
	GetLoggedSensors(ctx context.Context) (LoggerSensorSet, error)

	// Change the set of logged sensors.
	//
	//	@param sensors  New set of sensors
	//
	//	@return 0 if OK
	//	@return 1 if any sensor in the list is unknown
	SetLoggedSensors(ctx context.Context, sensors LoggerSensorSet) (int32, error)

	// Enable logging for one or more sensors or peripheral device slots.
	//
	// Sensors in the list that are already logged are ignored. Logged
	// sensors not in the list remain enabled.
	//
	//	@param sensors  Sensors and slots to be logged
	//
	//	@return 0 if OK
	//	@return 1 if any sensor in the list is unknown
	EnableSensors(ctx context.Context, sensors LoggerSensorSet) (int32, error)

	// Disable logging for one or more sensors or peripheral device slots.
	//
	// Sensors in the list that are not logged are ignored. Logged sensors
	// not in the list remain enabled.
	//
	//	@param sensors  Sensors and slots to be disabled
	//
	//	@return 0 if OK
	//	@return 1 if any sensor in the list is unknown
	DisableSensors(ctx context.Context, sensors LoggerSensorSet) (int32, error)

	// Check if logging is enabled for a given sensor.
	//
	//	@param sensor  Sensor to be checked
	//
	//	@return true if sensor is logged, false otherwise
	IsSensorEnabled(ctx context.Context, sensor sensor.Sensor) (bool, error)

	// Check if logging is enabled for a given peripheral device slot.
	//
	//	@param sensor  Peripheral device slot to be checked
	//
	//	@return true if slot is logged, false otherwise
	IsSlotEnabled(ctx context.Context, slot peripheraldeviceslot.DeviceSlot) (bool, error)

	// Enable logging for all PDU sensors.
	EnableAllSensors(ctx context.Context) error

	// Disable logging for all PDU sensors.
	DisableAllSensors(ctx context.Context) error

	// Get the time of the last sensor set modification.
	//
	// This can be used by clients which keep a cached copy of the sensor
	// set to determine whether that copy is still up-to-date.
	//
	//	@return Sensor set time stamp (UNIX timestamp, UTC)
	GetSensorSetTimestamp(ctx context.Context) (time.Time, error)

	// Get one full log row.
	//
	//	@param row    Result: Log row
	//	@param recid  Record id
	//
	//	@return 0 if OK
	//	@return 1 if the record id is invalid
	GetLogRow(ctx context.Context, recid int32) (ret int32, row LoggerLogRow, err error)
}

// Sensor logger info
type LoggerInfo struct {
	SamplePeriod int32 // Sample interval in milliseconds
	// Maximum supported number of log records (number of
	// logged sensors multiplied by log capacity)
	MaxTotalRecords int32
	// Effective log capacity; may be lower than the
	// setting to meet the maxTotalRecords limit.
	EffectiveCapacity int32
	OldestRecId       int32 // ID of oldest record in buffer (0 if empty)
	NewestRecId       int32 // ID of newest record in buffer (0 if empty)
}

// Sensor logger settings
type LoggerSettings struct {
	IsEnabled        bool  // true if sensor logging is enabled
	SamplesPerRecord int32 // Number of samples per log record
	LogCapacity      int32 // Maximum number of log records in buffer
	BackupEnabled    bool  // true if backup to external storage is enabled
}

// Set of logged sensors
type LoggerSensorSet struct {
	Sensors []sensor.Sensor                   // List of numeric or state sensors
	Slots   []peripheraldeviceslot.DeviceSlot // List of peripheral device slots
}

// Event: Sensor logger info has changed
type LoggerInfoChangedEvent interface {
	event.Event
	OldInfo() LoggerInfo // Info before change
	NewInfo() LoggerInfo // Info after change
	isLoggerInfoChangedEvent()
}

// Event: Sensor logger settings have been changed
type LoggerSettingsChangedEvent interface {
	userevent.UserEvent
	OldSettings() LoggerSettings // Settings before change
	NewSettings() LoggerSettings // Settings after change
	isLoggerSettingsChangedEvent()
}

// Event: Set of logged sensors has been changed
type LoggerLoggedSensorsChangedEvent interface {
	userevent.UserEvent
	OldSensors() LoggerSensorSet // Sensor set before change
	NewSensors() LoggerSensorSet // Sensor set after change
	isLoggerLoggedSensorsChangedEvent()
}

// Sensor log record
type LoggerRecord struct {
	Available         bool    // Sensor was available for at least one sample
	TakenValidSamples int32   // Number of samples with a valid reading/state
	State             int32   // Sensor state
	MinValue          float64 // Minimum sensor reading
	AvgValue          float64 // Average sensor reading
	MaxValue          float64 // Maximum sensor reading
}

// Sensor log record with timestamp
type LoggerTimedRecord struct {
	Timestamp time.Time    // UNIX timestamp (UTC)
	Record    LoggerRecord // Log record
}

// One full log row
type LoggerLogRow struct {
	SensorSetTimestamp      time.Time      // Time of last sensor set modification (UNIX timestamp, UTC)
	Timestamp               time.Time      // Log row time stamp (UNIX timestamp, UTC)
	SensorRecords           []LoggerRecord // Sensor records; same order as in SensorSet::sensors
	PeripheralDeviceRecords []LoggerRecord // Peripheral device records; same order as in SensorSet::slots
}
