// Code generated by "stringer -output=enum_strings.go -type=SimSecurityStatus"; DO NOT EDIT.

package gsmmodem

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UNLOCKED-0]
	_ = x[WAITFORPIN-1]
	_ = x[WAITFORPUK-2]
	_ = x[UNKNOWN-3]
}

const _SimSecurityStatus_name = "UNLOCKEDWAITFORPINWAITFORPUKUNKNOWN"

var _SimSecurityStatus_index = [...]uint8{0, 8, 18, 28, 35}

func (i SimSecurityStatus) String() string {
	if i < 0 || i >= SimSecurityStatus(len(_SimSecurityStatus_index)-1) {
		return "SimSecurityStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SimSecurityStatus_name[_SimSecurityStatus_index[i]:_SimSecurityStatus_index[i+1]]
}
