// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package gsmmodem was generated by IDLC from GsmModem.idl.
// It is part of module serial.
// The remaining comment is for module serial.
//
// Serial Ports
package gsmmodem

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40000/idl"
	"github.com/arminguenther/xeruspower-go/v40000/idl/event"
)

// Error codes
const (
	SUCCESS                   int32 = 0 // No error
	ERR_INVALID_VALUE         int32 = 1 // Invalid argument
	ERR_WRONG_PIN             int32 = 2 // The PIN is incorrect or missing
	ERR_SMS_SEND_FAILED       int32 = 3 // SMS delivery failed
	ERR_COMMUNICATION_FAILURE int32 = 4 // Communication with the modem failed
	ERR_SIM_LOCKED            int32 = 5 // The SIM card is locked and waits for the PUK
	ERR_WRONG_SIM_STATUS      int32 = 6 // The SIM card doesn't wait for the PUK
	ERR_WRONG_PUK             int32 = 7 // The PUK is incorrect or missing
	ERR_SIM_PROBLEM           int32 = 8 // There is a problem with the SIM or service subscription
)

// Interface for communication with a GSM modem attached
// to a serial port
type GsmModem interface {
	idl.Object

	// Get modem settings
	//
	//	@return -- Current modem settings
	GetSettings(ctx context.Context) (Settings, error)

	// Set modem settings
	//
	//	@param settings -- New settings
	//
	//	@return SUCCESS           -- on success
	//	@return ERR_INVALID_VALUE -- if any passed value was invalid
	SetSettings(ctx context.Context, settings Settings) (int32, error)

	// Send out a SMS message
	//
	//	@param recipient -- Phone number of the message recipient in ITU-T E.164 format
	//	@param text      -- Message text (will be sent in multiple messages if longer than 160 characters)
	//
	//	@return SUCCESS                   -- on success
	//	@return ERR_WRONG_PIN             -- if the PIN currently stored in the settings is incorrect or missing
	//	@return ERR_SMS_SEND_FAILED       -- if the delivery of the SMS to the network failed
	//	@return ERR_SIM_LOCKED            -- if the SIM card is locked and waits for the PUK
	//	@return ERR_COMMUNICATION_FAILURE -- if communication with the modem failed
	SendSms(ctx context.Context, recipient string, text string) (int32, error)

	// Send out a test SMS message
	//
	// The message will be sent to the selected recipient with the text 'SMS Test'.
	//
	//	@param recipient    -- Phone number of the message recipient in ITU-T E.164 format
	//	@param testSettings -- Modem settings to be used temporarily during testing
	//
	//	@return SUCCESS                   -- on success
	//	@return ERR_WRONG_PIN             -- if the PIN currently stored in the settings is incorrect or missing
	//	@return ERR_SMS_SEND_FAILED       -- if the delivery of the SMS to the network failed
	//	@return ERR_SIM_LOCKED            -- if the SIM card is locked and waits for the PUK
	//	@return ERR_COMMUNICATION_FAILURE -- if communication with the modem failed
	SendTestSms(ctx context.Context, recipient string, testSettings Settings) (int32, error)

	// Retrieve low-level information about the modem and the SIM card.
	//
	//	@param info         -- structure holding the returned information
	//
	//	@return SUCCESS                   -- on success
	//	@return ERR_WRONG_PIN             -- if the used PIN is incorrect or missing
	//	@return ERR_SIM_LOCKED            -- if the SIM card is locked and waits for the PUK
	//	@return ERR_COMMUNICATION_FAILURE -- if communication with the modem failed
	GetInformation(ctx context.Context) (ret int32, info Information, err error)

	// Retrieve low-level information about the modem and the SIM card.
	//
	//	      Like getInformation, but allows providing a PIN not stored in the settings
	//
	//	@param pin   -- PIN to use for authentication
	//	@param info  -- structure holding the returned information
	//
	//	@return SUCCESS                   -- on success
	//	@return ERR_WRONG_PIN             -- if the used PIN is incorrect or missing
	//	@return ERR_SIM_LOCKED            -- if the SIM card is locked and waits for the PUK
	//	@return ERR_COMMUNICATION_FAILURE -- if communication with the modem failed
	GetInformationWithPin(ctx context.Context, pin string) (ret int32, info Information, err error)

	// Retrieve security status of the SIM card.
	//
	//	@param simStatus -- SIM card security status
	//
	//	@return SUCCESS                   -- on success
	//	@return ERR_COMMUNICATION_FAILURE -- if communication with the modem failed
	GetSimSecurityStatus(ctx context.Context) (ret int32, simStatus SimSecurityStatus, err error)

	// Unlock SIM card with PUK and set new PIN if the SIM card is in security status WAITFORPUK.
	//
	//	      The new PIN is automatically saved in the settings.
	//
	//	@param puk    -- PUK to use for authentication
	//	@param newPin -- new PIN to use for future authentication
	//
	//	@return SUCCESS                   -- on success
	//	@return ERR_WRONG_SIM_STATUS      -- if the SIM card doesn't wait for the PUK
	//	@return ERR_WRONG_PUK             -- if the used PUK is incorrect or missing
	//	@return ERR_COMMUNICATION_FAILURE -- if communication with the modem failed
	UnlockSimCard(ctx context.Context, puk string, newPin string) (int32, error)
}

// Possible security states the sim card can be in at a given time
type SimSecurityStatus int

const (
	UNLOCKED   SimSecurityStatus = iota // SIM card is unlocked
	WAITFORPIN                          // PIN must be entered to unlock the SIM card
	WAITFORPUK                          // PUK and new PIN must be entered to unlock the SIM card
	UNKNOWN                             // Unkown security status
)

// Structure for holding settings of the GSM modem
// and its SIM card
type Settings struct {
	Pin string // PIN of the SIM card
	// Custom SMS center number (in ITU-T E.164 format),
	// leave empty to use number stored on SIM card
	Smsc string
}

// Structure holding information about the modem and the SIM card.
// Any of the fields may be empty if the information can not be retrieved.
type Information struct {
	Imei                string // IMEI of the modem
	Imsi                string // IMSI of the SIM card
	Manufacturer        string // modem manufacturer string
	Model               string // modem model string
	Revision            string // modem revision string
	OwnNumber           string // own phone number in ITU-T E.164 format
	SimSmsc             string // SMS center number stored on SIM card
	NetworkName         string // Name of the currently used network (PLMN)
	ServiceProviderName string // Name of the service provider (SPN)
	// reception level in dBm
	// 0 means unknown, -1 means no reception
	ReceptionLevel int32
}

// Sim card security status changed event
type SimSecurityStatusChangedEvent interface {
	event.Event
	NewSimStatus() SimSecurityStatus // new SIM card security status
	isSimSecurityStatusChangedEvent()
}

// Sim pin updated event
type SimPinUpdatedEvent interface {
	event.Event
	NewPin() string // new PIN for SIM card after Unlock
	isSimPinUpdatedEvent()
}
