// Code generated by "stringer -output=enum_strings.go -type=Orientation"; DO NOT EDIT.

package unit

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NORMAL-0]
	_ = x[FLIPPED-1]
}

const _Orientation_name = "NORMALFLIPPED"

var _Orientation_index = [...]uint8{0, 6, 13}

func (i Orientation) String() string {
	if i < 0 || i >= Orientation(len(_Orientation_index)-1) {
		return "Orientation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Orientation_name[_Orientation_index[i]:_Orientation_index[i+1]]
}
