// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Code generated by "stringer -output=enum_strings.go -type=DeviceInterfaceType,FlowControl,State,Parity"; DO NOT EDIT.

package dsamport

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DEV_IFTYPE_AUTO-0]
	_ = x[DEV_IFTYPE_DTE-1]
	_ = x[DEV_IFTYPE_DCE-2]
}

const _DeviceInterfaceType_name = "DEV_IFTYPE_AUTODEV_IFTYPE_DTEDEV_IFTYPE_DCE"

var _DeviceInterfaceType_index = [...]uint8{0, 15, 29, 43}

func (i DeviceInterfaceType) String() string {
	if i < 0 || i >= DeviceInterfaceType(len(_DeviceInterfaceType_index)-1) {
		return "DeviceInterfaceType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DeviceInterfaceType_name[_DeviceInterfaceType_index[i]:_DeviceInterfaceType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FLOW_CTRL_NONE-0]
	_ = x[FLOW_CTRL_HARDWARE-1]
	_ = x[FLOW_CTRL_SOFTWARE-2]
}

const _FlowControl_name = "FLOW_CTRL_NONEFLOW_CTRL_HARDWAREFLOW_CTRL_SOFTWARE"

var _FlowControl_index = [...]uint8{0, 14, 32, 50}

func (i FlowControl) String() string {
	if i < 0 || i >= FlowControl(len(_FlowControl_index)-1) {
		return "FlowControl(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FlowControl_name[_FlowControl_index[i]:_FlowControl_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[STATE_AVAILABLE-0]
	_ = x[STATE_OCCUPIED-1]
	_ = x[STATE_BUSY-2]
}

const _State_name = "STATE_AVAILABLESTATE_OCCUPIEDSTATE_BUSY"

var _State_index = [...]uint8{0, 15, 29, 39}

func (i State) String() string {
	if i < 0 || i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PARITY_NONE-0]
	_ = x[PARITY_ODD-1]
	_ = x[PARITY_EVEN-2]
}

const _Parity_name = "PARITY_NONEPARITY_ODDPARITY_EVEN"

var _Parity_index = [...]uint8{0, 11, 21, 32}

func (i Parity) String() string {
	if i < 0 || i >= Parity(len(_Parity_index)-1) {
		return "Parity(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Parity_name[_Parity_index[i]:_Parity_index[i+1]]
}
