// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package datapushservice was generated by IDLC from DataPushService.idl.
// It is part of module event.
// The remaining comment is for module event.
//
// Event interface
package datapushservice

import (
	"context"
	"time"

	"github.com/arminguenther/xeruspower-go/v40412/event/userevent"
	"github.com/arminguenther/xeruspower-go/v40412/idl"
	"github.com/arminguenther/xeruspower-go/v40412/idl/event"
)

// Error codes
const (
	ERR_NO_SUCH_ID          int32 = 1 // No such ID
	ERR_INVALID_PARAMS      int32 = 2 // Invalid parameters
	ERR_MAX_ENTRIES_REACHED int32 = 3 // Maximum number of entries reached
)

// Data push service configuration interface
type DataPushService interface {
	idl.Object

	// Add a new entry.
	//
	//	@param entryId        Result: New entry id, automatically assigned
	//	@param entrySettings  New Model Push Entry settings
	//
	//	@return 0 if OK
	//	@return 2 if the settings are invalid
	//	@return 3 if the maximum number of entries is reached
	AddEntry(ctx context.Context, entrySettings EntrySettings) (ret int32, entryId int32, err error)

	// Modify an existing entry.
	//
	//	@param entryId        Entry id
	//	@param entrySettings  New Model Push Entry settings
	//
	//	@return 0 if OK
	//	@return 1 if the entry does not exist
	//	@return 2 if the settings are invalid
	ModifyEntry(ctx context.Context, entryId int32, entrySettings EntrySettings) (int32, error)

	// Delete an entry.
	//
	//	@param entryId  Entry id
	//
	//	@return 0 if OK
	//	@return 1 if the entry does not exist
	DeleteEntry(ctx context.Context, entryId int32) (int32, error)

	// Retrieve an entry.
	//
	//	@param entrySettings  Result: Model Push Entry settings
	//	@param entryId        Entry id
	//
	//	@return 0 if OK
	//	@return 1 if the entry does not exist
	GetEntry(ctx context.Context, entryId int32) (ret int32, entrySettings EntrySettings, err error)

	// Retrieve a list of entries.
	//
	//	@return List of Entry Settings
	ListEntries(ctx context.Context) (map[int32]EntrySettings, error)

	// Push data for one specified entry
	//
	//	@param entryId  Entry id
	//
	//	@return 0 if OK
	//	@return 1 if entry does not exist
	PushData(ctx context.Context, entryId int32) (int32, error)

	// Cancels an active data push
	//
	// If a data push is currently in process for the specified entry,
	// that push is canceled. If no push is in process, this method
	// is a no-op.
	//
	//	@param entryId  Entry id
	CancelDataPush(ctx context.Context, entryId int32) error

	// Retrieve an entry's status.
	//
	//	@param entryStatus  Result: Entry status
	//	@param entryId      Entry id
	//
	//	@return 0 if OK
	//	@return 1 if the entry does not exist
	GetEntryStatus(ctx context.Context, entryId int32) (ret int32, entryStatus EntryStatus, err error)
}

// Data Push Entry Types
type EntryType int

const (
	SENSORLIST EntryType = iota // Sensor values for a set of sensors
	SENSORLOG                   // Sensor log
	AMSLIST                     // Asset Management information for a set of AMS strips
	AMSLOG                      // Asset Management log
	AUDITLOG                    // Audit log
)

// Data Push Mqtt Settings
type MqttSettings struct {
	// Prefix added to all topics published to,
	// must end with level separator '/' if non-empty
	TopicPrefix string
}

// Data Push Entry Settings
type EntrySettings struct {
	Url                    string // Destination host
	AllowOffTimeRangeCerts bool   // allow expired and not yet valid TLS certificates
	CaCertChain            string // TLS CA certificate chain
	// true to use username/password authentication
	// (basic authentication in case of HTTP)
	UseAuth      bool
	Username     string       // Authentication username
	Password     string       // Password; write-only, empty to leave unchanged
	Type         EntryType    // Type of data
	Items        []string     // Included items (e.g. list of sensors) depending on type
	MqttSettings MqttSettings // MQTT specific settings
}

// Data Push Entry Status
type EntryStatus struct {
	Busy bool // true if the entry is currently being pushed
	// true if the entry is set to be pushed again
	// immediately after completion
	Rescheduled     bool
	LastAttemptTime time.Time // UNIX timestamp (UTC) of the last push attempt (0 = never)
	LastSuccessTime time.Time // UNIX timestamp (UTC) of last successful push (0 = never)
}

// Event: A new push destination has been added
type EntryAddedEvent interface {
	userevent.UserEvent
	EntryId() int32          // New entry id
	Settings() EntrySettings // New entry settings
	isEntryAddedEvent()
}

// Event: A configured push destination has been modified
type EntryModifiedEvent interface {
	userevent.UserEvent
	EntryId() int32             // Modified entry id
	OldSettings() EntrySettings // Settings before change
	NewSettings() EntrySettings // Settings after change
	isEntryModifiedEvent()
}

// Event: A configured push destination has been deleted
type EntryDeletedEvent interface {
	userevent.UserEvent
	EntryId() int32 // Deleted entry id
	isEntryDeletedEvent()
}

// Event: The status of a configured push destination has changed
type EntryStatusChangedEvent interface {
	event.Event
	EntryId() int32         // Entry id
	NewStatus() EntryStatus // New status
	isEntryStatusChangedEvent()
}
