// Code generated by "stringer -output=enum_strings.go -type=EntryType"; DO NOT EDIT.

package datapushservice

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SENSORLIST-0]
	_ = x[SENSORLOG-1]
	_ = x[AMSLIST-2]
	_ = x[AMSLOG-3]
	_ = x[AUDITLOG-4]
}

const _EntryType_name = "SENSORLISTSENSORLOGAMSLISTAMSLOGAUDITLOG"

var _EntryType_index = [...]uint8{0, 10, 19, 26, 32, 40}

func (i EntryType) String() string {
	if i < 0 || i >= EntryType(len(_EntryType_index)-1) {
		return "EntryType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EntryType_name[_EntryType_index[i]:_EntryType_index[i+1]]
}
