// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package transferswitchbypassstatesensor was generated by IDLC from TransferSwitchBypassStateSensor.idl.
// It is part of module pdumodel.
// The remaining comment is for module pdumodel.
//
// PDU Model
package transferswitchbypassstatesensor

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40412/sensors/statesensor"
)

const (
	STATE_ACTIVE_INLET_MASK  int32 = 0x7  // Active inlet, can be 0 (off), 1 or 2
	STATE_IS_BYPASS_SELECTED int32 = 0x8  // Whether the "bypass" position is selected
	STATE_FAULT              int32 = 0x10 // If set, communication to the bypass controller failed unexpectedly
)

// Overcurrent protector trip sensor interface
type TransferSwitchBypassStateSensor interface {
	statesensor.StateSensor

	// Acknowledge communication fault as expected
	//
	// If a bypass was present in the unit and later on removed, the STATE_FAULT bit will be set in the bypass state.
	// If removing the bypass happened deliberately, this method can be used to reset the state back to 'unavailable'
	// until the bypass is added to the unit again.
	AcknowledgeFault(ctx context.Context) error
}
