// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package corectrl was generated by IDLC from CoreCtrl.idl.
// It is part of module tfw.
// The remaining comment is for module tfw.
//
// Topology Framework Base
package corectrl

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40411/idl"
	"github.com/arminguenther/xeruspower-go/v40411/tfw/scannerctrl"
)

// Core control interface
type CoreCtrl interface {
	idl.Object

	// Get scanner by name.
	//
	//	@param name  Scanner name
	//
	//	@return Scanner reference
	GetScanner(ctx context.Context, name string) (scannerctrl.ScannerCtrl, error)

	// Start all scanner services.
	StartAllScanners(ctx context.Context) error

	// Stop all scanner services.
	StopAllScanners(ctx context.Context) error

	// Start all back-worker services.
	StartAllBackWorkers(ctx context.Context) error

	// Stop all back-worker services.
	StopAllBackWorkers(ctx context.Context) error
}
