// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Code generated by "stringer -output=enum_strings.go -type=FeedbackObjectFeedbackState,EncodingType,ModbusEndianness,Interpretation"; DO NOT EDIT.

package gatewaysensormanager

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UNSPECIFIED-0]
	_ = x[INTENTIONALLY_UNUSED-1]
	_ = x[FAILED_PRECONDITIONS_UNUSED-2]
	_ = x[FAILED-3]
	_ = x[GOOD-4]
}

const _FeedbackObjectFeedbackState_name = "UNSPECIFIEDINTENTIONALLY_UNUSEDFAILED_PRECONDITIONS_UNUSEDFAILEDGOOD"

var _FeedbackObjectFeedbackState_index = [...]uint8{0, 11, 31, 58, 64, 68}

func (i FeedbackObjectFeedbackState) String() string {
	if i < 0 || i >= FeedbackObjectFeedbackState(len(_FeedbackObjectFeedbackState_index)-1) {
		return "FeedbackObjectFeedbackState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FeedbackObjectFeedbackState_name[_FeedbackObjectFeedbackState_index[i]:_FeedbackObjectFeedbackState_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BOOL-0]
	_ = x[INT-1]
	_ = x[UINT-2]
	_ = x[IEEE754-3]
}

const _EncodingType_name = "BOOLINTUINTIEEE754"

var _EncodingType_index = [...]uint8{0, 4, 7, 11, 18}

func (i EncodingType) String() string {
	if i < 0 || i >= EncodingType(len(_EncodingType_index)-1) {
		return "EncodingType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EncodingType_name[_EncodingType_index[i]:_EncodingType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MODBUS_BIG_ENDIAN-0]
	_ = x[MODBUS_LITTLE_ENDIAN-1]
}

const _ModbusEndianness_name = "MODBUS_BIG_ENDIANMODBUS_LITTLE_ENDIAN"

var _ModbusEndianness_index = [...]uint8{0, 17, 37}

func (i ModbusEndianness) String() string {
	if i < 0 || i >= ModbusEndianness(len(_ModbusEndianness_index)-1) {
		return "ModbusEndianness(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ModbusEndianness_name[_ModbusEndianness_index[i]:_ModbusEndianness_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DEFAULT-0]
	_ = x[REJECT_DEVICE-1]
	_ = x[REJECT_SENSOR-2]
	_ = x[IGNORE-3]
	_ = x[UNAVAILABLE-4]
	_ = x[NUMERIC_INVALID-5]
	_ = x[STATE_ON-6]
	_ = x[STATE_OFF-7]
}

const _Interpretation_name = "DEFAULTREJECT_DEVICEREJECT_SENSORIGNOREUNAVAILABLENUMERIC_INVALIDSTATE_ONSTATE_OFF"

var _Interpretation_index = [...]uint8{0, 7, 20, 33, 39, 50, 65, 73, 82}

func (i Interpretation) String() string {
	if i < 0 || i >= Interpretation(len(_Interpretation_index)-1) {
		return "Interpretation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Interpretation_name[_Interpretation_index[i]:_Interpretation_index[i+1]]
}
