// Code generated by "stringer -output=enum_strings.go -type=SnmpAuthProtocol,FeedbackObjectFeedbackState,EncodingType,ModbusEndianness,SnmpPrivProtocol,Interpretation,SnmpSecurityLevel,AccessType"; DO NOT EDIT.

package gatewaysensormanager

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MD5-0]
	_ = x[SHA1-1]
	_ = x[SHA224-2]
	_ = x[SHA256-3]
	_ = x[SHA384-4]
	_ = x[SHA512-5]
}

const _SnmpAuthProtocol_name = "MD5SHA1SHA224SHA256SHA384SHA512"

var _SnmpAuthProtocol_index = [...]uint8{0, 3, 7, 13, 19, 25, 31}

func (i SnmpAuthProtocol) String() string {
	if i < 0 || i >= SnmpAuthProtocol(len(_SnmpAuthProtocol_index)-1) {
		return "SnmpAuthProtocol(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SnmpAuthProtocol_name[_SnmpAuthProtocol_index[i]:_SnmpAuthProtocol_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UNSPECIFIED-0]
	_ = x[INTENTIONALLY_UNUSED-1]
	_ = x[FAILED_PRECONDITIONS_UNUSED-2]
	_ = x[FAILED-3]
	_ = x[GOOD-4]
}

const _FeedbackObjectFeedbackState_name = "UNSPECIFIEDINTENTIONALLY_UNUSEDFAILED_PRECONDITIONS_UNUSEDFAILEDGOOD"

var _FeedbackObjectFeedbackState_index = [...]uint8{0, 11, 31, 58, 64, 68}

func (i FeedbackObjectFeedbackState) String() string {
	if i < 0 || i >= FeedbackObjectFeedbackState(len(_FeedbackObjectFeedbackState_index)-1) {
		return "FeedbackObjectFeedbackState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FeedbackObjectFeedbackState_name[_FeedbackObjectFeedbackState_index[i]:_FeedbackObjectFeedbackState_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BOOL-0]
	_ = x[INT-1]
	_ = x[UINT-2]
	_ = x[IEEE754-3]
	_ = x[INT_ONES_COMPLEMENT-4]
	_ = x[INT_SIGN_MAGNITUDE-5]
	_ = x[INT_10K-6]
	_ = x[UINT_10K-7]
	_ = x[INT_BCD-8]
	_ = x[INT_SIGN_MAGNITUDE_BCD-9]
	_ = x[UINT_BCD-10]
	_ = x[INT_PACKED_BCD-11]
	_ = x[INT_SIGN_MAGNITUDE_PACKED_BCD-12]
	_ = x[UINT_PACKED_BCD-13]
}

const _EncodingType_name = "BOOLINTUINTIEEE754INT_ONES_COMPLEMENTINT_SIGN_MAGNITUDEINT_10KUINT_10KINT_BCDINT_SIGN_MAGNITUDE_BCDUINT_BCDINT_PACKED_BCDINT_SIGN_MAGNITUDE_PACKED_BCDUINT_PACKED_BCD"

var _EncodingType_index = [...]uint8{0, 4, 7, 11, 18, 37, 55, 62, 70, 77, 99, 107, 121, 150, 165}

func (i EncodingType) String() string {
	if i < 0 || i >= EncodingType(len(_EncodingType_index)-1) {
		return "EncodingType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EncodingType_name[_EncodingType_index[i]:_EncodingType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MODBUS_BIG_ENDIAN-0]
	_ = x[MODBUS_LITTLE_ENDIAN-1]
}

const _ModbusEndianness_name = "MODBUS_BIG_ENDIANMODBUS_LITTLE_ENDIAN"

var _ModbusEndianness_index = [...]uint8{0, 17, 37}

func (i ModbusEndianness) String() string {
	if i < 0 || i >= ModbusEndianness(len(_ModbusEndianness_index)-1) {
		return "ModbusEndianness(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ModbusEndianness_name[_ModbusEndianness_index[i]:_ModbusEndianness_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DES-0]
	_ = x[AES128-1]
	_ = x[AES192-2]
	_ = x[AES256-3]
	_ = x[AES192_3DES-4]
	_ = x[AES256_3DES-5]
}

const _SnmpPrivProtocol_name = "DESAES128AES192AES256AES192_3DESAES256_3DES"

var _SnmpPrivProtocol_index = [...]uint8{0, 3, 9, 15, 21, 32, 43}

func (i SnmpPrivProtocol) String() string {
	if i < 0 || i >= SnmpPrivProtocol(len(_SnmpPrivProtocol_index)-1) {
		return "SnmpPrivProtocol(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SnmpPrivProtocol_name[_SnmpPrivProtocol_index[i]:_SnmpPrivProtocol_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DEFAULT-0]
	_ = x[REJECT_DEVICE-1]
	_ = x[REJECT_SENSOR-2]
	_ = x[IGNORE-3]
	_ = x[UNAVAILABLE-4]
	_ = x[NUMERIC_INVALID-5]
	_ = x[STATE_ON-6]
	_ = x[STATE_OFF-7]
}

const _Interpretation_name = "DEFAULTREJECT_DEVICEREJECT_SENSORIGNOREUNAVAILABLENUMERIC_INVALIDSTATE_ONSTATE_OFF"

var _Interpretation_index = [...]uint8{0, 7, 20, 33, 39, 50, 65, 73, 82}

func (i Interpretation) String() string {
	if i < 0 || i >= Interpretation(len(_Interpretation_index)-1) {
		return "Interpretation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Interpretation_name[_Interpretation_index[i]:_Interpretation_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NO_AUTH_NO_PRIV-0]
	_ = x[AUTH_NO_PRIV-1]
	_ = x[AUTH_PRIV-2]
}

const _SnmpSecurityLevel_name = "NO_AUTH_NO_PRIVAUTH_NO_PRIVAUTH_PRIV"

var _SnmpSecurityLevel_index = [...]uint8{0, 15, 27, 36}

func (i SnmpSecurityLevel) String() string {
	if i < 0 || i >= SnmpSecurityLevel(len(_SnmpSecurityLevel_index)-1) {
		return "SnmpSecurityLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SnmpSecurityLevel_name[_SnmpSecurityLevel_index[i]:_SnmpSecurityLevel_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ACCESS_READ_WRITE-0]
	_ = x[ACCESS_READ-1]
	_ = x[ACCESS_WRITE-2]
}

const _AccessType_name = "ACCESS_READ_WRITEACCESS_READACCESS_WRITE"

var _AccessType_index = [...]uint8{0, 17, 28, 40}

func (i AccessType) String() string {
	if i < 0 || i >= AccessType(len(_AccessType_index)-1) {
		return "AccessType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AccessType_name[_AccessType_index[i]:_AccessType_index[i+1]]
}
