// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package gatewaysensormanager was generated by IDLC from GatewaySensorManager.idl.
// It is part of module peripheral.
// The remaining comment is for module peripheral.
//
// Peripheral Devices
package gatewaysensormanager

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40410/idl"
	"github.com/arminguenther/xeruspower-go/v40410/idl/event"
	"github.com/arminguenther/xeruspower-go/v40410/peripheral/modbuscfg"
	"github.com/arminguenther/xeruspower-go/v40410/sensors/numericsensor"
	"github.com/arminguenther/xeruspower-go/v40410/sensors/sensor"
)

const (
	MODBUS_VENDOR_NAME        int32 = 0
	MODBUS_PRODUCT_CODE       int32 = 1
	MODBUS_REVISION           int32 = 2
	MODBUS_VENDOR_URL         int32 = 3
	MODBUS_PRODUCT_NAME       int32 = 4
	MODBUS_MODEL_NAME         int32 = 5
	MODBUS_APP_NAME           int32 = 6
	ERR_CONFIG_INCONSISTENT   int32 = 1
	ERR_CONFIG_STORAGE_FAILED int32 = 2
)

// Gateway Sensor Configuration Interface
type GatewaySensorManager interface {
	idl.Object

	// Get all defined gateway sensors and required objects from config
	//
	// Read all Sensor Classes, Remote Devices, Value Encodings and Sensors
	// at once to ensure that the overall configuration is consistent
	//
	//	@return all defined gateway sensor feature configuration objects
	GetConfiguration(ctx context.Context) (map[string]ConfigurationPackage, error)

	// Replace defined gateway sensor and/or other configuration objects in config
	//
	// Write all Sensor Classes, Remote Devices, Value Encodings and Sensors
	// at once to ensure that the overall configuration is consistent at every
	// moment.
	//
	// The uniqueness of all IDs and the availability of all referenced elements are
	// checked before the configuration is applied. Otherwise setConfiguration() returns
	// with an error.
	//
	//	@param cfg all defined gateway sensor feature configuration objects
	//	@return 0 if OK
	//	@return ERR_CONFIG_INCONSISTENT if consistency check has failed (e.g. non-unique identifiers)
	//	@return ERR_CONFIG_STORAGE_FAILED if configuration cannot be stored
	SetConfiguration(ctx context.Context, cfg map[string]ConfigurationPackage) (int32, error)

	// Get feedback from gateway sensor configuration usage
	//
	//	@return Result: the full feedback
	GetFeedback(ctx context.Context) ([]Feedback, error)
}

// Specification of sensor class that stores sensor properties
//
// Before an instance of Sensor can be created,
// an instance of SensorClass must be present.
// The Sensor locates the corresponding SensorClass
// using the sensor class id `classId`.
type SensorClass interface {
	idl.ValueObject
	ClassId() string // sensor class id
	isSensorClass()
}

// Sensor class that stores numeric sensor properties
type NumericSensorClass interface {
	SensorClass
	Metadata() numericsensor.MetaData // numeric sensor type, ranges, etc.
	// threshold values may be used initially and as default threshold values,
	// depending on the value of the preferCommonThresholds field
	DefaultThresholds() numericsensor.Thresholds
	PreferCommonThresholds() bool // if true, use common default thresholds if available, otherwise use the value of the defaultThresholds field
	isNumericSensorClass()
}

// Sensor class that stores state sensor properties
type StateSensorClass interface {
	SensorClass
	Type() sensor.TypeSpec // state sensor type
	isStateSensorClass()
}

// Sensor class that switch properties
type SwitchSensorClass interface {
	StateSensorClass
	isSwitchSensorClass()
}

// Specification of a remote device that provides access to sensors
//
// It contains all the information required to connect a remote
// device that provides access to sensors and actuators to be connected
// to one or more gateway sensors.
//
// Before an instance of Sensor can be created, an instance
// of RemoteDevice must be present. The Sensor locates the
// corresponding RemoteDevice using the remote device id `deviceId`.
type RemoteDevice interface {
	idl.ValueObject
	DeviceId() string // remote device id
	Disabled() bool   // prevents usage of all sensor specifications which reference this device
	Name() string     // human readable remote device name
	TimeoutMs() int32 // communication access timeout, 0 = default
	Retry() int32     // communication retry count, 0 = default
	isRemoteDevice()
}

type RemoteModbusDevice interface {
	RemoteDevice
	DetectionIdentifiers() map[int32]string // list of expected device identifiers
	UnitId() int32                          // modbus server address
	// list of unsupported modbus function codes (FC)
	//
	// This information is used to select a supported way for communication,
	// if more than one way is available. If there is no flexibility, the list is ignored.
	// Therefore, some entries may have no effect.
	//
	// Examples:
	//   - FC 43 (Read Device Identification) is used without regard to this list,
	//     as there is no alternative way if detectionIdentifiers is to be used
	//   - FC 22 (Masked Register Write) is only used if the support is known,
	//     otherwise FC 03 + FC 06 (or FC 16 if not known as unsupported) will be used
	UnsupportedFunctionCodes() []byte
	isRemoteModbusDevice()
}

type RemoteModbusRTUDevice interface {
	RemoteModbusDevice
	// rs485 interface used for modbus communication
	//
	// Supported values:
	//
	// (1) with SRC-080X, the REMOTE HUB interfaces are supported, possible values are:
	//   - "REMOTE-HUB-1" or "sensorhub0-rs485" (deprecated) mean port "REMOTE HUB 1"
	//   - "REMOTE-HUB-2" or "sensorhub1-rs485" (deprecated) mean port "REMOTE HUB 2"
	//
	// (2) with Raritan Modbus/RS-485 dongle "USB-MOD-DONGLE", possible values are:
	//   - "USB<topo>": where <topo> contains the USB port number and possibly the topology of USB hubs
	//   - "USB-2" means dongle connected to PDU USB port "USB A 2"
	//   - "USB-1-2-3" means dongle is connected to a first USB hub at port 3,
	//     and the first USB hub is connected to a second USB hub at port 2,
	//     and the second USB hub is connected to PDU USB port "USB A 1"
	//   - "<serial>": where <serial> is the serial number of USB dongle, according to the label
	BusInterface() string
	BusSettings() modbuscfg.SerialSettings // interface settings
	InterframeDelayDeciChars() int32       // (== 0) -> default, (< 0) -> no delay, (> 0) -> e.g. 35 means 3.5 chars
	isRemoteModbusRTUDevice()
}

type RemoteModbusTCPDevice interface {
	RemoteModbusDevice
	IpAddress() string // modbus device ip address
	TcpPort() int32    // modbus tcp port
	isRemoteModbusTCPDevice()
}

type RemoteSnmpDevice interface {
	RemoteDevice
	Host() string // host
	isRemoteSnmpDevice()
}

type RemoteSnmpV1V2Device interface {
	RemoteSnmpDevice
	Community() string // community string for v1/v2c
	isRemoteSnmpV1V2Device()
}

type SnmpSecurityLevel int

const (
	NO_AUTH_NO_PRIV SnmpSecurityLevel = iota // no authentication, no privacy
	AUTH_NO_PRIV                             // authentication, no privacy
	AUTH_PRIV                                // authentication, privacy
)

type SnmpAuthProtocol int

const (
	MD5    SnmpAuthProtocol = iota // MD5
	SHA1                           // SHA-1
	SHA224                         // SHA-224
	SHA256                         // SHA-256
	SHA384                         // SHA-384
	SHA512                         // SHA-512
)

type SnmpPrivProtocol int

const (
	DES         SnmpPrivProtocol = iota // DES
	AES128                              // AES-128
	AES192                              // AES-192
	AES256                              // AES-256
	AES192_3DES                         // AES-192 with key extension (3DES)
	AES256_3DES                         // AES-256 with key extension (3DES)
)

type RemoteSnmpV3Device interface {
	RemoteSnmpDevice
	User() string                      // security username
	Level() SnmpSecurityLevel          // security level (noAuthNoPriv|authNoPriv|authPriv)
	AuthProtocol() SnmpAuthProtocol    // authentication protocol (MD5|SHA|SHA-224|SHA-256|SHA-384|SHA-512)
	AuthPassphrase() string            // authentication protocol passphrase
	PrivacyProtocol() SnmpPrivProtocol // privacy protocol (DES|AES|AES-192|AES-256)
	PrivacyPassphrase() string         // privacy protocol pass phrase
	isRemoteSnmpV3Device()
}

// interpretation of binary values
type EncodingType int

const (
	BOOL                          EncodingType = iota // boolean
	INT                                               // signed integer of a size specified in ValueEncoding as two's complement
	UINT                                              // unsigned integer of a size specified in ValueEncoding
	IEEE754                                           // IEEE 754 floating point of a size specified in ValueEncoding
	INT_ONES_COMPLEMENT                               // integer as one's complement
	INT_SIGN_MAGNITUDE                                // signed integer with sign in MSB
	INT_10K                                           // signed integer stored as 'modulo 10000' (int16[0] + 10000 * int16[1] + 10000^2 * int16[2] ...), the int16 parts are stores as two's complement
	UINT_10K                                          // unsigned integer stored as 'modulo 10000' (uint16[0] + 10000 * uint16[1] + 10000^2 * uint16[2] ...)
	INT_BCD                                           // signed integer as BCD, 10th complement
	INT_SIGN_MAGNITUDE_BCD                            // signed integer as BCD, with sign in MSB
	UINT_BCD                                          // unsigned integer as BCD
	INT_PACKED_BCD                                    // signed integer as packed BCD, 10th complement
	INT_SIGN_MAGNITUDE_PACKED_BCD                     // signed integer as packed BCD, with sign in MSB
	UINT_PACKED_BCD                                   // unsigned integer as packed BCD
)

// Here you define how certain read values are to be interpreted
//
// The rules leading to *_IGNORE and *_UNAVAILABLE are applied to numeric values and states.
//
// IGNORE can be time-limited using ignoreTimeout, see InterpretationRule. After the time has expired,
// the value is set to unavailable.
//
// NUMERIC_INVALID only affects NumericSensors. As DEFAULT for numeric sensors (if
// no rule is matched, or if DEFAULT is matched) the value is converted to a floating point
// number according to type specification.
//
// STATE_ON and STATE_OFF affect only StateSensors. If no such rule is specified, the state
// becomes true if the read value is integral and not 0. If STATE_ON or STATE_OFF are present in
// the rules, then the state is set to true or false only if a STATE_* rule matches. Otherwise
// (DEFAULT) the state becomes unavailable.
//
// REJECT_SENSOR means: do not accept this reading in any way. The sensor is treated as
// non-existent.
//
// REJECT_DEVICE means: do not accept this reading in any way. Instead, this is a clear
// indication that the device is defective, or it is a wrong device. All sensors that belong
// to this device are treated as non-existent.
// REJECT_DEVICE can be used in this way to detect devices. The sensor defined for this purpose
// does not have to be imported as gateway sensor (see Sensor.classId = "").
//
// Default on read access for
//   - received modbus exceptions is REJECT_SENSOR
//   - on modbus errors (SystemError or ModbusSystemError) is REJECT_DEVICE
//   - on value decoding/conversion is normal numeric/state decoding
//
// Default on write access (actuator switch) for
//   - all modbus exceptions and errors is UNAVAILABLE
type Interpretation int

const (
	DEFAULT         Interpretation = iota // default behaviour as without rule, see above
	REJECT_DEVICE                         // read only: device is treated as non-existent
	REJECT_SENSOR                         // read only: sensor is treated as non-existent
	IGNORE                                // read: ignore (use previous value) and retry  write: ignore error and retry
	UNAVAILABLE                           // read: treat as unavailable (both state and numeric value)  write: give up, do not retry
	NUMERIC_INVALID                       // read only: treat as invalid numeric value
	STATE_ON                              // read: treat as state ON   write: use for reversed rule to handle requested ON
	STATE_OFF                             // read: treat as state OFF  write: use for reversed rule to handle requested OFF
)

type AccessType int

const (
	ACCESS_READ_WRITE AccessType = iota // use rule for both read and write access
	ACCESS_READ                         // use rule for read access only
	ACCESS_WRITE                        // use rule for write access only
)

// InterpretationRule defines a rule that is applied to a reading, resulting in an Interpretation.
// A list of InterpretationRule is applied in the given order, and stopped after the first match.
// If no rule applies, the interpretation is Interpretation.DEFAULT.
type InterpretationRule interface {
	idl.ValueObject
	Interpretation() Interpretation // how to interpret the applied rule
	IgnoreTimeout() int32           // if > 0, ignoring stops after this timeout (seconds), and state changes to unavailable
	AccessType() AccessType         // use rule for read and/or write access
	isInterpretationRule()
}

type InterpretationRuleInvertable interface {
	InterpretationRule
	InvertCondition() bool // negate rule condition
	isInterpretationRuleInvertable()
}

// InterpretationRuleModbusException is applied to modbus read exceptions
type InterpretationRuleModbusException interface {
	InterpretationRuleInvertable
	Exceptions() []int32 // list of modbus exception codes
	isInterpretationRuleModbusException()
}

// InterpretationRuleModbusSystemError is applied to standard system errors returned
// from libmodbus
type InterpretationRuleModbusSystemError interface {
	InterpretationRuleInvertable
	Errnos() []int32 // list of system error codes
	isInterpretationRuleModbusSystemError()
}

// InterpretationRuleModbusSpecificError is applied to specific errors from libmodbus
type InterpretationRuleModbusSpecificError interface {
	InterpretationRuleInvertable
	Errors() []modbuscfg.SpecificModbusErrors // list of specific libmodbus error codes
	isInterpretationRuleModbusSpecificError()
}

// InterpretationRuleRAW is applied after swap, but before masking (because it has its own mask)
type InterpretationRuleRAW interface {
	InterpretationRuleInvertable
	Value() string // compare to value (unsigned 64-bit value as string, decimal or hexadecimal)
	Mask() string  // mask before compare (unsigned 64-bit value as string, decimal or hexadecimal; "" or "0" = not masked, the same as "0xFFFFFFFFFFFFFFFF")
	isInterpretationRuleRAW()
}

// InterpretationRuleRangeRAW is applied after swap, but before masking (because it has its own mask)
type InterpretationRuleRangeRAW interface {
	InterpretationRuleInvertable
	Min() string  // minimum accepted value (unsigned 64-bit value as string, decimal or hexadecimal)
	Max() string  // maximum accepted value (unsigned 64-bit value as string, decimal or hexadecimal)
	Mask() string // mask before compare (unsigned 64-bit value as string, decimal or hexadecimal; "" or "0" = not masked, the same as "0xFFFFFFFFFFFFFFFF")
	isInterpretationRuleRangeRAW()
}

// InterpretationRuleEnum is applied to a reading and maps the values to the given Interpretation
type InterpretationRuleEnum interface {
	InterpretationRuleInvertable
	EnumValues() []string // signed or unsigned 64-bit values as strings, decimal or hexadecimal 64-bit numbers
	isInterpretationRuleEnum()
}

// InterpretationRuleIEEE* are applied after value is wrapped, masked and interpreted as float / double
type InterpretationRuleIEEE754INF interface {
	InterpretationRuleInvertable
	isInterpretationRuleIEEE754INF()
}

type InterpretationRuleIEEE754NAN interface {
	InterpretationRuleInvertable
	isInterpretationRuleIEEE754NAN()
}

type InterpretationRuleCatchAll interface {
	InterpretationRule
	isInterpretationRuleCatchAll()
}

// Specification of value encoding
//
// Before an instance of Sensor can be created,
// an instance of ValueEncoding must be present.
// The Sensor locates the corresponding ValueEncoding
// using the sensor class id `encodingId`.
type ValueEncoding interface {
	idl.ValueObject
	EncodingId() string                        // encoding type id
	Type() EncodingType                        // value coding type
	InvertState() bool                         // invert when interpreting as state
	InterpretationRules() []InterpretationRule // error/value interpretation rules
	MinAccessInterval() int32                  // minimum time interval between two read accesses in seconds
	isValueEncoding()
}

type NumericValueEncoding interface {
	ValueEncoding
	ScalingFactor() float32 // multiply with when interpreting as numeric value
	Offset() float32        // add value after applying scalingFactor
	isNumericValueEncoding()
}

type ModbusValueEncodingBit interface {
	ValueEncoding
	isModbusValueEncodingBit()
}

type ModbusValueEncoding8 interface {
	NumericValueEncoding
	// 16-bit modbus words should be transferred in big-endian byte order.
	// For modbus devices that do not comply with this, byteSwap = true must
	// be set. Another application is to use byteSwap to address a single byte in
	// a 16-bit modbus word in case 8-bit values are requested (ModbusValueEncoding8).
	ByteSwap() bool
	// 64-bit unsigned raw mask value as decimal or hexadecimal string, applied before interpreting
	// ("" or "0" = not masked, the same as "0xFFFFFFFFFFFFFFFF")
	Mask() string
	// The least significant bit of the read word used in numerical interpretation.
	// If `start` is greater than 0, then one or more least significant bits remain unused.
	// 0 is the default value. For integer values a `start > 0` has mostly the same effect as
	// using a `mask = ~(2^start-1)` and a `scalingFactor = 1/2^start`.
	Start() int32
	// Word width in bits used in numerical interpretation.
	// If `width` is smaller than the read word width, then the most significant bits remain unused.
	// 0 is the default value.
	// Example: 24 bit signed integer:
	//
	//	`ModbusValueEncoding32` with `start = 0` and `width = 24` and 'type = INT`
	//
	// (Only for unsigned integer the use of `mask` would be sufficient.)
	Width() int32
	isModbusValueEncoding8()
}

type ModbusValueEncoding16 interface {
	ModbusValueEncoding8
	isModbusValueEncoding16()
}

type ModbusEndianness int

const (
	MODBUS_BIG_ENDIAN    ModbusEndianness = iota // use big endian modbus word order (default is big endian)
	MODBUS_LITTLE_ENDIAN                         // use little endian modbus word order
)

type ModbusValueEncoding32 interface {
	ModbusValueEncoding16
	// Modbus 16-bit-words should be transmitted in big endian order. For modbus
	// devices that do not comply with this, endianness must be set to LITTLE_ENDIAN.
	Endianness() ModbusEndianness
	isModbusValueEncoding32()
}

type ModbusValueEncoding48 interface {
	ModbusValueEncoding32
	isModbusValueEncoding48()
}

type ModbusValueEncoding64 interface {
	ModbusValueEncoding32
	isModbusValueEncoding64()
}

// Specification of a Sensor
type Sensor interface {
	idl.ValueObject
	SensorId() string // Unique sensor id, is automatically generated if not set
	Disabled() bool   // Set disabled = true prevents any usage of the specification
	// remote device id
	//
	// deviceId is used to locate the corresponding RemoteDevice that
	// provides the physical sensor
	DeviceId() string
	// sensor class id
	//
	// classId is used to locate the corresponding SensorClass.
	// classId = "" prevents the sensor specification from being used
	// for an imported gateway sensor. The sensor value is read anyway, and a read
	// error or an interpretation as Interpretation.REJECT_DEVICE
	// prevents the successful detection of the device
	ClassId() string
	// sensor encoding id
	//
	// classId is used to locate the corresponding ValueEncoding
	EncodingId() string
	// sensor name
	//
	// defaultName is used as default sensor slot name
	DefaultName() string
	// sensor description
	//
	// defaultDescription is used as default sensor slot description
	DefaultDescription() string
	// sensor location X coordinate
	//
	// defaultLocationX is used as default sensor slot location X coordinate
	DefaultLocationX() string
	// sensor location Y coordinate
	//
	// defaultLocationY is used as default sensor slot location Y coordinate
	DefaultLocationY() string
	// sensor location Z coordinate
	//
	// defaultLocationZ is used as default sensor slot location Z coordinate
	DefaultLocationZ() string
	isSensor()
}

type ModbusSensor interface {
	Sensor
	Function() modbuscfg.ModbusFunction // Modbus function to be used
	RegAddr() int32                     // Modbus server register address
	isModbusSensor()
}

type SnmpSensor interface {
	Sensor
	Oid() string // sensor oid
	isSnmpSensor()
}

type ConfigurationPackage struct {
	Disabled  bool   // prevents usage of all sensor specifications defined in this package
	Name      string // package name
	Classes   []SensorClass
	Devices   []RemoteDevice
	Encodings []ValueEncoding
	Sensors   []Sensor
}

// Event: The gateway sensor feature configuration has changed
type ConfigurationChangedEvent interface {
	event.Event
	Configuration() map[string]ConfigurationPackage // the current gateway sensor feature configuration
	isConfigurationChangedEvent()
}

// Feedback from gateway sensor configuration usage
//
// There is no knowledge of Feedback required to configure gateway sensors.
// The following is only needed for special tools that monitor the usage
// of the configurations above.
type FeedbackObject struct {
	Key              string                      // empty or free defined value name
	Value            string                      // message or value
	StateTansitionTo FeedbackObjectFeedbackState // this FeedbackObject changes state, if not UNSPECIFIED
}

type FeedbackObjectFeedbackState int

const (
	UNSPECIFIED FeedbackObjectFeedbackState = iota
	INTENTIONALLY_UNUSED
	FAILED_PRECONDITIONS_UNUSED
	FAILED
	GOOD
)

type Feedback interface {
	idl.ValueObject
	CurrentState() FeedbackObjectFeedbackState // Device or sensor state
	Infos() []FeedbackObject
	isFeedback()
}

type DeviceFeedback interface {
	Feedback
	PackageId() string // the configuration package id
	DeviceId() string  // the same id as in RemoteDevice
	isDeviceFeedback()
}

type SensorFeedback interface {
	Feedback
	PackageId() string // the configuration package id
	DeviceId() string  // the same id as in RemoteDevice
	SensorId() string  // the same id as in Sensor
	isSensorFeedback()
}

// Event: The configuration usage feedback has changed
type FeedbackChangedEvent interface {
	event.Event
	Feedback() []Feedback // the latest configuration usage feedback
	isFeedbackChangedEvent()
}
