// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package gatewaysensormanager was generated by IDLC from GatewaySensorManager.idl.
// It is part of module peripheral.
// The remaining comment is for module peripheral.
//
// Peripheral Devices
package gatewaysensormanager

import (
	"context"

	"github.com/arminguenther/xeruspower-go/idl"
	"github.com/arminguenther/xeruspower-go/idl/event"
	"github.com/arminguenther/xeruspower-go/peripheral/modbuscfg"
	"github.com/arminguenther/xeruspower-go/sensors/numericsensor"
	"github.com/arminguenther/xeruspower-go/sensors/sensor"
)

const (
	MODBUS_VENDOR_NAME        int32 = 0
	MODBUS_PRODUCT_CODE       int32 = 1
	MODBUS_REVISION           int32 = 2
	MODBUS_VENDOR_URL         int32 = 3
	MODBUS_PRODUCT_NAME       int32 = 5
	MODBUS_MODEL_NAME         int32 = 6
	MODBUS_APP_NAME           int32 = 7
	ERR_CONFIG_INCONSISTENT   int32 = 1
	ERR_CONFIG_STORAGE_FAILED int32 = 2
)

// Gateway Sensor Configuration Interface
type GatewaySensorManager interface {
	idl.Object

	// Get all defined gateway sensors and required objects from config
	//
	// Read all Sensor Classes, Remote Devices, Value Encodings and Sensors
	// at once to ensure that the overall configuration is consistent
	//
	//	@return all defined gateway sensor feature configuration objects
	GetConfiguration(ctx context.Context) (map[string]ConfigurationPackage, error)

	// Replace defined gateway sensor and/or other configuration objects in config
	//
	// Write all Sensor Classes, Remote Devices, Value Encodings and Sensors
	// at once to ensure that the overall configuration is consistent at every
	// moment.
	//
	// The uniqueness of all IDs and the availability of all referenced elements are
	// checked before the configuration is applied. Otherwise setConfiguration() returns
	// with an error.
	//
	//	@param cfg all defined gateway sensor feature configuration objects
	//	@return 0 if OK
	//	@return ERR_CONFIG_INCONSISTENT if consistency check has failed (e.g. non-unique identifiers)
	//	@return ERR_CONFIG_STORAGE_FAILED if configuration cannot be stored
	SetConfiguration(ctx context.Context, cfg map[string]ConfigurationPackage) (int32, error)

	// Get feedback from gateway sensor configuration usage
	//
	//	@return Result: the full feedback
	GetFeedback(ctx context.Context) ([]Feedback, error)
}

// Specification of sensor class that stores sensor properties
//
// Before an instance of Sensor can be created,
// an instance of SensorClass must be present.
// The Sensor locates the corresponding SensorClass
// using the sensor class id `classId`.
type SensorClass interface {
	idl.ValueObject
	ClassId() string // sensor class id
	isSensorClass()
}

// Sensor class that stores numeric sensor properties
type NumericSensorClass interface {
	SensorClass
	Metadata() numericsensor.MetaData // numeric sensor type, ranges, etc.
	// threshold values may be used initially and as default threshold values,
	// depending on the value of the preferCommonThresholds field
	DefaultThresholds() numericsensor.Thresholds
	PreferCommonThresholds() bool // if true, use common default thresholds if available, otherwise use the value of the defaultThresholds field
	isNumericSensorClass()
}

// Sensor class that stores state sensor properties
type StateSensorClass interface {
	SensorClass
	Type() sensor.TypeSpec // state sensor type
	isStateSensorClass()
}

// Sensor class that switch properties
type SwitchSensorClass interface {
	StateSensorClass
	isSwitchSensorClass()
}

// Specification of a remote device that provides access to sensors
//
// It contains all the information required to connect a remote
// device that provides access to sensors and actuators to be connected
// to one or more gateway sensors.
//
// Before an instance of Sensor can be created, an instance
// of RemoteDevice must be present. The Sensor locates the
// corresponding RemoteDevice using the remote device id `deviceId`.
type RemoteDevice interface {
	idl.ValueObject
	DeviceId() string // remote device id
	Disabled() bool   // prevents usage of all sensor specifications which reference this device
	Name() string     // human readable remote device name
	TimeoutMs() int32 // communication access timeout, 0 = default
	Retry() int32     // communication retry count, 0 = default
	isRemoteDevice()
}

type RemoteModbusDevice interface {
	RemoteDevice
	DetectionIdentifiers() map[int32]string // list of expected device identifiers
	UnitId() int32                          // modbus server address
	isRemoteModbusDevice()
}

type RemoteModbusRTUDevice interface {
	RemoteModbusDevice
	BusInterface() string                  // modbus/rs485 interface, e.g. 'sensorhub1-rs485`
	BusSettings() modbuscfg.SerialSettings // interface settings
	InterframeDelayDeciChars() int32       // (== 0) -> default, (< 0) -> no delay, (> 0) -> e.g. 35 means 3.5 chars
	isRemoteModbusRTUDevice()
}

type RemoteModbusTCPDevice interface {
	RemoteModbusDevice
	IpAddress() string // modbus device ip address
	TcpPort() int32    // modbus tcp port
	isRemoteModbusTCPDevice()
}

// Specification of value encoding
//
// Before an instance of Sensor can be created,
// an instance of ValueEncoding must be present.
// The Sensor locates the corresponding ValueEncoding
// using the sensor class id `encodingId`.
type EncodingType int

const (
	BOOL    EncodingType = iota // boolean
	INT                         // signed integer of a size specified in ValueEncoding
	UINT                        // unsigned integer of a size specified in ValueEncoding
	IEEE754                     // IEEE 754 floating point of a size specified in ValueEncoding
)

// Here you define how certain read values are to be interpreted
//
// The rules leading to *_IGNORE and *_UNAVAILABLE are applied to numeric values and states.
//
// IGNORE can be time-limited using ignoreTimeout, see InterpretationRule. After the time has expired,
// the value is set to unavailable.
//
// NUMERIC_INVALID only affects NumericSensors. As DEFAULT for numeric sensors (if
// no rule is matched, or if DEFAULT is matched) the value is converted to a floating point
// number according to type specification.
//
// STATE_ON and STATE_OFF affect only StateSensors. If no such rule is specified, the state
// becomes true if the read value is integral and not 0. If STATE_ON or STATE_OFF are present in
// the rules, then the state is set to true or false only if a STATE_* rule matches. Otherwise
// (DEFAULT) the state becomes unavailable.
//
// REJECT_SENSOR means: do not accept this reading in any way. The sensor is treated as
// non-existent.
//
// REJECT_DEVICE means: do not accept this reading in any way. Instead, this is a clear
// indication that the device is defective, or it is a wrong device. All sensors that belong
// to this device are treated as non-existent.
// REJECT_DEVICE can be used in this way to detect devices. The sensor defined for this purpose
// does not have to be imported as gateway sensor (see Sensor.classId = "").
//
// DEFAULT on failed receives modbus exceptions REJECT_SENSOR. DEFAULT on modbus read errors
// (e.g. timeouts) is REJECT_DEVICE.
type Interpretation int

const (
	DEFAULT         Interpretation = iota // use default decoding
	REJECT_DEVICE                         // device is treated as non-existent
	REJECT_SENSOR                         // sensor is treated as non-existent
	IGNORE                                // ignore (use previous value)
	UNAVAILABLE                           // set value to unavailable
	NUMERIC_INVALID                       // set numeric value to invalid
	STATE_ON                              // set state to ON
	STATE_OFF                             // set state to OFF
)

// InterpretationRule defines a rule that is applied to a reading, resulting in an Interpretation.
// A list of InterpretationRule is applied in the given order, and stopped after the first match.
// If no rule applies, the interpretation is Interpretation.DEFAULT.
type InterpretationRule interface {
	idl.ValueObject
	Interpretation() Interpretation // how to interpret the applied rule
	IgnoreTimeout() int32           // if > 0, ignoring stops after this timeout (seconds), and state changes to unavailable
	isInterpretationRule()
}

type InterpretationRuleInvertable interface {
	InterpretationRule
	InvertCondition() bool // negate rule condition
	isInterpretationRuleInvertable()
}

// InterpretationRuleModbusException is applied to modbus read exceptions
type InterpretationRuleModbusException interface {
	InterpretationRuleInvertable
	Exceptions() []int32 // list of modbus exception codes
	isInterpretationRuleModbusException()
}

// InterpretationRuleModbusSystemError is applied to standard system errors returned
//
//	from libmodbus
type InterpretationRuleModbusSystemError interface {
	InterpretationRuleInvertable
	Errnos() []int32 // list of system error codes
	isInterpretationRuleModbusSystemError()
}

// InterpretationRuleModbusSpecificError is applied to specific errors from libmodbus
type InterpretationRuleModbusSpecificError interface {
	InterpretationRuleInvertable
	Errors() []modbuscfg.SpecificModbusErrors // list of specific libmodbus error codes
	isInterpretationRuleModbusSpecificError()
}

// InterpretationRuleRAW is applied after swap, but before masking (because it has it's own mask)
type InterpretationRuleRAW interface {
	InterpretationRuleInvertable
	Value() int64 // compare to value
	Mask() int64  // (0 = not masked, the same as 0xFFFF...)
	isInterpretationRuleRAW()
}

// InterpretationRuleRangeRAW is applied after swap, but before masking (because it has it's own mask)
type InterpretationRuleRangeRAW interface {
	InterpretationRuleInvertable
	Min() int64  // minimum accepted value
	Max() int64  // maximum accepted value
	Mask() int64 // (0 = not masked, the same as 0xFFFF...)
	isInterpretationRuleRangeRAW()
}

// InterpretationRuleIEEE* are applied after value is wapped, masked and interpreted as float / double
type InterpretationRuleIEEE754INF interface {
	InterpretationRuleInvertable
	isInterpretationRuleIEEE754INF()
}

type InterpretationRuleIEEE754NAN interface {
	InterpretationRuleInvertable
	isInterpretationRuleIEEE754NAN()
}

type InterpretationRuleCatchAll interface {
	InterpretationRule
	isInterpretationRuleCatchAll()
}

type ValueEncoding interface {
	idl.ValueObject
	EncodingId() string                        // encoding type id
	Type() EncodingType                        // value coding type
	InvertState() bool                         // invert when interpreting as state
	InterpretationRules() []InterpretationRule // error/value inerpretation rules
	isValueEncoding()
}

type NumericValueEncoding interface {
	ValueEncoding
	ScalingFactor() float32 // multiply with when interpreting as numeric value
	Offset() float32        // add value after applying scalingFactor
	isNumericValueEncoding()
}

type ModbusValueEncodingBit interface {
	ValueEncoding
	isModbusValueEncodingBit()
}

type ModbusValueEncoding8 interface {
	NumericValueEncoding
	// 16-bit modbus words should be transferred in big-endian byte order.
	// For modbus devices that do not comply with this, byteSwap = true must
	// be set. Another application is to use byteSwap to address a single byte in
	// a 16-bit modbus word in case 8-bit values are requested (ModbusValueEncoding8).
	ByteSwap() bool
	Mask() int64 // mask raw value before interpreting (0 = not masked, the same as 0xFFFF...)
	isModbusValueEncoding8()
}

type ModbusValueEncoding16 interface {
	ModbusValueEncoding8
	isModbusValueEncoding16()
}

type ModbusEndianness int

const (
	MODBUS_BIG_ENDIAN    ModbusEndianness = iota // use big endian modbus word order (default is big endian)
	MODBUS_LITTLE_ENDIAN                         // use little endian modbus word order
)

type ModbusValueEncoding32 interface {
	ModbusValueEncoding16
	// Modbus 16-bit-words should be transmitted in big endian order. For modbus
	// devices that do not comply with this, endianness must be set to LITTLE_ENDIAN.
	Endianness() ModbusEndianness
	isModbusValueEncoding32()
}

type ModbusValueEncoding64 interface {
	ModbusValueEncoding32
	isModbusValueEncoding64()
}

// Specification of a Sensor
type Sensor interface {
	idl.ValueObject
	SensorId() string // Unique sensor id, is automatically generated if not set
	Disabled() bool   // Set disabled = true prevents any usage of the specification
	// remote device id
	//
	// deviceId is used to locate the corresponding RemoteDevice that
	// provides the physical sensor
	DeviceId() string
	// sensor class id
	//
	// classId is used to locate the corresponding SensorClass.
	// classId = "" prevents the sensor specification from being used
	// for an imported gateway sensor. The sensor value is read anyway, and a read
	// error or a interpretation as Interpretation.REJECT_DEVICE
	// prevents the successful detection of the device
	ClassId() string
	// sensor encoding id
	//
	// classId is used to locate the corresponding ValueEncoding
	EncodingId() string
	// default sensor name
	//
	// defaultName is used as sensor slot name
	DefaultName() string
	isSensor()
}

type ModbusSensor interface {
	Sensor
	Function() modbuscfg.ModbusFunction // Modbus function to be used
	RegAddr() int32                     // Modbus server register address
	isModbusSensor()
}

type ConfigurationPackage struct {
	Disabled  bool   // prevents usage of all sensor specifications defined in this package
	Name      string // package name
	Classes   []SensorClass
	Devices   []RemoteDevice
	Encodings []ValueEncoding
	Sensors   []Sensor
}

// Event: The gateway sensor feature configuration has changed
type ConfigurationChangedEvent interface {
	event.Event
	Configuration() map[string]ConfigurationPackage // the current gateway sensor feature configuration
	isConfigurationChangedEvent()
}

// Feedback from gateway sensor configuration usage
//
// There is no knowledge of Feedback required to configure gateway sensors.
// The following is only needed for special tools that monitor the usage
// of the configurations above.
type FeedbackObject struct {
	Key              string                      // empty or free defined value name
	Value            string                      // message or value
	StateTansitionTo FeedbackObjectFeedbackState // this FeedbackObject changes state, if not UNSPECIFIED
}

type FeedbackObjectFeedbackState int

const (
	UNSPECIFIED FeedbackObjectFeedbackState = iota
	INTENTIONALLY_UNUSED
	FAILED_PRECONDITIONS_UNUSED
	FAILED
	GOOD
)

type Feedback interface {
	idl.ValueObject
	CurrentState() FeedbackObjectFeedbackState // Device or sensor state
	Infos() []FeedbackObject
	isFeedback()
}

type DeviceFeedback interface {
	Feedback
	PackageId() string // the configuration package id
	DeviceId() string  // the same id as in RemoteDevice
	isDeviceFeedback()
}

type SensorFeedback interface {
	Feedback
	PackageId() string // the configuration package id
	DeviceId() string  // the same id as in RemoteDevice
	SensorId() string  // the same id as in Sensor
	isSensorFeedback()
}

// Event: The configuration usage feedback has changed
type FeedbackChangedEvent interface {
	event.Event
	Feedback() []Feedback // the latest configuration usage feedback
	isFeedbackChangedEvent()
}
