// Copyright 2026 Raritan Inc. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause

// Package inlets was generated by IDLC from Inlets.idl.
// It is part of module pdumodel.
// The remaining comment is for module pdumodel.
package inlets

import (
	"context"

	"github.com/arminguenther/xeruspower-go/idl"
)

// The inlets interface
type Inlets interface {
	idl.Object

	// Gets inlets information
	//
	//	@return inlets info
	GetInfo(ctx context.Context) (Info, error)
}

// The inlets information
type Info struct {
	NumberOfInlets int32 // the number of inlets
}
