// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package alarmmanager was generated by IDLC from AlarmManager.idl.
// It is part of module event.
// The remaining comment is for module event.
//
// Event interface
package alarmmanager

import (
	"context"
	"time"

	"github.com/arminguenther/xeruspower-go/v40020/idl"
	"github.com/arminguenther/xeruspower-go/v40020/idl/event"
)

// Error codes
const (
	NO_ERROR              int32 = 0 // operation successful, no error
	ERR_UNKNOWN_ALARM_ID  int32 = 1 // unknown alarmId
	ERR_EXECUTING_ACTIONS int32 = 2 // failure during executing actions
)

// AlarmManager interface
type AlarmManager interface {
	idl.Object

	// Acknowledges an alarm.
	//
	// This stops notification sending and will remove
	// the specified alarm from the alarm list.
	//
	//	@param  alarmId                      alarm id
	//	@return NO_ERROR                     if OK
	//	@return ERR_UNKNOWN_ALARM_ID         if alarmId is unknown
	//	@return ERR_EXECUTING_ACTIONS        if failure during executing acknowledgment actions
	AcknowledgeAlarm(ctx context.Context, alarmId string) (int32, error)

	// List alarms that need to be acknowledged.
	ListAlarms(ctx context.Context) ([]Alarm, error)
}

// Alert structure
//
// An alert contains the event id, the log message of the triggered
// alarm condition plus time and counter fields to express
// when and how often the alarm condition was triggered.
type Alert struct {
	EventCondition  string    // Event condition
	Message         string    // Log message
	FirstAppearance time.Time // Date & time of first appearance (UNIX timestamp, UTC)
	LastAppearance  time.Time // Date & time of last appearance (UNIX timestamp, UTC)
	NumberAlerts    int32     // Number of alerts
}

// Alarm structure
//
// An alarm has a name, a reference to its action source
// and a list of all alerts which created the alarm.
type Alarm struct {
	Id       string  // Alarm id
	Name     string  // Alarm name
	ActionId string  // Corresponding action id
	Alerts   []Alert // List of alerts
}

// New alarm added event
type AlarmAddedEvent interface {
	event.Event
	Alarm() Alarm // Newly added alarm
	isAlarmAddedEvent()
}

// Alarm updated event
type AlarmUpdatedEvent interface {
	event.Event
	Alarm() Alarm // Updated alarm
	isAlarmUpdatedEvent()
}

// Existing alarm acknowledgement event
type AlarmAcknowledgedEvent interface {
	event.Event
	AlarmId() string // Alarm id of acknowledged alarm
	isAlarmAcknowledgedEvent()
}
