// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package displaycontrol was generated by IDLC from DisplayControl.idl.
// It is part of module display.
// The remaining comment is for module display.
//
// Front panel display interface
package displaycontrol

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40010/event/userevent"
	"github.com/arminguenther/xeruspower-go/v40010/idl"
)

// Error codes
const (
	SUCCESS           int32 = 0 // No error
	ERR_INVALID_VALUE int32 = 1 // Invalid argument
)

// Interface to control the device's front panel display
type DisplayControl interface {
	idl.Object

	// Get available default views. This returns all views that can be
	// used as default views on the device display.
	//
	//	@return Possible default views, or empty list if the default view
	//	        can not be configured for the device's display
	GetAvailableDefaultViews(ctx context.Context) ([]DefaultViewItem, error)

	// Get the currently active default view.
	//
	//	@return View ID of current default view.
	//	        If the device doesn't allow configuration of
	//	        the default view, an empty string is returned.
	GetDefaultView(ctx context.Context) (string, error)

	// Set the active default view.
	//
	//	@param id  View ID of new default view
	//
	//	@return 0 on success
	//	@return 1 if id is not part of the key set returned by
	//	          getAvailableDefaultViews
	SetDefaultView(ctx context.Context, id string) (int32, error)

	// Retrieve display's meta information.
	//
	//	@return Display information
	GetInfo(ctx context.Context) (Info, error)

	// Show smiley on display
	//
	//	@param on    true to turn on smiley
	//	@param happy true to show happy smiley,false to show sad smiley
	//	@param msg   String for message
	ShowSmiley(ctx context.Context, on bool, happy bool, msg string) error
}

// Collected display meta information
type Info struct {
	FwAppVersion     int32 // Firmware application version; 0 if unavailable
	FwBootVersion    int32 // Firmware bootloader version; 0 if unavailable
	Orientation      int32 // Display orientation
	Width            int32 // Display width
	Height           int32 // Display height
	VersionAvailable bool  // true if version information is available
}

// Representation of a possible default view
type DefaultViewItem struct {
	Id          string // View ID
	Description string // Textual description
}

// Event: The default view was changed
type DefaultViewChangedEvent interface {
	userevent.UserEvent
	NewView() DefaultViewItem // New default view
	isDefaultViewChangedEvent()
}
