// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Code generated by "stringer -output=enum_strings.go -type=UpdateFlags,UpdateHistoryStatus,ImageState"; DO NOT EDIT.

package firmware

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CROSS_OEM-0]
	_ = x[CROSS_HW-1]
	_ = x[ALLOW_UNTRUSTED-2]
}

const _UpdateFlags_name = "CROSS_OEMCROSS_HWALLOW_UNTRUSTED"

var _UpdateFlags_index = [...]uint8{0, 9, 17, 32}

func (i UpdateFlags) String() string {
	if i < 0 || i >= UpdateFlags(len(_UpdateFlags_index)-1) {
		return "UpdateFlags(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UpdateFlags_name[_UpdateFlags_index[i]:_UpdateFlags_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SUCCESSFUL-0]
	_ = x[FAILED-1]
	_ = x[INCOMPLETE-2]
}

const _UpdateHistoryStatus_name = "SUCCESSFULFAILEDINCOMPLETE"

var _UpdateHistoryStatus_index = [...]uint8{0, 10, 16, 26}

func (i UpdateHistoryStatus) String() string {
	if i < 0 || i >= UpdateHistoryStatus(len(_UpdateHistoryStatus_index)-1) {
		return "UpdateHistoryStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UpdateHistoryStatus_name[_UpdateHistoryStatus_index[i]:_UpdateHistoryStatus_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NONE-0]
	_ = x[UPLOADING-1]
	_ = x[UPLOAD_FAILED-2]
	_ = x[DOWNLOADING-3]
	_ = x[DOWNLOAD_FAILED-4]
	_ = x[COMPLETE-5]
}

const _ImageState_name = "NONEUPLOADINGUPLOAD_FAILEDDOWNLOADINGDOWNLOAD_FAILEDCOMPLETE"

var _ImageState_index = [...]uint8{0, 4, 13, 26, 37, 52, 60}

func (i ImageState) String() string {
	if i < 0 || i >= ImageState(len(_ImageState_index)-1) {
		return "ImageState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ImageState_name[_ImageState_index[i]:_ImageState_index[i+1]]
}
