// Code generated by "stringer -output=enum_strings.go -type=PackageInfoState"; DO NOT EDIT.

package peripheraldevicepackage

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NORMAL-0]
	_ = x[FW_UPDATE-1]
	_ = x[INTERNAL_ERROR-2]
	_ = x[CONFIG_ERROR-3]
}

const _PackageInfoState_name = "NORMALFW_UPDATEINTERNAL_ERRORCONFIG_ERROR"

var _PackageInfoState_index = [...]uint8{0, 6, 15, 29, 41}

func (i PackageInfoState) String() string {
	if i < 0 || i >= PackageInfoState(len(_PackageInfoState_index)-1) {
		return "PackageInfoState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PackageInfoState_name[_PackageInfoState_index[i]:_PackageInfoState_index[i+1]]
}
