// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package peripheraldevicepackage was generated by IDLC from PeripheralDevicePackage.idl.
// It is part of module peripheral.
// The remaining comment is for module peripheral.
//
// Peripheral Devices
package peripheraldevicepackage

import (
	"context"
	"time"

	"github.com/arminguenther/xeruspower-go/idl"
	"github.com/arminguenther/xeruspower-go/idl/event"
	"github.com/arminguenther/xeruspower-go/peripheral/poselement"
)

// Peripheral device package information
type PackageInfo struct {
	State    PackageInfoState        // The peripheral device package operational state
	Position []poselement.PosElement // Position within 1-wire topo
	HwInfo   struct /*HardwareInfo*/ {
		Serial              string // serial number
		PackageClass        string // serial number prefix for current packages
		Model               string // like 'DPX-CC2' or 'DX-D2C6'
		MinDowngradeVersion int32  // minimum downgrade version (or -1)
		Revision            string // hardware revision
		Address             string // ROM code for 1-wire devices
	} // Device package hardware specific information
	FwInfo struct /*FirmwareInfo*/ {
		CompileDate time.Time // Date of firmware compilation (Deprecated: always returns 0)
		Version     struct /*Version*/ {
			MajorNumber       int32 // firmware version encoded as 'major << 4 | minor'
			MinorNumber       int32 // deprecated, was minor firmware version
			BootloaderVersion int32 // device bootloader version
		} // Firmware version (0.0 if not applicable)
		UpdateDate   time.Time // Date of device firmware update (Deprecated: always returns 0)
		FirmwareName string    // firmware file name
	} // Device package firmware specific information
}

type PackageInfoState int

const (
	NORMAL         PackageInfoState = iota // Device package is in normal operation
	FW_UPDATE                              // Device package's firmware is being updated
	INTERNAL_ERROR                         // Device package's internal error flag is set
	CONFIG_ERROR                           // Device package's internal configuration is invalid
)

type Package interface {
	idl.Object

	GetPackageInfo(ctx context.Context) (PackageInfo, error)
}

const (
	SUCCESS              int32 = 0
	ERR_NOT_SUPPORTED    int32 = 1
	ERR_OPERATION_FAILED int32 = 2
)

type DoorHandleControllerPackage interface {
	Package

	GetSupportedHandleTypes(ctx context.Context) ([]string, error)

	GetSupportedExternalDeviceTypes(ctx context.Context) ([]string, error)

	GetHandleType(ctx context.Context, channel int32) (string, error)

	GetExternalDeviceType(ctx context.Context, channel int32) (string, error)

	SetHandleType(ctx context.Context, channel int32, handleType string) (int32, error)

	SetExternalDeviceType(ctx context.Context, channel int32, type_ string) (int32, error)
}

// Event: A handle was opened without being electronically unlocked
type DoorHandleControllerPackageMechanicallyUnlockedEvent interface {
	event.Event
	PackageInfo() PackageInfo // package info
	Channel() int32           // channel number (zero-based)
	DoorStateName() string    // name of the door state sensor (if assigned)
	DoorHandleName() string   // name of the door handle sensor (if assigned)
	DoorLockName() string     // name of the door lock actuator (if assigned)
	isDoorHandleControllerPackageMechanicallyUnlockedEvent()
}

// Event: A door was opened without unlocking the door handle
type DoorHandleControllerPackageDoorForcedOpenEvent interface {
	event.Event
	PackageInfo() PackageInfo // package info
	Channel() int32           // channel number (zero-based)
	DoorStateName() string    // name of the door state sensor (if assigned)
	DoorHandleName() string   // name of the door handle sensor (if assigned)
	DoorLockName() string     // name of the door lock actuator (if assigned)
	isDoorHandleControllerPackageDoorForcedOpenEvent()
}

type BatteryPoweredDevicePackage interface {
	Package

	// This method outputs the given voltage value or zero if no value is available.
	//
	//	@return 0 or the voltage value in V
	GetBatteryVoltage(ctx context.Context) (float64, error)
}

// Event: the voltage of this device changed
type BatteryPoweredDevicePackageVoltageChangedEvent interface {
	event.Event
	OldVoltage() float64 // old voltage
	NewVoltage() float64 // new voltage
	isBatteryPoweredDevicePackageVoltageChangedEvent()
}
