// Copyright 2026 Raritan Inc. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause

// Package testunit was generated by IDLC from TestUnit.idl.
// It is part of module test.
// The remaining comment is for module test.
//
// Test Interfaces
package testunit

import (
	"context"

	"github.com/arminguenther/xeruspower-go/idl"
	"github.com/arminguenther/xeruspower-go/test/testdisplay"
)

// Test interface for PDU components controlled by topofw
type Unit interface {
	idl.Object

	// Retrieve all Displays attached to the unit.
	//
	//	@return List of displays
	GetDisplays(ctx context.Context) ([]testdisplay.Display, error)

	// Retrieve state of all buttons attached to the unit.
	//
	// Note that semantics of the buttons is not defined
	// by this interface, although it is garanteed that the
	// order in which states are returned will not change.
	//
	//	@return List of button states (true if pressed)
	GetButtonStates(ctx context.Context) ([]bool, error)

	// Force on the buzzer.
	//
	//	@param isOn true to force buzzer on, false for normal mode
	SetBuzzer(ctx context.Context, isOn bool) error

	// Reset all sub controllers via RS485 break condition
	ResetAllSubControllers(ctx context.Context) error

	// Trigger watchdog of a selected sub controller
	//
	//	@param rs485Addr RS485 address of the sub controller to trigger
	//	                 the watchdog for.
	TriggerSubControllerWatchdog(ctx context.Context, rs485Addr int32) error
}
