// Code generated by "stringer -output=enum_strings.go -type=PowerLine"; DO NOT EDIT.

package pole

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[L1-0]
	_ = x[L2-1]
	_ = x[L3-2]
	_ = x[NEUTRAL-3]
	_ = x[EARTH-4]
	_ = x[PLUS-5]
	_ = x[MINUS-6]
}

const _PowerLine_name = "L1L2L3NEUTRALEARTHPLUSMINUS"

var _PowerLine_index = [...]uint8{0, 2, 4, 6, 13, 18, 22, 27}

func (i PowerLine) String() string {
	if i < 0 || i >= PowerLine(len(_PowerLine_index)-1) {
		return "PowerLine(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PowerLine_name[_PowerLine_index[i]:_PowerLine_index[i+1]]
}
