// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package pole was generated by IDLC from Pole.idl.
// It is part of module pdumodel.
// The remaining comment is for module pdumodel.
//
// PDU Model
package pole

import (
	"github.com/arminguenther/xeruspower-go/v40412/pdumodel/residualcurrentstatesensor"
	"github.com/arminguenther/xeruspower-go/v40412/sensors/numericsensor"
)

// Power line
type PowerLine int

const (
	L1      PowerLine = iota // Line 1
	L2                       // Line 2
	L3                       // Line 3
	NEUTRAL                  // Neutral
	EARTH                    // Earth
	PLUS                     // Positive (DC)
	MINUS                    // Negative (DC)
)

// An inlet or outlet pole
type Pole struct {
	Label                   string                      // Pole label
	Line                    PowerLine                   // Power line
	NodeId                  int32                       // Circuit node id
	Voltage                 numericsensor.NumericSensor // RMS voltage sensor, L-L, may be a VoltageMonitoringSensor
	VoltageLN               numericsensor.NumericSensor // RMS voltage sensor, L-N (Wye) or L-PE (Delta), may be a VoltageMonitoringSensor
	Current                 numericsensor.NumericSensor // RMS current sensor
	PeakCurrent             numericsensor.NumericSensor // Peak current sensor
	ActivePower             numericsensor.NumericSensor // Active power sensor
	ReactivePower           numericsensor.NumericSensor // Reactive power sensor
	ApparentPower           numericsensor.NumericSensor // Apparent power sensor
	PowerFactor             numericsensor.NumericSensor // Power factor sensor
	PhaseAngle              numericsensor.NumericSensor // Phase angle sensor
	DisplacementPowerFactor numericsensor.NumericSensor // Displacement power factor sensor
	ActiveEnergy            numericsensor.NumericSensor // Active energy sensor
	ApparentEnergy          numericsensor.NumericSensor // Apparent energy sensor
	ResidualCurrent         numericsensor.NumericSensor // Residual current sensor
	// AC Residual current sensor
	// (AC portion of residual operating current)
	ResidualACCurrent numericsensor.NumericSensor
	// DC Residual current sensor
	// (DC portion of residual operating current)
	ResidualDCCurrent     numericsensor.NumericSensor
	CrestFactor           numericsensor.NumericSensor                           // Crest factor sensor
	VoltageThd            numericsensor.NumericSensor                           // Voltage total harmonic distortion sensor
	CurrentThd            numericsensor.NumericSensor                           // Current total harmonic distortion sensor
	ResidualCurrentStatus residualcurrentstatesensor.ResidualCurrentStateSensor // Residual current monitor state sensor
}

// An inlet line pair
type MeteredLinePair struct {
	LeftLine                PowerLine                   // Power line of left node
	RightLine               PowerLine                   // Power line of right node
	LeftNodeId              int32                       // Left node id
	RightNodeId             int32                       // Right node id
	Voltage                 numericsensor.NumericSensor // RMS voltage sensor, L-L, may be a VoltageMonitoringSensor
	Current                 numericsensor.NumericSensor // RMS current sensor
	PeakCurrent             numericsensor.NumericSensor // Peak current sensor
	ActivePower             numericsensor.NumericSensor // Active power sensor
	ReactivePower           numericsensor.NumericSensor // Reactive power sensor
	ApparentPower           numericsensor.NumericSensor // Apparent power sensor
	PowerFactor             numericsensor.NumericSensor // Power factor sensor
	PhaseAngle              numericsensor.NumericSensor // Phase angle sensor
	DisplacementPowerFactor numericsensor.NumericSensor // Displacement power factor sensor
	ActiveEnergy            numericsensor.NumericSensor // Active energy sensor
	ApparentEnergy          numericsensor.NumericSensor // Apparent energy sensor
	CrestFactor             numericsensor.NumericSensor // Crest factor sensor
	VoltageThd              numericsensor.NumericSensor // Voltage total harmonic distortion sensor
	CurrentThd              numericsensor.NumericSensor // Current total harmonic distortion sensor
}

// for OCP
type DoublePole struct {
	Label          string                      // Pole label
	Line           PowerLine                   // Power line
	InNodeId       int32                       // Upstream (inlet-side) circuit node id
	OutNodeId      int32                       // Downstream (outlet-side) circuit node id
	Voltage        numericsensor.NumericSensor // RMS voltage sensor, L-L
	VoltageLN      numericsensor.NumericSensor // RMS voltage sensor, L-N
	Current        numericsensor.NumericSensor // RMS current sensor
	PeakCurrent    numericsensor.NumericSensor // Peak current sensor
	ActivePower    numericsensor.NumericSensor // Active power sensor
	ApparentPower  numericsensor.NumericSensor // Apparent power sensor
	PowerFactor    numericsensor.NumericSensor // Power factor sensor
	ActiveEnergy   numericsensor.NumericSensor // Active energy sensor
	ApparentEnergy numericsensor.NumericSensor // Apparent energy sensor
}

// A pole that can select one of multiple inputs
type ThrowPole struct {
	Label     string    // Pole label
	Line      PowerLine // Power line
	InNodeIds []int32   // Upstream node ids
	OutNodeId int32     // Downstream node id
}
