// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package outlet was generated by IDLC from Outlet.idl.
// It is part of module pdumodel.
// The remaining comment is for module pdumodel.
//
// PDU Model
package outlet

import (
	"context"
	"time"

	"github.com/arminguenther/xeruspower-go/v40010/event/userevent"
	"github.com/arminguenther/xeruspower-go/v40010/idl/event"
	"github.com/arminguenther/xeruspower-go/v40010/pdumodel/controller"
	"github.com/arminguenther/xeruspower-go/v40010/pdumodel/edevice"
	"github.com/arminguenther/xeruspower-go/v40010/pdumodel/inlet"
	"github.com/arminguenther/xeruspower-go/v40010/pdumodel/nameplate"
	"github.com/arminguenther/xeruspower-go/v40010/pdumodel/overcurrentprotector"
	"github.com/arminguenther/xeruspower-go/v40010/pdumodel/pole"
	"github.com/arminguenther/xeruspower-go/v40010/pdumodel/waveform"
	"github.com/arminguenther/xeruspower-go/v40010/sensors/numericsensor"
	"github.com/arminguenther/xeruspower-go/v40010/sensors/statesensor"
)

// Outlet statistics
type Statistic struct {
	RelayCycleCnt int32 // Relay switch count
	RelayFailCnt  int32 // Relay failure count
}

const (
	ERR_OUTLET_NOT_SWITCHABLE int32 = 1 // Outlet is not switchable
	ERR_LOAD_SHEDDING_ACTIVE  int32 = 2 // Load-shedding is enabled (deprecated)
	ERR_OUTLET_DISABLED       int32 = 3 // Outlet is disabled
	ERR_OUTLET_NOT_OFF        int32 = 4 // Outlet is on or in power-cylce; unstick not possible
	ERR_INVALID_PARAM         int32 = 1 // Invalid parameters
)

// Outlet interface
type Outlet interface {
	edevice.EDevice

	// Retrieve the outlet metadata.
	//
	//	@return Outlet metadata
	GetMetaData(ctx context.Context) (MetaData, error)

	// Get the outlet sensors.
	//
	//	@return Outlet sensors
	GetSensors(ctx context.Context) (Sensors, error)

	// Retrieve the outlet state.
	//
	//	@return Outlet state
	GetState(ctx context.Context) (State, error)

	// Switch the outlet.
	//
	//	@param pstate  New power state
	//
	//	@return 0 if OK
	//	@return 1 if the outlet is not switchable
	//	@return 3 if the outlet is disabled
	SetPowerState(ctx context.Context, pstate PowerState) (int32, error)

	// Power-cycle the outlet.
	//
	//	@return 0 if OK
	//	@return 1 if the outlet is not switchable
	//	@return 3 if the outlet is disabled
	CyclePowerState(ctx context.Context) (int32, error)

	// Retrieve the outlet settings.
	//
	//	@return Outlet settings
	GetSettings(ctx context.Context) (Settings, error)

	// Change the outlet settings.
	//
	//	@param settings  New outlet settings
	//
	//	@return 0 if OK
	//	@return 1 if any parameters are invalid
	SetSettings(ctx context.Context, settings Settings) (int32, error)

	// Get inlet, overcurrent protector and poles.
	//
	//	@param i  Result: Inlet reference
	//	@param o  Result: Overcurrent protector reference
	//	@param p  Result: List of poles
	GetIOP(ctx context.Context) (i inlet.Inlet, o overcurrentprotector.OverCurrentProtector, p []pole.Pole, err error)

	// Get the controller for this outlet.
	//
	//	@return Sub controller reference
	GetController(ctx context.Context) (controller.Controller, error)

	// Get the voltage and current waveforms at the time of last switch on operation.
	//
	//	@note If waveform reading is not supported or a waveform could not be acquired for other
	//	      reasons (e.g. the outlet not actually be switchable, or the outlet board being reset
	//	      since the outlet was turned on), an empty waveform is returned.
	//
	//	@return Waveform samples
	GetInrushWaveform(ctx context.Context) (waveform.Waveform, error)

	// Trigger an attempt to un-stick sticking relay contacts
	//
	// Warning: Please contact Tech Support before using this.
	//
	// Tries repairing relay contacts that are sticked together due to wear
	// by switching the relay in a certain pattern.
	// Prior to running this method, the outlet must be in 'off' state
	// to acknowledge that loads were disconnected.
	//
	//	@return 0 if unsticking was triggered successfully
	//	@return 1 if outlet is not switchable
	//	@return 3 if the outlet is disabled
	//	@return 4 if relay is in a power cycle or on
	Unstick(ctx context.Context) (int32, error)
}

// Outlet metadata
type MetaData struct {
	Label              string              // Outlet label
	ReceptacleType     string              // Receptacle type
	NamePlate          nameplate.Nameplate // Nameplate information
	Rating             nameplate.Rating    // Numerical usage ratings
	IsSwitchable       bool                // true if the outlet is switchable
	IsLatching         bool                // true if the outlet is able to keep its state after power loss
	MaxRelayCycleCnt   int32               // Maximum relay cycle count
	HasWaveformSupport bool                // Whether waveform reading is supported on this outlet
}

// Outlet power state. Used both for switching and representing the current state
type PowerState int

const (
	PS_OFF PowerState = iota // Switch off / Power is off
	PS_ON                    // Switch on / Power is on
)

// Deprecated:
// Outlet LED state
type LedState struct {
	Red      bool // true if the red LED is enabled
	Green    bool // true if the green LED is enabled
	Blinking bool // true if the LED is blinking
}

// Outlet state
type State struct {
	Available bool // powerState is available
	// Current power state of outlet
	// (represented by the control state of the relay, which
	// was set by the last command sent to it)
	PowerState PowerState
	// true if the outlet is pending to be switched on
	// after the sequencing delay has passed.
	SwitchOnInProgress bool
	// if a power-cycle is in progress. The outlet will
	// be switched on after the cycle delay has passed.
	CycleInProgress bool
	// true if the outlet is currently switched off due
	// to being non-critical and load shedding being active
	IsLoadShed bool
	// Whether the outlet was turned off automatically due to
	// being suspected to have caused an OCP trip event
	IsSuspended bool
	// Whether a valid waveform of last switch-on operation
	// can be read using {@link getInrushWaveform()}.
	HasInrushWaveform    bool
	LedState             LedState  // LED state (deprecated and always sent as 'off')
	LastPowerStateChange time.Time // Time of last power state change (UNIX timestamp, UTC)
}

// Outlet power state on device startup
type StartupState int

const (
	SS_ON        StartupState = iota // Outlet will be switched on
	SS_OFF                           // Outlet will be switched off
	SS_LASTKNOWN                     // Last known power state will be restored
	SS_PDUDEF                        // Use default state as defined in PDU settings
)

// Outlet settings
type Settings struct {
	Name             string       // User-defined name
	StartupState     StartupState // Power state after power is applied to the outlet
	UsePduCycleDelay bool         // true to use power-cycle delay as defined in PDU settings
	CycleDelay       int32        // Outlet-specific power-cycle delay
	NonCritical      bool         // true if outlet is non-critical (for load shedding)
	SequenceDelay    int32        // Delay in ms after this outlet when switching multiple outlets on
}

// Outlet sensors
type Sensors struct {
	Voltage                 numericsensor.NumericSensor // RMS voltage sensor (may be a VoltageMonitoringSensor)
	Current                 numericsensor.NumericSensor // RMS current sensor
	PeakCurrent             numericsensor.NumericSensor // Peak current sensor
	MaximumCurrent          numericsensor.NumericSensor // Maximum current sensor
	UnbalancedCurrent       numericsensor.NumericSensor // Current unbalance sensor
	ActivePower             numericsensor.NumericSensor // Active power sensor
	ReactivePower           numericsensor.NumericSensor // Reactive power sensor
	ApparentPower           numericsensor.NumericSensor // Apparent power sensor
	PowerFactor             numericsensor.NumericSensor // Power factor sensor
	DisplacementPowerFactor numericsensor.NumericSensor // Displacement power factor sensor
	ActiveEnergy            numericsensor.NumericSensor // Active energy sensor
	ApparentEnergy          numericsensor.NumericSensor // Apparent energy sensor
	PhaseAngle              numericsensor.NumericSensor // Phase angle sensor
	LineFrequency           numericsensor.NumericSensor // AC line frequency sensor
	CrestFactor             numericsensor.NumericSensor // Crest factor sensor
	VoltageThd              numericsensor.NumericSensor // Voltage total harmonic distortion sensor
	CurrentThd              numericsensor.NumericSensor // Current total harmonic distortion sensor
	InrushCurrent           numericsensor.NumericSensor // In-rush current occuring after turning outlet on
	OutletState             statesensor.StateSensor     // Outlet power state sensor
}

// Event: Power control was initiated
type PowerControlEvent interface {
	userevent.UserEvent
	State() PowerState // State the outlet was switched to (if cycle is false)
	Cycle() bool       // Whether the outlet was cycled
	isPowerControlEvent()
}

// Event: Outlet state has changed
type StateChangedEvent interface {
	event.Event
	OldState() State // State before change
	NewState() State // State after change
	isStateChangedEvent()
}

// Event: Outlet settings have been changed
type SettingsChangedEvent interface {
	userevent.UserEvent
	OldSettings() Settings // Settings before change
	NewSettings() Settings // Settings after change
	isSettingsChangedEvent()
}
