// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package outletgroup was generated by IDLC from OutletGroup.idl.
// It is part of module pdumodel.
// The remaining comment is for module pdumodel.
package outletgroup

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40211/event/userevent"
	"github.com/arminguenther/xeruspower-go/v40211/idl"
	"github.com/arminguenther/xeruspower-go/v40211/idl/event"
	"github.com/arminguenther/xeruspower-go/v40211/pdumodel/outlet"
	"github.com/arminguenther/xeruspower-go/v40211/sensors/accumulatingnumericsensor"
	"github.com/arminguenther/xeruspower-go/v40211/sensors/numericsensor"
)

const ERR_INVALID_ARGUMENT int32 = 1

// Outlet group interface
type OutletGroup interface {
	idl.Object

	// Retrieve the outlet group sensors.
	//
	//	@return outlet group sensors
	GetSensors(ctx context.Context) (Sensors, error)

	// Retrieve the outlet group metadata.
	//
	//	@return outlet group metadata
	GetMetaData(ctx context.Context) (MetaData, error)

	// Retrieve the outlet group settings.
	//
	//	@return outlet group settings
	GetSettings(ctx context.Context) (Settings, error)

	// Change the outlet group settings.
	//
	//	@param settings  New outlet group settings
	//
	//	@return 0 if OK
	//	@return 1 if any parameters are invalid
	SetSettings(ctx context.Context, settings Settings) (int32, error)

	// Switch all member outlets.
	//
	//	@param pstate  New power state for all outlets
	//
	//	@return 0 if OK
	SetAllOutletPowerStates(ctx context.Context, pstate outlet.PowerState) (int32, error)

	// Power-cycle all member outlets.
	//
	//	@return 0 if OK
	CycleAllOutletPowerStates(ctx context.Context) (int32, error)
}

// Outlet group sensors
type Sensors struct {
	ActivePower    numericsensor.NumericSensor                         // Active power sensor
	ApparentPower  numericsensor.NumericSensor                         // Apparent power sensor
	ActiveEnergy   accumulatingnumericsensor.AccumulatingNumericSensor // Active energy sensor
	ApparentEnergy accumulatingnumericsensor.AccumulatingNumericSensor // Apparent energy sensor
}

// Outlet group settings
type Settings struct {
	Name    string          // User-defined name
	Members []outlet.Outlet // List of member outlets
}

// Outlet group metadata
type MetaData struct {
	// (ID) Value under which OutletGroupManager references this group,
	// unique only for a given point in time
	GroupId int32
	// (Random) ID value uniquely identifying this group,
	// even after group deletions and creations of new groups
	UniqueId int32
}

// Event: Group sensors have changed
type SensorsChangedEvent interface {
	event.Event
	OldSensors() Sensors // Sensors before change
	NewSensors() Sensors // Sensors after change
	isSensorsChangedEvent()
}

// Event: Group settings have been changed
type SettingsChangedEvent interface {
	userevent.UserEvent
	OldSettings() Settings // Settings before change
	NewSettings() Settings // Settings after change
	isSettingsChangedEvent()
}

// Event: Group switch operation has been invoked
type PowerControlEvent interface {
	userevent.UserEvent
	State() outlet.PowerState // Target power state, only valid if not cycling
	Cycle() bool              // Whether a power cycle operation was invoked
	isPowerControlEvent()
}
