// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package cardreader was generated by IDLC from CardReader.idl.
// It is part of module smartcard.
// The remaining comment is for module smartcard.
//
// Card Reader
package cardreader

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40412/idl"
	"github.com/arminguenther/xeruspower-go/v40412/idl/event"
)

// Error codes
const (
	NO_ERROR       int32 = 0 // operation successful, no error
	ERR_SLOT_EMPTY int32 = 1 // no card present in reader
)

// Card Reader Interface
type CardReader interface {
	idl.Object

	// Retrieve reader metadata.
	//
	//	@return metadata
	GetMetaData(ctx context.Context) (MetaData, error)

	// Retrieve card information from reader.
	//
	//	@param cardInfo    Card Information
	//
	//	@return NO_ERROR                     if OK
	//	@return ERR_SLOT_EMPTY               if reader sees no card
	GetCardInformation(ctx context.Context) (ret int32, cardInfo CardInformation, err error)
}

// Reader Metadata
type MetaData struct {
	Id           string // Card reader ID used in events and traps
	Manufacturer string // manufacturer
	Product      string // product
	SerialNumber string // serial number (S/N)
	Channel      int32  // one device (S/N) can provide multiple readers
	// Position of the card reader.
	// Contains either the position in the 1-wire topology and the
	// channel (e.g. D1:H1:C1-1) or, for usb card readers, a string like
	// usb:<n> where n is a number increasing with usb card readers.
	Position string
}

// Card Information
type CardInformation struct {
	Type string // card type
	Uid  string // card id
}

// Card base event
type CardEvent interface {
	event.Event
	MetaData() MetaData // MetaData of this card reader
	isCardEvent()
}

// Card inserted event
//
// Fetch Card ID by calling getCardInformation() on this card reader
type CardInsertedEvent interface {
	CardEvent
	isCardInsertedEvent()
}

// Card removed event
type CardRemovedEvent interface {
	CardEvent
	isCardRemovedEvent()
}
