// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Code generated by "stringer -output=enum_strings.go -type=StorageType,StorageStatus,Direction"; DO NOT EDIT.

package storagemanager

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LOCAL-0]
	_ = x[FTP-1]
	_ = x[CIFS-2]
	_ = x[NFS-3]
}

const _StorageType_name = "LOCALFTPCIFSNFS"

var _StorageType_index = [...]uint8{0, 5, 8, 12, 15}

func (i StorageType) String() string {
	if i < 0 || i >= StorageType(len(_StorageType_index)-1) {
		return "StorageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StorageType_name[_StorageType_index[i]:_StorageType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INITIALIZING-0]
	_ = x[READY-1]
}

const _StorageStatus_name = "INITIALIZINGREADY"

var _StorageStatus_index = [...]uint8{0, 12, 17}

func (i StorageStatus) String() string {
	if i < 0 || i >= StorageStatus(len(_StorageStatus_index)-1) {
		return "StorageStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StorageStatus_name[_StorageStatus_index[i]:_StorageStatus_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ASCENDING-0]
	_ = x[DESCENDING-1]
}

const _Direction_name = "ASCENDINGDESCENDING"

var _Direction_index = [...]uint8{0, 9, 19}

func (i Direction) String() string {
	if i < 0 || i >= Direction(len(_Direction_index)-1) {
		return "Direction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Direction_name[_Direction_index[i]:_Direction_index[i+1]]
}
