// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package storagemanager was generated by IDLC from StorageManager.idl.
// It is part of module webcam.
// The remaining comment is for module webcam.
//
// Webcam Management
package storagemanager

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40000/event/userevent"
	"github.com/arminguenther/xeruspower-go/v40000/idl"
	"github.com/arminguenther/xeruspower-go/v40000/webcam/webcam"
)

// Error codes
const (
	NO_ERROR                    int32 = 0 // Operation successful, no error
	ERR_INVALID_PARAM           int32 = 1 // Invalid parameter for an operation
	ERR_INIT_IN_PROGRESS        int32 = 2 // Storage information is going to be initialized
	ERR_ALREADY_RUNNING         int32 = 3 // The activity is already running
	ERR_TOO_LARGE               int32 = 4 // The requested result is too large
	ERR_OPERATION_NOT_SUPPORTED int32 = 5 // The requested operation is not supported on the current storage type
)

// The storage manager interface
type StorageManager interface {
	idl.Object

	// Get supported storage types
	//
	//	@return a list of supported storage types
	GetSupportedStorageTypes(ctx context.Context) ([]StorageType, error)

	// get storage information
	//
	//	@return StorageInformation
	GetInformation(ctx context.Context) (StorageInformation, error)

	// get storage settings
	//
	//	@return StorageSettings
	GetSettings(ctx context.Context) (StorageSettings, error)

	// set storage settings
	//
	//	@param  settings             settings structure
	//
	//	@return NO_ERROR             on success
	//	@return ERR_INVALID_PARAM    invalid settings
	SetSettings(ctx context.Context, settings StorageSettings) (int32, error)

	// add an image to the storage
	//
	//	@param  webcam               image source webcam
	//	@param  image                image
	//	@param  index                index of the added image
	//
	//	@return NO_ERROR             on success
	AddImage(ctx context.Context, webcam webcam.Webcam, image webcam.Image) (ret int32, index int64, err error)

	// remove an image of the storage
	//
	//	@note not supported for remote storage (CIFS and FTP)
	//
	//	@param  webcam               image source webcam
	//	@param  start                start index
	//	@param  count                number of images
	//	@param  direction            index counting direction
	//
	//	@return NO_ERROR             on success
	RemoveImages(ctx context.Context, webcam webcam.Webcam, start int64, count int32, direction Direction) (int32, error)

	// get meta data of images from storage
	//
	//	@note not supported for remote storage (CIFS and FTP)
	//
	//	@param  webcam               image source webcam
	//	@param  start                start index
	//	@param  count                number of images
	//	@param  direction            index counting direction
	//	@param  meta                 result: list of storage meta data
	//
	//	@return NO_ERROR             on success
	//	@return ERR_TOO_LARGE        too many information requested
	GetMetaData(ctx context.Context, webcam webcam.Webcam, start int64, count int32, direction Direction) (ret int32, meta []ImageStorageMetaData, err error)

	// retrieve images from the storage
	//
	//	@note not supported for remote storage (CIFS and FTP)
	//
	//	@param  webcam               image source webcam
	//	@param  start                start index
	//	@param  count                number of images
	//	@param  direction            index counting direction
	//	@param  image                result: list of storage images
	//
	//	@return NO_ERROR             on success
	//	@return ERR_TOO_LARGE        too many images requested
	GetImages(ctx context.Context, webcam webcam.Webcam, start int64, count int32, direction Direction) (ret int32, image []StorageImage, err error)

	// get all running activities
	//
	//	@return list of running activities
	GetActivities(ctx context.Context) ([]Activity, error)

	// start a capture activity
	//
	//	@param  webcam               webcam
	//	@param  count                number of images to store, zero is interpreted as infinite
	//	@param  interval             interval in ms
	//
	//	@return NO_ERROR             on success
	//	@return ERR_INVALID_PARAM    webcam not found
	StartActivity(ctx context.Context, webcam webcam.Webcam, count int32, interval int32) (int32, error)

	// Start a capture activity, storing the images to a specific storage folder
	//
	//	@param  webcam               webcam
	//	@param  count                number of images to store, zero is interpreted as infinite
	//	@param  interval             interval in ms
	//	@param  folder               folder path to store the images into
	//
	//	@return NO_ERROR             on success
	//	@return ERR_INVALID_PARAM    webcam not found
	StartActivityWithFolder(ctx context.Context, webcam webcam.Webcam, count int32, interval int32, folder string) (int32, error)

	// stop a capture activity
	//
	//	@param  webcam               webcam
	//
	//	@return NO_ERROR             on success
	//	@return ERR_INVALID_PARAM    no matching activity found
	StopActivity(ctx context.Context, webcam webcam.Webcam) (int32, error)
}

// StorageType
type StorageType int

const (
	LOCAL StorageType = iota // Local
	FTP                      // FTP
	CIFS                     // CIFS
	NFS                      // NFS
)

// Direction
type Direction int

const (
	ASCENDING  Direction = iota // ascending
	DESCENDING                  // descending
)

// StorageStatus
type StorageStatus int

const (
	INITIALIZING StorageStatus = iota // Initializing is in progress,
	READY                             // Storage is ready for usage
)

// Webcam Storage Info
type WebcamStorageInfo struct {
	Webcam      webcam.Webcam // webcam object
	NewestIndex int64         // newest know index
	OldestIndex int64         // oldest know index
	Count       int32         // nr of stored images from this webcam
}

// Information
type StorageInformation struct {
	Status            StorageStatus       // storage status
	Capacity          int32               // over-all nr of storable images
	Used              int32               // nr of stored images (local storage only)
	WebcamStorageInfo []WebcamStorageInfo // List of storage information for each webcam (local storage only)
}

// Settings
type StorageSettings struct {
	Type     StorageType // storage type
	Capacity int32       // maximum number of stored images; obsolete, no longer used
	Server   string      // server ip, share and path (empty/ignored for LOCAL storage type)
	Username string      // username  (empty/ignored for LOCAL storage type)
	Password string      // password  (empty/ignored for LOCAL storage type)
}

// StorageMetaData
type StorageMetaData struct {
	Index  int64         // current image index
	Webcam webcam.Webcam // source webcam
}

// StorageMetaData
type ImageStorageMetaData struct {
	ImageMeta   webcam.ImageMetaData // image related meta data
	FileSize    int32                // image file size in bytes
	StorageMeta StorageMetaData      // store related meta data
}

// StorageImage
type StorageImage struct {
	Image    webcam.Image    // image object
	MetaData StorageMetaData // meta data
}

// Activity
type Activity struct {
	Webcam   webcam.Webcam // webcam object
	Interval int32         // capture interval
	Count    int32         // nr of images to take
	Done     int32         // nr of images taken
}

// Event: image upload to storage started
type ImageUploadStartedEvent interface {
	userevent.UserEvent
	Webcam() webcam.Webcam // webcam object
	FolderUrl() string     // URL under which the containing folder can be accessed
	isImageUploadStartedEvent()
}
