// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package edevice was generated by IDLC from EDevice.idl.
// It is part of module pdumodel.
// The remaining comment is for module pdumodel.
//
// PDU Model
package edevice

import (
	"context"

	"github.com/arminguenther/xeruspower-go/idl"
	"github.com/arminguenther/xeruspower-go/pdumodel/pole"
	"github.com/arminguenther/xeruspower-go/pdumodel/waveform"
)

// Common base interface for any kind of electrical device that is used
// in the PDU model, such as inlets, OCPs and outlets.
//
// EDevices form a hierarchy of parent-child relationships. An EDevice is
// defined to be the parent of another if it "provides energy" to the
// latter. E.g. an inlet could be the parent of a number of OCPs,
// wires or outlets.
//
// An EDevice can have multiple parents, e.g. in case of transfer switches
// which select power from multiple sources.
type EDevice interface {
	idl.Object

	// Get the list of devices that provide energy to this device.
	//
	//	@return List of parent devices
	GetParents(ctx context.Context) ([]EDevice, error)

	// Get the list of devices that are directly fed by this device.
	//
	//	@return List of child devices
	GetChildren(ctx context.Context) ([]EDevice, error)

	// Get the current voltage and current waveforms for this device.
	//
	//	@note If waveform reading is not supported, an empty waveform is returned.
	//
	//	@return Waveform samples
	GetWaveform(ctx context.Context) (waveform.Waveform, error)

	// Get the current voltage and current waveforms for a pole of this device.
	//
	//	@note If waveform reading is not supported, an empty waveform is returned.
	//
	//	@return Waveform samples
	GetPoleWaveform(ctx context.Context, line pole.PowerLine) (waveform.Waveform, error)
}
