// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package dsammanager was generated by IDLC from DsamManager.idl.
// It is part of module dsam.
// The remaining comment is for module dsam.
package dsammanager

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40412/dsam/dsamdevice"
	"github.com/arminguenther/xeruspower-go/v40412/idl"
	"github.com/arminguenther/xeruspower-go/v40412/idl/event"
)

// DSAM manager interface
type DsamManager interface {
	idl.Object

	// Retrieve the current DSAM devices.
	//
	//	@return Map with DSAM devices. Index is the DSAM number (1-based).
	GetDsamDevices(ctx context.Context) (map[int32]dsamdevice.DsamDevice, error)

	// Get the version of the firmware file provided with the device that will be installed on the DSAM
	// either by explicit request or when the DSAM needs to be recovered.
	//
	//	@return Firmware version
	GetFirmwareUpdateFileVersion(ctx context.Context) (dsamdevice.FirmwareVersion, error)
}

// Event that is sent when a DSAM module has been attached
type DsamAttachedEvent interface {
	event.Event
	Info() dsamdevice.Info         // DSAM info
	Device() dsamdevice.DsamDevice // DSAM device
	isDsamAttachedEvent()
}

// Event that is sent when a DSAM module has been removed
type DsamDetachedEvent interface {
	event.Event
	Info() dsamdevice.Info // DSAM info
	isDsamDetachedEvent()
}

// Event that is sent when a DSAM controller has been reset or recovery is in progress
type DsamControllerChangedEvent interface {
	event.Event
	DsamNumber() int32   // DSAM number (1-based)
	Reset() bool         // true if controller was reset; false if recovery started
	ResetReason() string // reset reason (only set when reset is true)
	isDsamControllerChangedEvent()
}
