// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package nameservice was generated by IDLC from NameService.idl.
// It is part of module jsonrpc.
// The remaining comment is for module jsonrpc.
//
// Raritan JSON-RPC
package nameservice

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40411/idl"
)

// RPC Object Name Service
type NameService interface {
	idl.Object

	// Find an RPC object by its resource ID or well-known name.
	//
	//	@param name  Resource id or well-known name
	//
	//	@return Object reference; nil if the name can't be resolved
	Lookup(ctx context.Context, name string) (idl.Object, error)
}
