// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package externalbeeper was generated by IDLC from ExternalBeeper.idl.
// It is part of module hmi.
// The remaining comment is for module hmi.
//
// Human Machine Interface
package externalbeeper

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40412/idl"
	"github.com/arminguenther/xeruspower-go/v40412/idl/event"
)

// External Beeper interface
type ExternalBeeper interface {
	idl.Object

	// Get current beeper state
	GetState(ctx context.Context) (State, error)

	// Start beeper alarm
	//
	// Starts and repeats an alarm sequence of beeper on and beeper off.
	// The sequence will be infinitely repeated until "off" is called.
	Alarm(ctx context.Context) error

	// Turn beeper on
	//
	// Enables the beeper sound.
	On(ctx context.Context) error

	// Turn beeper off
	//
	// Disables beeper sound and also stops beeper alarm.
	Off(ctx context.Context) error
}

// Beeper state
type State int

const (
	OFF State = iota
	ON
	ALARMING
)

// Event: beeper state has changed
type StateChangedEvent interface {
	event.Event
	OldState() State
	NewState() State
	isStateChangedEvent()
}
