// Code generated by "stringer -output=enum_strings.go -type=EventType,EngineConditionOp,EngineConditionMatchType,EngineEventDescType"; DO NOT EDIT.

package eventengine

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[STATE-0]
	_ = x[TRIGGER-1]
}

const _EventType_name = "STATETRIGGER"

var _EventType_index = [...]uint8{0, 5, 12}

func (i EventType) String() string {
	if i < 0 || i >= EventType(len(_EventType_index)-1) {
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AND-0]
	_ = x[OR-1]
	_ = x[XOR-2]
}

const _EngineConditionOp_name = "ANDORXOR"

var _EngineConditionOp_index = [...]uint8{0, 3, 5, 8}

func (i EngineConditionOp) String() string {
	if i < 0 || i >= EngineConditionOp(len(_EngineConditionOp_index)-1) {
		return "EngineConditionOp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EngineConditionOp_name[_EngineConditionOp_index[i]:_EngineConditionOp_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ASSERTED-0]
	_ = x[DEASSERTED-1]
	_ = x[BOTH-2]
}

const _EngineConditionMatchType_name = "ASSERTEDDEASSERTEDBOTH"

var _EngineConditionMatchType_index = [...]uint8{0, 8, 18, 22}

func (i EngineConditionMatchType) String() string {
	if i < 0 || i >= EngineConditionMatchType(len(_EngineConditionMatchType_index)-1) {
		return "EngineConditionMatchType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EngineConditionMatchType_name[_EngineConditionMatchType_index[i]:_EngineConditionMatchType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NODE-0]
	_ = x[DYN_NODE-1]
	_ = x[LEAF-2]
}

const _EngineEventDescType_name = "NODEDYN_NODELEAF"

var _EngineEventDescType_index = [...]uint8{0, 4, 12, 16}

func (i EngineEventDescType) String() string {
	if i < 0 || i >= EngineEventDescType(len(_EngineEventDescType_index)-1) {
		return "EngineEventDescType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EngineEventDescType_name[_EngineEventDescType_index[i]:_EngineEventDescType_index[i+1]]
}
