// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package eventengine was generated by IDLC from EventEngine.idl.
// It is part of module event.
// The remaining comment is for module event.
//
// Event interface
package eventengine

import (
	"context"
	"time"

	"github.com/arminguenther/xeruspower-go/v40000/idl"
)

// Helper that is used wherever key/value pairs are required.
//
//	@note This interface was designed before IDL maps were supported.
type KeyValue struct {
	Key   string // Key
	Value string // Value
}

// Event has a type:
//
//	a STATE event indicates that a boolean state has been
//	  changed, i.e. asserted or deasserted
//	a TRIGGER event is one that has no state assigned.
//	  conceptually it is asserted and deasserted at once.
//
// The id has multiple components that form a path into a hierarchy.
// The value ("asserted") indicates whether the state has become
// true (assertion) or false (deassertion). For events of type TRIGGER
// this will be true always.
type Event struct {
	Type      EventType  // Event type
	Id        []string   // Event id vector
	Asserted  bool       // Assertion value
	TimeStamp time.Time  // UNIX timestamp (UTC)
	Context   []KeyValue // Context map
}

// Event type
type EventType int

const (
	STATE   EventType = iota // State event
	TRIGGER                  // Trigger event
)

// There is a single event engine instance reachable by a well known
// reference.
type Engine interface {
	idl.Object

	// Query existing event descriptors.
	//
	//	@return 0 if OK
	//	@return 1 if id was not found
	ListEventDescs(ctx context.Context, eventIdPrefix []string) (ret int32, eventDescs []EngineEventDesc, err error)

	// List all available action types. The action type is intentionally
	// defined generically so that implementation can be extensible without
	// changing interface.
	ListActionTypes(ctx context.Context) ([]string, error)

	// Add a new action.
	//
	// The id and isSystem fields are ignored. The actions's id field is
	// allocated automatically and returned in the actionId parameter.
	//
	//	@return 0 if OK
	//	@return 1 if the name of the new action already exists
	//	@return 2 if generating the action id failed
	//	@return 3 if the maximum number of actions have been created
	AddAction(ctx context.Context, action EngineAction) (ret int32, actionId string, err error)

	// Modify an action.
	//
	//	@return 0 if OK
	//	@return 1 if the name of the new action already exists
	//	@return 2 if the action id does not exist
	ModifyAction(ctx context.Context, action EngineAction) (int32, error)

	// Remove an action.
	//
	//	@return 0 if OK
	//	@return 1 if id is unknown
	//	@return 2 if the action is not deletable
	DeleteAction(ctx context.Context, actionId string) (int32, error)

	// List all actions currently know to this event engine.
	ListActions(ctx context.Context) ([]EngineAction, error)

	// Trigger an action.
	//
	// This is mainly used for test and debugging. The operation will
	// block until the action has been performed or an error occurred.
	// In the latter case errMsg will contain an error message. The
	// context is passed to the actions.
	//
	// NOTE: Currently this function doesn't block!
	//
	//	@return 0 if OK
	//	@return 1 if id is unknown
	//	@return 2 if no actor was found for the action
	//	@return 3 if performing the action failed, errmsg will be set
	TriggerAction(ctx context.Context, actionId string, context []KeyValue) (ret int32, errMsg string, err error)

	// Test an action.
	//
	// This is similar to {@link triggerAction}, except that an action
	// that is not yet saved can be passed in. Therefore this method
	// can be used for testing actions to be newly created. The
	// operation will block until the action has been performed or an
	// error occurred. In the latter case errMsg will contain an error
	// message. The context is passed to the actions.
	//
	// NOTE: Currently this function doesn't block!
	//
	//	@return 0 if OK
	//	@return 1 if the action name is invalid
	//	@return 2 if no actor was found for the action
	//	@return 3 if performing the action failed, errmsg will be set
	TestAction(ctx context.Context, action EngineAction, context []KeyValue) (ret int32, errMsg string, err error)

	// Add a new rule.
	//
	// The id, hasMatched and isSystem fields are ignored. The rule's
	// id field is allocated automatically and returned in the the ruleId
	// parameter.
	//
	//	@return 0 if OK
	//	@return 1 if the name of the new rule already exists
	//	@return 2 if generating the rule id failed
	//	@return 3 if the rule condition contains an invalid event id
	//	@return 4 if the maximum number of rules have been created
	//	@return 5 if the maximum number of actions per rule is exceeded
	AddRule(ctx context.Context, rule EngineRule) (ret int32, ruleId string, err error)

	// Modify a rule.
	//
	// The hasMatched and isSystem fields are ignored.
	//
	//	@return 0 if OK
	//	@return 1 if the name of the new rule already exists
	//	@return 2 if the rule id does not exist
	//	@return 3 if the rule condition contains an invalid event id
	//	@return 4 if the maximum number of actions per rule is exceeded
	ModifyRule(ctx context.Context, rule EngineRule) (int32, error)

	// Enable a rule.
	//
	// An enabled rule will be evaluated when processing events.
	//
	//	@return 0 if OK
	//	@return 1 if id is unknown
	EnableRule(ctx context.Context, ruleId string) (int32, error)

	// Disable a rule.
	//
	// A disabled rule will be ignored when processing events.
	//
	//	@return 0 if OK
	//	@return 1 if ruleId is unknown
	DisableRule(ctx context.Context, ruleId string) (int32, error)

	// Delete a rule.
	//
	//	@return 0 if OK
	//	@return 1 if ruleId is unknown
	//	@return 2 if the rule is not deletable
	DeleteRule(ctx context.Context, ruleId string) (int32, error)

	// List all rules.
	//
	// Question: will number of rules be small enough to list them
	//
	//	all in a single operation.
	//	A single Rule may be quite large...
	//	See below for alternative interface using iterator.
	ListRules(ctx context.Context) ([]EngineRule, error)

	// Deliver an event.
	//
	//	@return 0 if OK
	//	@return 1 if event is unknown
	DeliverEvent(ctx context.Context, event Event) (int32, error)

	// Rearm an event rule that is active.
	//
	// Once a Rule triggers its actions it is done once. If the condition
	// of the rules becomes false and back again true, no action will be
	// performed unless the rule is rearmed. Rules may be auto-rearmed what
	// means whenever the rule's conditions changes from false to true
	// actions are triggered over and again.
	//
	//	@return 0 if OK
	//	@return 1 if the rule is unknown
	//	@return 2 if the rule is not enabled
	RearmRule(ctx context.Context, ruleId string) (int32, error)
}

// An event descriptor.
//
// In case eventDescType is LEAF then the descriptor refers to a
// 'real' event. In this case eventType is set and the entries vector
// is empty. Otherwise eventType is a don't care and the entries vector
// contains sub-entries. In case eventDescType is DYN_NODE then the
// dynNodeContext contains a key which is used to generate a dynamic
// node.
type EngineEventDesc struct {
	EventDescType  EngineEventDescType // Event descriptor type
	EventType      EventType           // Event type
	DynNodeContext string              // Dynamic node context
	IdComp         string              // Event ID component
	Name           string              // User-defined name
	Entries        []EngineEventDesc   // Child nodes
}

// Event descriptor type
type EngineEventDescType int

const (
	NODE     EngineEventDescType = iota // Intermediate node
	DYN_NODE                            // Dynamic node
	LEAF                                // Leaf node
)

// An action is a tuple of 'id' (unique within the scope of this event
// engine), 'name' which is unique as well and used by the GUI as user
// readable identificator, 'isSystem' which denotes the action as
// system action, 'type' which defines what it is, and an argument
// vector that vary depending on type and which is passed to the action.
// The 'isSystem' flag is readonly and if set marks the action as not
// deletable.
type EngineAction struct {
	Id        string     // Action ID
	Name      string     // User-defined name
	IsSystem  bool       // true for system-defined actions
	Type      string     // Action type
	Arguments []KeyValue // Action argument map
}

// Condition is a logical combination of multiple events. Normally you
// should use STATE events in logical conditions. In case a TRIGGER
// event is part of a condition or logical operation it will per
// default be interpreted as deasserted. The TRIGGER will evaluate as
// asserted if that exact event was raised and is matched against the
// event rules. In some sense the 'assertion state' of the TRIGGER is
// true only at the moment the Event exists and set to false again once
// it passed.
type EngineCondition struct {
	Negate     bool                     // Negate the result
	Operation  EngineConditionOp        // Logical operation to be applied
	MatchType  EngineConditionMatchType // Match type
	EventId    []string                 // Event ID
	Conditions []EngineCondition        // List of subordinate conditions
}

// logical operation to be applied over all conditions and event
type EngineConditionOp int

const (
	AND EngineConditionOp = iota // Logical And
	OR                           // Logical Or
	XOR                          // Exclusive Or
)

// the match type how to match the event assertion state
type EngineConditionMatchType int

const (
	ASSERTED   EngineConditionMatchType = iota // Match if the event is asserted
	DEASSERTED                                 // Match if the event is deasserted
	BOTH                                       // Match both (for trigger events)
)

// A Rule binds an action to a condition.
//
// The 'id' is an unique identification within the scope of this event
// engine. The 'name' is unique as well and used by the GUI as user
// readable identificator. The flag 'isAutoRearm' determines whether
// actions are triggered again after condition reoccurres. The
// 'hasMatched' flag is true if the condition was true once and the rule
// is not rearmed yet. The 'isSystem' flag is readonly and if set marks
// the action as not deletable. The 'actionIds' are the actions to
// perform if the rule evaluates to true. The arguments are passed to
// the actions.
type EngineRule struct {
	Id          string          // Rule ID
	Name        string          // User-defined name
	IsSystem    bool            // true for system-defined rules
	IsEnabled   bool            // true if the rule is enabled
	IsAutoRearm bool            // true for auto-rearming rules
	HasMatched  bool            // true if the rule has matched since being armed
	Condition   EngineCondition // Trigger condition
	ActionIds   []string        // List of action IDs
	Arguments   []KeyValue      // Argument map
}
