// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package residualcurrentstatesensor was generated by IDLC from ResidualCurrentStateSensor.idl.
// It is part of module pdumodel.
// The remaining comment is for module pdumodel.
//
// PDU Model
package residualcurrentstatesensor

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40040/sensors/statesensor"
)

// Possible sensor state values
const (
	STATE_NORMAL   int32 = 0 // Residual current sensor is operating normally
	STATE_WARNING  int32 = 1 // Residual current sensor detected overcurrent
	STATE_CRITICAL int32 = 2 // Residual current sensor detected overcurrent
	STATE_SELFTEST int32 = 3 // Residual current sensor currently conducts a self test
	STATE_FAILURE  int32 = 4 // Residual current sensor is unavailable or self test failed
)

// Residual current state sensor interface
type ResidualCurrentStateSensor interface {
	statesensor.StateSensor

	// Start a self test of the residual current monitor
	//
	//	@return 0 if OK
	//	@return 1 if no residual current monitor is present
	//	@return 2 if a self test is already running
	StartSelfTest(ctx context.Context) (int32, error)
}
