// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Code generated by "stringer -output=enum_strings.go -type=Orientation,StartupState"; DO NOT EDIT.

package pdu

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PO_NONE-0]
	_ = x[PO_BOTTOMFEED-1]
	_ = x[PO_TOPFEED-2]
}

const _Orientation_name = "PO_NONEPO_BOTTOMFEEDPO_TOPFEED"

var _Orientation_index = [...]uint8{0, 7, 20, 30}

func (i Orientation) String() string {
	if i < 0 || i >= Orientation(len(_Orientation_index)-1) {
		return "Orientation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Orientation_name[_Orientation_index[i]:_Orientation_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SS_ON-0]
	_ = x[SS_OFF-1]
	_ = x[SS_LASTKNOWN-2]
}

const _StartupState_name = "SS_ONSS_OFFSS_LASTKNOWN"

var _StartupState_index = [...]uint8{0, 5, 11, 23}

func (i StartupState) String() string {
	if i < 0 || i >= StartupState(len(_StartupState_index)-1) {
		return "StartupState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StartupState_name[_StartupState_index[i]:_StartupState_index[i+1]]
}
