// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package webcammanager was generated by IDLC from WebcamManager.idl.
// It is part of module webcam.
// The remaining comment is for module webcam.
//
// Webcam Management
package webcammanager

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40032/idl"
	"github.com/arminguenther/xeruspower-go/v40032/idl/event"
	"github.com/arminguenther/xeruspower-go/v40032/webcam/webcam"
	"github.com/arminguenther/xeruspower-go/v40032/webcam/webcamchannel"
)

// Priority
type Priority int

const (
	VERY_LOW  Priority = iota // very low
	LOW                       // low
	NORMAL                    // normal
	HIGH                      // high
	VERY_HIGH                 // very high
)

// Base type of all webcam event
type WebcamEvent interface {
	event.Event
	Webcam() webcam.Webcam           // The webcam which was affected
	Information() webcam.Information // Information about the camera
	Name() string                    // The user-assigned camera name
	isWebcamEvent()
}

// This event is emitted after a webcam was added
type WebcamAddedEvent interface {
	WebcamEvent
	isWebcamAddedEvent()
}

// This event is emitted after a webcam has been removed
type WebcamRemovedEvent interface {
	WebcamEvent
	isWebcamRemovedEvent()
}

// Error codes
const (
	NO_ERROR          int32 = 0 // Operation successful, no error
	ERR_INVALID_PARAM int32 = 1 // Invalid parameter for an operation
)

// The webcam manager interface
type WebcamManager interface {
	idl.Object

	// Retrieve all connected webcams.
	//
	//	@return List of webcams
	GetWebcams(ctx context.Context) ([]webcam.Webcam, error)

	// Returns an existing channel that is currently viewing the given webcam or creates one
	// If the client type is unknown it's added to the list of client types.
	//
	// Note: When a new channel is created the priority of the given webcam and
	// channel type is summed up. The result is used to determine the used overall priority.
	//
	//	@param  webcam               webcam
	//	@param  clientType           the channel client type -> @ref getClientTypes()
	//	@param  channel              Result: The channel
	//
	//	@return NO_ERROR             on success
	//	@return ERR_INVALID_PARAM    one of the parameters is invalid
	GetChannel(ctx context.Context, webcam webcam.Webcam, clientType string) (ret int32, channel webcamchannel.Channel, err error)

	// Returns all channels. Note: you need to release every unneeded channel
	//
	//	@return List of all channels
	GetChannels(ctx context.Context) ([]webcamchannel.Channel, error)

	// Remove a client type
	//
	//	@param  clientType           client type
	//
	//	@return NO_ERROR             on success
	//	@return ERR_INVALID_PARAM    one of the parameters is invalid
	RemoveClientType(ctx context.Context, clientType string) (int32, error)

	// Get all known client types
	//
	//	@return List of all client types
	GetClientTypes(ctx context.Context) ([]string, error)

	// Get the priority of all known client types
	//
	//	@return a hash map with the key "event type ID" and the value "priority"
	GetClientTypePriorities(ctx context.Context) (map[string]Priority, error)

	// Set the priority of a client type
	//
	//	@param  priorities           a hash map with the key "event type ID" and the value "priority"
	//
	//	@return NO_ERROR             on success
	//	@return ERR_INVALID_PARAM    one of the parameters is invalid
	SetClientTypePriorities(ctx context.Context, priorities map[string]Priority) (int32, error)

	// Get the priority of a webcam
	//
	//	@return a hash map with the key "webcam ID" and the value "priority"
	GetWebcamPriorities(ctx context.Context) (map[string]Priority, error)

	// Set the priority of a webcam
	//
	//	@param  priorities           a hash map with the key "webcam ID" and the value "priority"
	//
	//	@return NO_ERROR             on success
	//	@return ERR_INVALID_PARAM    one of the parameters is invalid
	SetWebcamPriorities(ctx context.Context, priorities map[string]Priority) (int32, error)
}
