// Code generated by "stringer -output=enum_strings.go -type=SerialSettingsParity,ModbusFunction,SpecificModbusErrors"; DO NOT EDIT.

package modbuscfg

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NONE-0]
	_ = x[EVEN-1]
	_ = x[ODD-2]
}

const _SerialSettingsParity_name = "NONEEVENODD"

var _SerialSettingsParity_index = [...]uint8{0, 4, 8, 11}

func (i SerialSettingsParity) String() string {
	if i < 0 || i >= SerialSettingsParity(len(_SerialSettingsParity_index)-1) {
		return "SerialSettingsParity(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SerialSettingsParity_name[_SerialSettingsParity_index[i]:_SerialSettingsParity_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[COIL-0]
	_ = x[DISCRETE_INPUT-1]
	_ = x[HOLDING_REGISTER-2]
	_ = x[INPUT_REGISTER-3]
}

const _ModbusFunction_name = "COILDISCRETE_INPUTHOLDING_REGISTERINPUT_REGISTER"

var _ModbusFunction_index = [...]uint8{0, 4, 18, 34, 48}

func (i ModbusFunction) String() string {
	if i < 0 || i >= ModbusFunction(len(_ModbusFunction_index)-1) {
		return "ModbusFunction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ModbusFunction_name[_ModbusFunction_index[i]:_ModbusFunction_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ERROR_BADCRC-0]
	_ = x[ERROR_BADDATA-1]
	_ = x[ERROR_BADEXC-2]
	_ = x[ERROR_UNKEXC-3]
	_ = x[ERROR_MDATA-4]
	_ = x[ERROR_OTHER-5]
}

const _SpecificModbusErrors_name = "ERROR_BADCRCERROR_BADDATAERROR_BADEXCERROR_UNKEXCERROR_MDATAERROR_OTHER"

var _SpecificModbusErrors_index = [...]uint8{0, 12, 25, 37, 49, 60, 71}

func (i SpecificModbusErrors) String() string {
	if i < 0 || i >= SpecificModbusErrors(len(_SpecificModbusErrors_index)-1) {
		return "SpecificModbusErrors(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SpecificModbusErrors_name[_SpecificModbusErrors_index[i]:_SpecificModbusErrors_index[i+1]]
}
