// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package modbuscfg was generated by IDLC from ModbusCfg.idl.
// It is part of module peripheral.
// The remaining comment is for module peripheral.
//
// Peripheral Devices
package modbuscfg

import "github.com/arminguenther/xeruspower-go/v40300/idl"

const (
	EXCEPTION_ILLEGAL_FUNCTION        int32 = 1
	EXCEPTION_ILLEGAL_DATA_ADDRESS    int32 = 2
	EXCEPTION_ILLEGAL_DATA_VALUE      int32 = 3
	EXCEPTION_SLAVE_OR_SERVER_FAILURE int32 = 4
	EXCEPTION_ACKNOWLEDGE             int32 = 5
	EXCEPTION_SLAVE_OR_SERVER_BUSY    int32 = 6
	EXCEPTION_NEGATIVE_ACKNOWLEDGE    int32 = 7
	EXCEPTION_MEMORY_PARITY           int32 = 8
	EXCEPTION_GATEWAY_PATH            int32 = 10
	EXCEPTION_GATEWAY_TARGET          int32 = 11
)

type ModbusCfg interface {
	idl.Object
}

type SerialSettings struct {
	Baud     int32
	Parity   SerialSettingsParity
	DataBits int32
	StopBits int32
}

type SerialSettingsParity int

const (
	NONE SerialSettingsParity = iota
	EVEN
	ODD
)

type ModbusFunction int

const (
	COIL ModbusFunction = iota
	DISCRETE_INPUT
	HOLDING_REGISTER
	INPUT_REGISTER
)

type SpecificModbusErrors int

const (
	ERROR_BADCRC SpecificModbusErrors = iota
	ERROR_BADDATA
	ERROR_BADEXC
	ERROR_UNKEXC
	ERROR_MDATA
	ERROR_OTHER
)
