// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package zigbeedevice was generated by IDLC from ZigbeeDevice.idl.
// It is part of module zigbee.
// The remaining comment is for module zigbee.
//
// Zigbee
package zigbeedevice

import (
	"context"
	"time"

	"github.com/arminguenther/xeruspower-go/v40100/idl"
	"github.com/arminguenther/xeruspower-go/v40100/idl/event"
)

// Supported Cluster Types
// defined by zigbee alliance in the zigbee cluster library specification
const (
	CLUSTER_BASIC               int32 = 0x0
	CLUSTER_POWER_CONFIGURATION int32 = 0x1
	CLUSTER_RSSI                int32 = 0xb
	CLUSTER_CONTACT_CLOSURE     int32 = 0xf
	CLUSTER_TEMPERATURE         int32 = 0x402
	CLUSTER_HUMIDITY            int32 = 0x405
)

// Zigbee Device
type ZigbeeDevice interface {
	idl.Object

	// Retrieve Dongle MetaData
	//
	//	@return MetaData
	GetMetaData(ctx context.Context) (MetaData, error)

	// Retrieve the last cluster values
	// Needed for battery voltage (only reported all 12h)
	//
	//	@return list of all cluster values currently reported
	GetClusterValues(ctx context.Context) ([]ClusterValue, error)
}

// Device MetaData
type MetaData struct {
	SourceId      int32   // the device source ID
	Clusters      []int32 // the clusters which are reporting to this device
	PreferredSlot int32   // the slot which should be assigned to the first sensor
}

// Cluster Value
type ClusterValue struct {
	Id        int32     // the cluster ID
	Endpoint  int32     // the endpoint ID
	Attribute int32     // the reported attribute. some clusters have multiple reporting attributes
	Timestamp time.Time // the time when the cluster value was updated. UNIX timestamp (UTC)
	Value     string    // the value which was reported.
}

// Cluster Value Changed Event
type ClusterDataEvent interface {
	event.Event
	Value() ClusterValue // the cluster value
	isClusterDataEvent()
}
