// SPDX-License-Identifier: BSD-3-Clause
// Copyright 2026 Raritan Inc. All rights reserved.

// Package serversslcert was generated by IDLC from ServerSSLCert.idl.
// It is part of module cert.
// The remaining comment is for module cert.
//
// TLS Certificate Management
package serversslcert

import (
	"context"

	"github.com/arminguenther/xeruspower-go/v40000/idl"
)

// success code
const SUCCESS int32 = 0

// key-pair generation error codes
const (
	ERR_GEN_KEY_LEN_INVALID        int32 = 100
	ERR_GEN_CSR_OR_CERT_PENDING    int32 = 101
	ERR_GEN_KEY_GEN_FAILED         int32 = 102
	ERR_GEN_KEY_TYPE_INVALID       int32 = 103
	ERR_GEN_ELLIPTIC_CURVE_INVALID int32 = 104
)

// key-pair installation error codes
const (
	ERR_INSTALL_KEY_MISSING         int32 = 200
	ERR_INSTALL_CERT_MISSING        int32 = 201
	ERR_INSTALL_CERT_FORMAT_INVALID int32 = 202
	ERR_INSTALL_CERT_KEY_MISMATCH   int32 = 203
	ERR_INSTALL_KEY_FORMAT_INVALID  int32 = 204
)

// TLS certificate management interface
type ServerSSLCert interface {
	idl.Object

	// Generate an unsigned key pair.
	//
	//	@param reqInfo    Certificate signing request information
	//	@param challenge  Challenge password
	//
	//	@return SUCCESS or one of the error code constants
	GenerateUnsignedKeyPair(ctx context.Context, reqInfo ReqInfo, challenge string) (int32, error)

	// Generate a self-signed key pair.
	//
	//	@param reqInfo  Certificate signing request information
	//	@param days     Number of days the certificate will be valid
	//
	//	@return SUCCESS or one of the error code constants
	GenerateSelfSignedKeyPair(ctx context.Context, reqInfo ReqInfo, days int32) (int32, error)

	// Remove a pending certificate signing request or certificate.
	DeletePending(ctx context.Context) error

	// Retrieve certificate manager information.
	//
	//	@param info  Result: Certificate manager information
	GetInfo(ctx context.Context) (info Info, err error)

	// Activate a pending key pair.
	//
	//	@return SUCCESS or one of the error code constants
	InstallPendingKeyPair(ctx context.Context) (int32, error)
}

// Certificate issuer or subject attributes
type CommonAttributes struct {
	Country            string // Country code
	StateOrProvince    string // State or province
	Locality           string // Locality or city
	Organization       string // Organization
	OrganizationalUnit string // Organizational Unit
	CommonName         string // Common Name
	EmailAddress       string // Email Address
}

// Supported key types
type KeyType int

const (
	KEY_TYPE_UNKNOWN KeyType = iota // Key type unknown (only allowed as return value)
	KEY_TYPE_RSA                    // RSA key
	KEY_TYPE_ECDSA                  // ECDSA key
)

// Supported elliptic curves for key type ECDSA
type EllipticCurve int

const (
	EC_CURVE_UNKNOWN   EllipticCurve = iota // Curve unknown (only allowed as return value)
	EC_CURVE_NIST_P256                      // NIST curve P-256 (also known as secp256r1 and prime256v1)
	EC_CURVE_NIST_P384                      // NIST curve P-384 (also known as secp384r1)
	EC_CURVE_NIST_P521                      // NIST curve P-521 (also known as secp521r1)
)

// Certificate signing request information
//
// If names is empty then commonName from the subject is used as single entry.
type ReqInfo struct {
	Subject       CommonAttributes // Certificate subject attributes
	Names         []string         // DNS names and/or IP addresses
	KeyType       KeyType          // Key type
	EllipticCurve EllipticCurve    // Selected elliptic curve (only relevant if key type is ECDSA)
	RsaKeyLength  int32            // Length of the RSA key in bits (only relevant if key type is RSA)
}

// Certificate information
type CertInfo struct {
	Subject       CommonAttributes // Subject attributes
	Issuer        CommonAttributes // Issuer attributes
	Names         []string         // DNS names and/or IP addresses
	InvalidBefore string           // Begin of validity period
	InvalidAfter  string           // End of validity period
	SerialNumber  string           // Serial number
	KeyType       KeyType          // Key type
	EllipticCurve EllipticCurve    // Selected elliptic curve (only relevant if key type is ECDSA)
	RsaKeyLength  int32            // Length of the RSA key in bits (only relevant if key type is RSA)
}

// Certificate manager information
type Info struct {
	HavePendingReq        bool       // true if a CSR is pending
	HavePendingCert       bool       // true if an uploaded certificate is pending activation
	PendingReqInfo        ReqInfo    // Information about pending CSR
	PendingCertInfo       CertInfo   // Information about pending certificate file (device certificate)
	PendingCertChainInfos []CertInfo // Information about pending certificate file (remaining certificate chain if available)
	ActiveCertInfo        CertInfo   // Information about active certificate file (device certificate)
	ActiveCertChainInfos  []CertInfo // Information about active certificate file (remaining certificate chain if available)
	MaxSignDays           int32      // Maximum number of days a self signed certificate will be valid.
}
